$rpcs = @{
    "agent_" = "Agents"
    "bridge_" = "Bridge"
    "channel" = "Channels"
    "coldwallet_" = "ColdWallet"
    "covenant_" = "Covenant"
    "disclose_" = "Disclosure"
    "escrow_" = "Escrow"
    "eth_" = "Ethereum RPC"
    "exchange_" = "Exchange"
    "follow" = "Social"
    "gov_" = "Governance"
    "grid_" = "Grid"
    "htlc_" = "HTLC/Swap"
    "identity_" = "Identity"
    "intent_" = "Intent"
    "kyc_" = "KYC"
    "mica_" = "MICA"
    "notarize" = "Notarize"
    "openchannel" = "Channels"
    "poap_" = "POAP"
    "profile_" = "Profile"
    "pq_" = "PQ Wallets"
    "setcategory" = "Names"
    "stake" = "Staking"
    "sub_" = "Subscriptions"
    "swap_" = "Atomic Swap"
    "timelock_" = "Timelock"
    "treasury_" = "Treasury"
    "validator_" = "Validators"
}

# Frontend pages
$frontend = @{
    "agents" = "AgentsPage"
    "bridge" = "BridgePage"
    "channels" = "ChannelsPage"
    "coldwallet" = "ColdWalletPanel"
    "covenant" = "CovenantPanel"
    "escrow" = "(embedded in ExchangePage)"
    "ethereum" = "(embedded in DexBuyPanel)"
    "exchange" = "ExchangePage"
    "governance" = "GovernancePage"
    "grid" = "GridPanel"
    "htlc" = "HtlcTradePanel"
    "identity" = "IdentityPanel"
    "kyc" = "KycPanel"
    "notarize" = "NotarizePage"
    "poap" = "PoapPage"
    "profile" = "ProfilePage"
    "reputation" = "ReputationPage"
    "stake" = "StakePage"
    "swap" = "AtomicSwapPanel"
    "timelock" = "TimelockPanel"
    "treasury" = "TreasuryPanel"
    "validators" = "ValidatorsPage"
    "wallet" = "WalletPage"
    "vault" = "VaultPage"
}

Write-Host "RPC Coverage Analysis:`n"
Write-Host "Missing Frontend Pages (in rpc_server but no Page/Panel):"
$missing = @()
$missing += "disclose_* (RPC exists)"
$missing += "intent_* (RPC exists)"
$missing += "pq_* / sendpqattest (PQ Wallets RPC exists)"
$missing += "setcategory / getnamesbycategory (Names extension)"
$missing += "sub_* (Subscriptions RPC exists)"
$missing += "mica_* (MICA RPC exists)"
$missing += "omnibus_* (OmniBus custom analytics)"
$missing += "profile_get/update/init (embedded in ProfilePage)"

$missing | % { Write-Host "  - $_" }
