#!/usr/bin/env bash
# fix-nginx.sh — Reset complet Nginx config pentru omnibusblockchain.cc
#
# Usage:
#   git pull origin main
#   chmod +x fix-nginx.sh
#   sudo bash fix-nginx.sh
#
# Ce face:
#   1. Verifica ca nodurile (mainnet/testnet/regtest) ruleaza
#   2. Restart Vite explorer
#   3. Rescrie /etc/nginx/sites-available/omnibusblockchain.cc COMPLET
#   4. Forteaza symlink corect in sites-enabled
#   5. Validate + reload Nginx
#   6. Verifica ca asculta pe 80 + 443
#   7. Test HTTPS RPC pe toate 3 chain-uri
#   8. Print diagnostic complet la final

set -uo pipefail

DOMAIN="omnibusblockchain.cc"
# Port HTTPS public — pe acest VPS portul 443 e blocat de iptables
# (port-knocking ruleaza pe el), deci folosim 8443 ca alternativa.
HTTPS_PORT="8443"
ROOT="/root/omnibus-blockchain"
NGINX_AVAIL="/etc/nginx/sites-available/${DOMAIN}"
NGINX_ENABL="/etc/nginx/sites-enabled/${DOMAIN}"
SSL_LIVE="/etc/letsencrypt/live/${DOMAIN}"

echo "=========================================="
echo " OmniBus Nginx + 3-node Reset"
echo "=========================================="
echo ""

# ---------------------------------------------------------------------------
# 1. Verifica ca cert-ul SSL exista
# ---------------------------------------------------------------------------
if [[ ! -f "${SSL_LIVE}/fullchain.pem" ]]; then
    echo "[ERR] Cert-ul SSL lipseste: ${SSL_LIVE}/fullchain.pem"
    echo "      Ruleaza intai: sudo certbot --nginx -d ${DOMAIN} -d www.${DOMAIN}"
    exit 1
fi
echo "[OK] Cert SSL gasit: ${SSL_LIVE}/"

# ---------------------------------------------------------------------------
# 2. Verifica nodurile
# ---------------------------------------------------------------------------
echo ""
echo "=== Status noduri OmniBus ==="
for c in mainnet testnet regtest; do
    if [[ -f "/run/omnibus/${c}.pid" ]] && kill -0 "$(cat /run/omnibus/${c}.pid)" 2>/dev/null; then
        printf "  %-10s UP  PID=%s\n" "$c" "$(cat /run/omnibus/${c}.pid)"
    else
        printf "  %-10s DOWN — pornire ...\n" "$c"
        cd "$ROOT" && bash start-all-vps.sh start | grep -E "$c"
    fi
done

# ---------------------------------------------------------------------------
# 3. Restart Vite explorer (preia codul nou de la git pull)
# ---------------------------------------------------------------------------
echo ""
echo "=== Restart Vite explorer ==="
pkill -f vite 2>/dev/null || true
sleep 1
rm -f /run/omnibus/explorer.pid

cd "${ROOT}/frontend"
nohup npm run dev -- --host 0.0.0.0 > /var/log/omnibus/explorer.log 2>&1 &
echo $! > /run/omnibus/explorer.pid
disown
sleep 3
echo "  Vite PID=$(cat /run/omnibus/explorer.pid)"

# ---------------------------------------------------------------------------
# 4. Rescrie config-ul Nginx — heredoc cu marker unic
# ---------------------------------------------------------------------------
echo ""
echo "=== Rescriu Nginx config ==="

cat > "${NGINX_AVAIL}" <<'NGINXCONF'
# OmniBus Blockchain — explorer + multi-chain RPC over HTTPS
# Auto-generated by fix-nginx.sh — do not edit manually.

server {
    listen 80;
    server_name omnibusblockchain.cc www.omnibusblockchain.cc;
    # Redirect catre HTTPS pe 8443 (portul 443 standard e blocat de iptables port-knock).
    return 301 https://$host:8443$request_uri;
}

server {
    listen 8443 ssl;
    server_name omnibusblockchain.cc www.omnibusblockchain.cc;

    ssl_certificate /etc/letsencrypt/live/omnibusblockchain.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/omnibusblockchain.cc/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Buffer limits
    client_max_body_size 10M;

    # ===== RPC chain proxies =====
    # `proxy_pass http://...:port/` cu trailing "/" face strip prefix automat:
    # /api-testnet/foo -> http://127.0.0.1:18332/foo
    # location = /api-testnet -> exact-match POST fara slash

    location /api-mainnet/ {
        proxy_pass http://127.0.0.1:8332/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
    }
    location = /api-mainnet {
        proxy_pass http://127.0.0.1:8332/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
    }

    location /api-testnet/ {
        proxy_pass http://127.0.0.1:18332/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
    }
    location = /api-testnet {
        proxy_pass http://127.0.0.1:18332/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
    }

    location /api-regtest/ {
        proxy_pass http://127.0.0.1:28332/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
    }
    location = /api-regtest {
        proxy_pass http://127.0.0.1:28332/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
    }

    # ===== WebSocket per chain — necesita Upgrade headers =====
    location /ws-mainnet {
        proxy_pass http://127.0.0.1:8334/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }
    location /ws-testnet {
        proxy_pass http://127.0.0.1:18334/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }
    location /ws-regtest {
        proxy_pass http://127.0.0.1:28334/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }

    # ===== Default — Vite explorer (cu HMR WebSocket) =====
    # Vite 4 face host check pe Host header; ii trimitem localhost ca sa
    # nu mai conteze ce a cerut clientul. SSL termiat tot in Nginx, deci
    # bypass-ul Host header e safe (nu ajunge la backend).
    location / {
        proxy_pass http://127.0.0.1:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host "localhost:8888";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
NGINXCONF

# Verifica linii — daca-i sub 50, heredoc-ul a fost taiat
LINES=$(wc -l < "${NGINX_AVAIL}")
echo "  Config scris: ${LINES} linii in ${NGINX_AVAIL}"
if [[ "${LINES}" -lt 80 ]]; then
    echo "[ERR] Config-ul pare incomplet (${LINES} linii, asteptam 100+)"
    echo "      Verifica manual ${NGINX_AVAIL}"
    exit 1
fi

# ---------------------------------------------------------------------------
# 5. Forteaza symlink corect (certbot poate creat fisier real)
# ---------------------------------------------------------------------------
rm -f "${NGINX_ENABL}"
ln -sf "${NGINX_AVAIL}" "${NGINX_ENABL}"
echo "[OK] Symlink: ${NGINX_ENABL} -> ${NGINX_AVAIL}"

# ---------------------------------------------------------------------------
# 5b. Dezactiveaza vechiul `default` site (intercepteaza :443 cu cert
#     self-signed pe 38.143.19.97 si blocheaza tot traficul HTTPS catre noi).
# ---------------------------------------------------------------------------
if [[ -L /etc/nginx/sites-enabled/default ]]; then
    rm -f /etc/nginx/sites-enabled/default
    echo "[OK] Dezactivat /etc/nginx/sites-enabled/default (era default site vechi)"
fi

# ---------------------------------------------------------------------------
# 6. Validate + reload
# ---------------------------------------------------------------------------
echo ""
echo "=== Nginx validate + reload ==="
if ! nginx -t 2>&1; then
    echo "[ERR] Config invalid — nu fac reload"
    exit 1
fi
systemctl reload nginx
echo "[OK] Nginx reloaded"

# ---------------------------------------------------------------------------
# 7. Verifica porturi LISTEN
# ---------------------------------------------------------------------------
echo ""
echo "=== Porturi LISTEN ==="
ss -tlnp 2>/dev/null | grep -E ':(80|443|8332|8334|8888|18332|18334|28332|28334|9000|9001|9002) ' | sort

# ---------------------------------------------------------------------------
# 8. Test direct backend (ca sa stim ca node-ul merge)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test direct la backend (bypass Nginx) ==="
for spec in "mainnet:8332" "testnet:18332" "regtest:28332"; do
    chain="${spec%:*}"
    port="${spec#*:}"
    printf "  %-10s :%s -> " "$chain" "$port"
    result=$(curl -s -m 3 "http://127.0.0.1:${port}" \
        -X POST -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","id":1,"method":"getblockcount","params":[]}' 2>&1 || echo "TIMEOUT")
    echo "${result}"
done

# ---------------------------------------------------------------------------
# 9. Test prin Nginx HTTPS pe portul real (8443, nu 443 standard)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test HTTPS prin Nginx pe :${HTTPS_PORT} ==="
for chain in mainnet testnet regtest; do
    printf "  /api-%s -> " "$chain"
    result=$(curl -s -m 5 "https://${DOMAIN}:${HTTPS_PORT}/api-${chain}" \
        -X POST -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","id":1,"method":"getblockcount","params":[]}' 2>&1 || echo "TIMEOUT")
    if [[ -z "${result}" ]]; then
        echo "[empty response]"
    else
        echo "${result}"
    fi
done

# ---------------------------------------------------------------------------
# 10. Test pagina root (Vite)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test pagina explorer ==="
status=$(curl -sI -m 5 "https://${DOMAIN}:${HTTPS_PORT}/" | head -1 || echo "TIMEOUT")
echo "  GET / -> ${status}"

# ---------------------------------------------------------------------------
# 11. Diagnostic la final
# ---------------------------------------------------------------------------
echo ""
echo "=== Nginx error log (ultimele 10 linii) ==="
tail -10 /var/log/nginx/error.log 2>/dev/null || echo "  (gol)"

echo ""
echo "=========================================="
echo " URL-uri publice (port ${HTTPS_PORT} fiindca 443 e blocat de iptables):"
echo "   https://${DOMAIN}:${HTTPS_PORT}                  -> Explorer"
echo "   https://${DOMAIN}:${HTTPS_PORT}/api-mainnet      -> Mainnet RPC"
echo "   https://${DOMAIN}:${HTTPS_PORT}/api-testnet      -> Testnet RPC"
echo "   https://${DOMAIN}:${HTTPS_PORT}/api-regtest      -> Regtest RPC"
echo "=========================================="
