// rpc-reference.ts — Static catalog of all OmniBus JSON-RPC 2.0 methods.
// Extracted from core/rpc_server.zig (dispatch table at ~line 3955).
// Used by DocsPage for search/filter without needing to parse JSX.

export interface RpcMethod {
  method: string;
  category: string;
  description: string;
  params: string;
  example: string;
}

export const RPC_METHODS: RpcMethod[] = [
  // ── Chain Info ──────────────────────────────────────────────────────────────
  {
    method: "getblockcount",
    category: "Chain Info",
    description: "Returns the current chain height (number of blocks mined).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblockcount","params":[]}\n// → {"result":12345}',
  },
  {
    method: "getblockchaininfo",
    category: "Chain Info",
    description: "Full chain info: chain name, height, best hash, difficulty, supply.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblockchaininfo","params":[]}',
  },
  {
    method: "getblock",
    category: "Chain Info",
    description: "Get a block by height.",
    params: "[height: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblock","params":[100]}',
  },
  {
    method: "getblocks",
    category: "Chain Info",
    description: "Get multiple blocks starting at height.",
    params: "[from: number, count: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblocks","params":[100,10]}',
  },
  {
    method: "getlatestblock",
    category: "Chain Info",
    description: "Returns the most recently mined block.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getlatestblock","params":[]}',
  },
  {
    method: "getblockhash",
    category: "Chain Info",
    description: "Get block hash at given height.",
    params: "[height: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblockhash","params":[42]}',
  },
  {
    method: "getbestblockhash",
    category: "Chain Info",
    description: "Hash of the current chain tip.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getbestblockhash","params":[]}',
  },
  {
    method: "getdifficulty",
    category: "Chain Info",
    description: "Current PoW difficulty target.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getdifficulty","params":[]}',
  },
  {
    method: "getstatus",
    category: "Chain Info",
    description: "Combined chain status: height, mempool size, peers, sync.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getstatus","params":[]}',
  },
  {
    method: "getchainmetrics",
    category: "Chain Info",
    description: "Detailed chain metrics: TPS, block intervals, fee averages.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getchainmetrics","params":[]}',
  },
  {
    method: "getperformance",
    category: "Chain Info",
    description: "Runtime performance counters (CPU, memory, TX/s).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getperformance","params":[]}',
  },
  {
    method: "getheaders",
    category: "Chain Info",
    description: "Get block headers for light-client SPV verification.",
    params: "[from_height: number, count: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getheaders","params":[0,100]}',
  },
  {
    method: "getmerkleproof",
    category: "Chain Info",
    description: "Merkle proof for a transaction (SPV).",
    params: '["tx_hash_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getmerkleproof","params":["abc123..."]}',
  },
  // ── Wallet ──────────────────────────────────────────────────────────────────
  {
    method: "getbalance",
    category: "Wallet",
    description: "Node wallet balance in satoshis (1 OMNI = 1,000,000,000 sat).",
    params: "[] or [address]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getbalance","params":[]}',
  },
  {
    method: "getaddressbalance",
    category: "Wallet",
    description: "Balance of any on-chain address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getaddressbalance","params":["ob1qzhrauq0xe9hg033ccup7vlgsdmj6kcxyza9zp0"]}',
  },
  {
    method: "getwalletsummary",
    category: "Wallet",
    description: "Atomic snapshot: wallet, staked, in_orders, available. Also returns open orders and locks.",
    params: '["ob1q..."] or {"address":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"getwalletsummary","params":["ob1q..."]}\n// → {"wallet":100,"staked":20,"in_orders":5,"available":75}',
  },
  {
    method: "listunspent",
    category: "Wallet",
    description: "List unspent transaction outputs (UTXOs) for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"listunspent","params":["ob1q..."]}',
  },
  {
    method: "getaddresshistory",
    category: "Wallet",
    description: "Full TX history for an address (sent/received/mined/staked).",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getaddresshistory","params":["ob1q..."]}',
  },
  {
    method: "listtransactions",
    category: "Wallet",
    description: "List recent transactions from node wallet.",
    params: "[count: number]  (default 10)",
    example: '{"jsonrpc":"2.0","id":1,"method":"listtransactions","params":[20]}',
  },
  {
    method: "gettransaction",
    category: "Wallet",
    description: "Get transaction details by hash.",
    params: '["tx_hash_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"gettransaction","params":["deadbeef..."]}',
  },
  {
    method: "gettransactions",
    category: "Wallet",
    description: "Batch-fetch multiple transactions.",
    params: '["hash1","hash2",...]',
    example: '{"jsonrpc":"2.0","id":1,"method":"gettransactions","params":[["hash1","hash2"]]}',
  },
  {
    method: "sendtransaction",
    category: "Wallet",
    description: "Broadcast a signed transaction to the network.",
    params: '["to_address", amount_sat, fee_sat]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendtransaction","params":["ob1q...",1000000000,10000]}',
  },
  {
    method: "sendrawtransaction",
    category: "Wallet",
    description: "Broadcast a raw hex-encoded transaction.",
    params: '["raw_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendrawtransaction","params":["0200000001..."]}',
  },
  {
    method: "sendopreturn",
    category: "Wallet",
    description: "Send a transaction with OP_RETURN data (used for name registrations, memos).",
    params: '["data_string", fee_sat] or {"data":"...","fee":100}',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendopreturn","params":["ns:alice.omnibus:ob1q...",10000]}',
  },
  {
    method: "minersendtx",
    category: "Wallet",
    description: "Miner-signed transaction (used by mining pool).",
    params: '["from_addr","to_addr",amount_sat,fee_sat]',
    example: '{"jsonrpc":"2.0","id":1,"method":"minersendtx","params":["ob1q...","ob1q...",1000,100]}',
  },
  {
    method: "estimatefee",
    category: "Wallet",
    description: "Estimate fee for next block inclusion.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"estimatefee","params":[]}',
  },
  {
    method: "getnonce",
    category: "Wallet",
    description: "Get the next transaction nonce for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getnonce","params":["ob1q..."]}',
  },
  {
    method: "getrichlist",
    category: "Wallet",
    description: "Top N addresses by balance. Includes roles[] badges.",
    params: "[count: number]  (default 100)",
    example: '{"jsonrpc":"2.0","id":1,"method":"getrichlist","params":[50]}',
  },
  {
    method: "getdailyactivity",
    category: "Wallet",
    description: "Per-day TX breakdown for an address (useful for audit charts).",
    params: '["ob1q...", days?]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getdailyactivity","params":["ob1q...",30]}',
  },
  // ── Mempool / Network ────────────────────────────────────────────────────────
  {
    method: "getmempoolsize",
    category: "Network",
    description: "Number of pending transactions in the mempool.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmempoolsize","params":[]}',
  },
  {
    method: "getmempoolstats",
    category: "Network",
    description: "Mempool stats: size, bytes, fee histogram.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmempoolstats","params":[]}',
  },
  {
    method: "getmempoolinfo",
    category: "Network",
    description: "Alias for getmempoolstats. Also aliased as getrawmempool / getmempool.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmempoolinfo","params":[]}',
  },
  {
    method: "getpeers",
    category: "Network",
    description: "List connected P2P peers.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getpeers","params":[]}',
  },
  {
    method: "getpeerinfo",
    category: "Network",
    description: "Detailed peer info (latency, version, services).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getpeerinfo","params":[]}',
  },
  {
    method: "getnetworkinfo",
    category: "Network",
    description: "Network info: version, subversion, connections, local addresses.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getnetworkinfo","params":[]}',
  },
  {
    method: "getconnectioncount",
    category: "Network",
    description: "Number of active P2P connections.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getconnectioncount","params":[]}',
  },
  {
    method: "getsyncstatus",
    category: "Network",
    description: "IBD sync progress: headers/blocks synced vs chain tip.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getsyncstatus","params":[]}',
  },
  {
    method: "getnodelist",
    category: "Network",
    description: "Known nodes in the DHT routing table.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getnodelist","params":[]}',
  },
  // ── Mining ───────────────────────────────────────────────────────────────────
  {
    method: "getminerstats",
    category: "Mining",
    description: "Miner statistics: hashrate, blocks found, rewards.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getminerstats","params":[]}',
  },
  {
    method: "getminerinfo",
    category: "Mining",
    description: "Info about the node's own miner (address, hashrate, rewards).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getminerinfo","params":[]}',
  },
  {
    method: "getmininginfo",
    category: "Mining",
    description: "Mining info: difficulty, network hashrate, block reward.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmininginfo","params":[]}',
  },
  {
    method: "getpoolstats",
    category: "Mining",
    description: "Mining pool stats: connected miners, total hashrate, last payout.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getpoolstats","params":[]}',
  },
  {
    method: "getslotleader",
    category: "Mining",
    description: "Current slot leader address for PoUW slot-based mining.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getslotleader","params":[]}',
  },
  {
    method: "getslotcalendar",
    category: "Mining",
    description: "Upcoming slot assignments for the next N blocks.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getslotcalendar","params":[]}',
  },
  {
    method: "getclockstatus",
    category: "Mining",
    description: "Node clock drift vs NTP and slot timing status.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getclockstatus","params":[]}',
  },
  {
    method: "getfuturepool",
    category: "Mining",
    description: "Transactions pre-committed for future blocks.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getfuturepool","params":[]}',
  },
  {
    method: "registerminer",
    category: "Mining",
    description: "Register a miner address with the network.",
    params: '["address","node_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"registerminer","params":["ob1q...","miner-1"]}',
  },
  {
    method: "omnibus_getminers",
    category: "Mining",
    description: "List all known miners registered on chain.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getminers","params":[]}',
  },
  {
    method: "omnibus_gettotalmined",
    category: "Mining",
    description: "Total OMNI mined across the entire network (explorer stat).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_gettotalmined","params":[]}',
  },
  // ── Staking & Validators ─────────────────────────────────────────────────────
  {
    method: "stake",
    category: "Staking",
    description: "Stake OMNI to become a validator candidate.",
    params: '["address", amount_sat, "privkey_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"stake","params":["ob1q...",10000000000,"aabbcc..."]}',
  },
  {
    method: "unstake",
    category: "Staking",
    description: "Unstake OMNI (subject to unbonding period).",
    params: '["address", amount_sat, "privkey_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"unstake","params":["ob1q...",10000000000,"aabbcc..."]}',
  },
  {
    method: "getstake",
    category: "Staking",
    description: "Current stake amount and status for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getstake","params":["ob1q..."]}',
  },
  {
    method: "getstakers",
    category: "Staking",
    description: "List of all stakers sorted by stake amount.",
    params: "[limit?]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getstakers","params":[20]}',
  },
  {
    method: "getvalidators",
    category: "Staking",
    description: "List of current active validators.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getvalidators","params":[]}',
  },
  {
    method: "getvalidatorsv2",
    category: "Staking",
    description: "Validators v2: includes soulbound tier, uptime, slash history.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getvalidatorsv2","params":[]}',
  },
  {
    method: "become_validator",
    category: "Staking",
    description: "Promote staker to active validator set.",
    params: '["address","pubkey_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"become_validator","params":["ob1q...","03..."]}',
  },
  {
    method: "validator_heartbeat",
    category: "Staking",
    description: "Keep-alive ping for active validators (prevents slashing).",
    params: '["validator_addr","sig_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"validator_heartbeat","params":["ob1q...","sig..."]}',
  },
  {
    method: "getstakinginfo",
    category: "Staking",
    description: "Staking parameters: min stake, unbonding days, epoch.",
    params: '["validator_addr"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getstakinginfo","params":["ob1q..."]}',
  },
  {
    method: "submitslashevidence",
    category: "Staking",
    description: "Submit double-sign evidence to slash a misbehaving validator.",
    params: '["validator_addr","double_sign","hash1","hash2",height,"reporter_addr"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"submitslashevidence","params":["ob1q...","double_sign","h1","h2",100,"ob1q..."]}',
  },
  {
    method: "getslashhistory",
    category: "Staking",
    description: "Slash events for a validator.",
    params: '["validator_addr"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getslashhistory","params":["ob1q..."]}',
  },
  {
    method: "getslashevents",
    category: "Staking",
    description: "All recent slash events on the network.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getslashevents","params":[]}',
  },
  // ── DNS / Names ──────────────────────────────────────────────────────────────
  {
    method: "registername",
    category: "Names",
    description: "Register a .omnibus / .arbitraje / .bank name on-chain.",
    params: '{"name":"alice.omnibus","address":"ob1q...","owner":"ob1q...","fee_sat":5000000000}',
    example: '{"jsonrpc":"2.0","id":1,"method":"registername","params":[{"name":"alice.omnibus","address":"ob1q...","owner":"ob1q...","fee_sat":5000000000}]}',
  },
  {
    method: "resolvename",
    category: "Names",
    description: "Resolve a name to an on-chain address.",
    params: '["alice.omnibus"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"resolvename","params":["alice.omnibus"]}',
  },
  {
    method: "ns_resolveforsend",
    category: "Names",
    description: "Resolve name and validate it can receive funds.",
    params: '["alice.omnibus"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_resolveforsend","params":["alice.omnibus"]}',
  },
  {
    method: "reverseresolvename",
    category: "Names",
    description: "Reverse lookup: address → name.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"reverseresolvename","params":["ob1q..."]}',
  },
  {
    method: "listnames",
    category: "Names",
    description: "List all registered names, optionally filtered by owner.",
    params: '[{"owner":"ob1q..."}]  (optional)',
    example: '{"jsonrpc":"2.0","id":1,"method":"listnames","params":[{"owner":"ob1q..."}]}',
  },
  {
    method: "renewname",
    category: "Names",
    description: "Renew a name registration before expiry.",
    params: '["alice.omnibus","owner_addr","sig"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"renewname","params":["alice.omnibus","ob1q...","sig"]}',
  },
  {
    method: "transfername",
    category: "Names",
    description: "Transfer a name to a new owner address.",
    params: '["alice.omnibus","new_owner","sig"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"transfername","params":["alice.omnibus","ob1q...","sig"]}',
  },
  {
    method: "updatename",
    category: "Names",
    description: "Update the resolved address for a name.",
    params: '["alice.omnibus","new_addr","sig"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"updatename","params":["alice.omnibus","ob1q...","sig"]}',
  },
  {
    method: "getensfee",
    category: "Names",
    description: "Get registration fee for a name (varies by TLD and length).",
    params: '["alice.omnibus"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getensfee","params":["alice.omnibus"]}',
  },
  {
    method: "ns_listTlds",
    category: "Names",
    description: "List all supported TLDs (.omnibus, .arbitraje, .bank, etc.).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_listTlds","params":[]}',
  },
  {
    method: "ns_stats",
    category: "Names",
    description: "Registry stats: total names, registrations today, by TLD.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_stats","params":[]}',
  },
  {
    method: "ns_expiringSoon",
    category: "Names",
    description: "Names expiring in the next N days.",
    params: "[days: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_expiringSoon","params":[30]}',
  },
  {
    method: "getnamesbycategory",
    category: "Names",
    description: "Names filtered by category tag.",
    params: '["category_slug"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getnamesbycategory","params":["defi"]}',
  },
  // ── Exchange / DEX ────────────────────────────────────────────────────────────
  {
    method: "exchange_listPairs",
    category: "Exchange",
    description: "List all trading pairs with pair_id. IDs are fixed forever.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_listPairs","params":[]}',
  },
  {
    method: "exchange_pairInfo",
    category: "Exchange",
    description: "Info for a pair: maker_chains[], taker_chains[], 24h stats.",
    params: "[pair_id: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_pairInfo","params":[0]}',
  },
  {
    method: "exchange_getOrderbook",
    category: "Exchange",
    description: "Current orderbook (bids/asks) for a pair.",
    params: "[pair_id: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getOrderbook","params":[3]}',
  },
  {
    method: "exchange_placeOrder",
    category: "Exchange",
    description: "Place a limit order on the DEX orderbook.",
    params: '{"pair_id":0,"side":"buy","price":100,"amount":1000000000,"owner":"ob1q...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_placeOrder","params":[{"pair_id":0,"side":"buy","price":100,"amount":1000000000,"owner":"ob1q..."}]}',
  },
  {
    method: "exchange_cancelOrder",
    category: "Exchange",
    description: "Cancel an open order.",
    params: '{"order_id":"uuid","owner":"ob1q...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_cancelOrder","params":[{"order_id":"...","owner":"ob1q..."}]}',
  },
  {
    method: "exchange_getUserOrders",
    category: "Exchange",
    description: "All open orders for a given user address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getUserOrders","params":["ob1q..."]}',
  },
  {
    method: "exchange_getTrades",
    category: "Exchange",
    description: "Recent trades for a pair.",
    params: "[pair_id: number, limit?: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getTrades","params":[0,50]}',
  },
  {
    method: "exchange_getStats",
    category: "Exchange",
    description: "24h stats for a pair: volume, high, low, last price.",
    params: "[pair_id: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getStats","params":[0]}',
  },
  {
    method: "exchange_depositReal",
    category: "Exchange",
    description: "Initiate a real cross-chain deposit into DEX escrow via HTLC.",
    params: '{"pair_id":0,"amount":1000,"chain":"omni","address":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_depositReal","params":[{"pair_id":0,"amount":1000,"chain":"omni","address":"ob1q..."}]}',
  },
  {
    method: "exchange_getEscrowAddress",
    category: "Exchange",
    description: "Returns the DEX escrow address (never deposit manually; use depositReal).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getEscrowAddress","params":[]}',
  },
  {
    method: "exchange_getBalance",
    category: "Exchange",
    description: "Exchange balance for an address (in-DEX custody).",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getBalance","params":["ob1q..."]}',
  },
  // ── Grid Trading ─────────────────────────────────────────────────────────────
  {
    method: "grid_create",
    category: "Grid",
    description: "Create an automated market-making grid. Chain generates N buy + N sell orders.",
    params: '{"pair_id":0,"price_low":95,"price_high":105,"levels":5,"total_base":10,"total_quote":1000,"owner":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_create","params":[{"pair_id":0,"price_low":95,"price_high":105,"levels":5,"total_base":10,"total_quote":1000,"owner":"ob1q..."}]}',
  },
  {
    method: "grid_list",
    category: "Grid",
    description: "List active grids, optionally filtered by owner.",
    params: '{"owner":"ob1q..."}  (optional)',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_list","params":[{"owner":"ob1q..."}]}',
  },
  {
    method: "grid_status",
    category: "Grid",
    description: "Grid details: fills, P&L, currently active orders.",
    params: '{"grid_id":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_status","params":[{"grid_id":"..."}]}',
  },
  {
    method: "grid_cancel",
    category: "Grid",
    description: "Stop a grid. Funds stay in user wallet (never locked until fill).",
    params: '{"grid_id":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_cancel","params":[{"grid_id":"..."}]}',
  },
  // ── HTLC ────────────────────────────────────────────────────────────────────
  {
    method: "htlc_init",
    category: "HTLC",
    description: "Create a Hash Time-Locked Contract for atomic cross-chain swap. Preimage generated server-side.",
    params: '{"pair_id":0,"maker":"ob1q...","taker":"ob1q...","amount":1000,"timelock_blocks":144}',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_init","params":[{"pair_id":0,"maker":"ob1q...","taker":"0x...","amount":1000}]}',
  },
  {
    method: "htlc_claim",
    category: "HTLC",
    description: "Claim HTLC funds by revealing the preimage.",
    params: '{"htlc_id":"...","preimage_hex":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_claim","params":[{"htlc_id":"...","preimage_hex":"..."}]}',
  },
  {
    method: "htlc_refund",
    category: "HTLC",
    description: "Refund expired HTLC back to maker.",
    params: '{"htlc_id":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_refund","params":[{"htlc_id":"..."}]}',
  },
  {
    method: "htlc_get",
    category: "HTLC",
    description: "Get HTLC status by ID.",
    params: '["htlc_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_get","params":["htlc_id_here"]}',
  },
  {
    method: "htlc_listByAddress",
    category: "HTLC",
    description: "List HTLCs involving an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_listByAddress","params":["ob1q..."]}',
  },
  {
    method: "htlc_listPending",
    category: "HTLC",
    description: "All pending (unclaimed/unrefunded) HTLCs.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_listPending","params":[]}',
  },
  // ── Identity / Profile ────────────────────────────────────────────────────────
  {
    method: "getdid",
    category: "Identity",
    description: "Get the W3C-compatible DID document for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getdid","params":["ob1q..."]}',
  },
  {
    method: "getobm",
    category: "Identity",
    description: "Get OmniBus Binary Map (OBM) — 8-bit badge vector for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getobm","params":["ob1q..."]}',
  },
  {
    method: "getfacets",
    category: "Identity",
    description: "Get the 4 identity facets (Social/Professional/Cultural/Economic) with Merkle proofs.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getfacets","params":["ob1q..."]}',
  },
  {
    method: "profile_init",
    category: "Identity",
    description: "Initialize profile for an address (first-time setup).",
    params: '{"address":"ob1q...","display_name":"Alice"}',
    example: '{"jsonrpc":"2.0","id":1,"method":"profile_init","params":[{"address":"ob1q...","display_name":"Alice"}]}',
  },
  {
    method: "profile_get",
    category: "Identity",
    description: "Get full profile: name, facets, OBM, reputation cups.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"profile_get","params":["ob1q..."]}',
  },
  {
    method: "profile_update",
    category: "Identity",
    description: "Update profile fields.",
    params: '{"address":"ob1q...","display_name":"Bob","bio":"...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"profile_update","params":[{"address":"ob1q...","display_name":"Bob"}]}',
  },
  {
    method: "mica_attest",
    category: "Identity",
    description: "Attach MiCA (EU crypto regulation) attestation to an address.",
    params: '{"address":"ob1q...","mica_type":"EMT","issuer":"ob1q...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"mica_attest","params":[{"address":"ob1q...","mica_type":"EMT"}]}',
  },
  {
    method: "mica_disclose",
    category: "Identity",
    description: "Selective disclosure of MiCA compliance fields.",
    params: '{"address":"ob1q...","fields":["mica_type","issuer"]}',
    example: '{"jsonrpc":"2.0","id":1,"method":"mica_disclose","params":[{"address":"ob1q...","fields":["mica_type"]}]}',
  },
  {
    method: "getreputation",
    category: "Identity",
    description: "4-cup reputation (LOVE/FOOD/RENT/VACATION) and total score for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getreputation","params":["ob1q..."]}',
  },
  {
    method: "getreputationtop",
    category: "Identity",
    description: "Top N addresses by reputation score.",
    params: "[limit: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getreputationtop","params":[50]}',
  },
  // ── Agents ────────────────────────────────────────────────────────────────────
  {
    method: "agent_list",
    category: "Agents",
    description: "List all registered autonomous trading agents.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_list","params":[]}',
  },
  {
    method: "agent_register",
    category: "Agents",
    description: "Register a new AI agent on-chain.",
    params: '{"name":"MyBot","owner":"ob1q...","strategy":"grid","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_register","params":[{"name":"MyBot","owner":"ob1q..."}]}',
  },
  {
    method: "agent_unregister",
    category: "Agents",
    description: "Remove an agent from the registry.",
    params: '{"agent_id":"...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_unregister","params":[{"agent_id":"..."}]}',
  },
  {
    method: "agent_status",
    category: "Agents",
    description: "Current status and last decisions of an agent.",
    params: '["agent_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_status","params":["agent_id_here"]}',
  },
  {
    method: "agent_pending_decisions",
    category: "Agents",
    description: "Pending decisions queued for an agent.",
    params: '["agent_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_pending_decisions","params":["agent_id"]}',
  },
  // ── Bridge ────────────────────────────────────────────────────────────────────
  {
    method: "getbridgestatus",
    category: "Bridge",
    description: "Status of cross-chain bridge (locked amounts, pending transfers).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getbridgestatus","params":[]}',
  },
  {
    method: "bridge_lock",
    category: "Bridge",
    description: "Lock OMNI on OmniBus chain to bridge to EVM chain.",
    params: '{"amount":1000000000,"to_chain":"base","to_address":"0x...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"bridge_lock","params":[{"amount":1000000000,"to_chain":"base","to_address":"0x..."}]}',
  },
  {
    method: "omnibus_getbridgestatus",
    category: "Bridge",
    description: "Extended bridge status including fee limits and supported chains.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getbridgestatus","params":[]}',
  },
  {
    method: "omnibus_bridge_limits",
    category: "Bridge",
    description: "Min/max bridge amounts and cooldown per chain.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_bridge_limits","params":[]}',
  },
  // ── Oracle / Prices ────────────────────────────────────────────────────────────
  {
    method: "omnibus_getoracleprices",
    category: "Oracle",
    description: "All price feeds from the distributed oracle (Chainlink/Pyth/CoinGecko).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getoracleprices","params":[]}',
  },
  {
    method: "omnibus_getallprices",
    category: "Oracle",
    description: "All prices in a single call including cross-rates.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getallprices","params":[]}',
  },
  {
    method: "omnibus_getarbitrage",
    category: "Oracle",
    description: "Current arbitrage opportunities across oracle feeds.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getarbitrage","params":[]}',
  },
  {
    method: "omnibus_getexchangefeed",
    category: "Oracle",
    description: "Real-time feed from connected external exchanges.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getexchangefeed","params":[]}',
  },
  // ── PQ / Post-Quantum ─────────────────────────────────────────────────────────
  {
    method: "pq_listSchemes",
    category: "Post-Quantum",
    description: "List supported PQ signature schemes (ML-DSA-87, Falcon-512, SLH-DSA, ML-KEM-768).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_listSchemes","params":[]}',
  },
  {
    method: "pq_balance",
    category: "Post-Quantum",
    description: "Balance on a PQ soulbound address.",
    params: '["obk1_..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_balance","params":["obk1_..."]}',
  },
  {
    method: "pq_attestation",
    category: "Post-Quantum",
    description: "Get pq_attest record (7 simultaneous signatures binding cross-chain identity).",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_attestation","params":["ob1q..."]}',
  },
  // ── Faucet ────────────────────────────────────────────────────────────────────
  {
    method: "claimfaucet",
    category: "Faucet",
    description: "Claim 0.1 OMNI from the testnet faucet. One claim per address per cooldown period.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"claimfaucet","params":["ob1q..."]}',
  },
  {
    method: "getfaucetstatus",
    category: "Faucet",
    description: "Faucet wallet balance, grant amount, and recent claims.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getfaucetstatus","params":[]}',
  },
  // ── Governance ───────────────────────────────────────────────────────────────
  {
    method: "gov_propose",
    category: "Governance",
    description: "Submit an on-chain governance proposal.",
    params: '{"title":"...","description":"...","type":"parameter_change","proposer":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"gov_propose","params":[{"title":"Increase block reward","type":"parameter_change","proposer":"ob1q..."}]}',
  },
  {
    method: "gov_vote",
    category: "Governance",
    description: "Vote on a governance proposal.",
    params: '{"proposal_id":1,"voter":"ob1q...","option":"yes","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"gov_vote","params":[{"proposal_id":1,"voter":"ob1q...","option":"yes"}]}',
  },
  {
    method: "getproposals",
    category: "Governance",
    description: "List all governance proposals (active/passed/rejected).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getproposals","params":[]}',
  },
  // ── Multisig ──────────────────────────────────────────────────────────────────
  {
    method: "createmultisig",
    category: "Advanced",
    description: "Create M-of-N multisig address.",
    params: "[M, [\"pubkey1_hex\", \"pubkey2_hex\", ...]]",
    example: '{"jsonrpc":"2.0","id":1,"method":"createmultisig","params":[2,["03abc...","03def..."]]}',
  },
  {
    method: "sendmultisig",
    category: "Advanced",
    description: "Send from multisig address with M signatures.",
    params: '["multisig_addr","to_addr",amount,fee,"privkey1","privkey2",...]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendmultisig","params":["ob1q...","ob1q...",1000,100,"key1","key2"]}',
  },
  // ── EVM Compatibility ─────────────────────────────────────────────────────────
  {
    method: "eth_call",
    category: "EVM",
    description: "EVM eth_call (read-only contract call on OmniBus EVM layer).",
    params: '[{"to":"0x...","data":"0x..."},"latest"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"to":"0x...","data":"0x..."},"latest"]}',
  },
  {
    method: "eth_chainId",
    category: "EVM",
    description: "OmniBus EVM chain ID (for MetaMask-compatible tooling).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}',
  },
  {
    method: "net_version",
    category: "EVM",
    description: "Network version string (EVM compatibility).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"net_version","params":[]}',
  },
];

export const RPC_CATEGORIES = [
  "Chain Info", "Wallet", "Network", "Mining", "Staking",
  "Names", "Exchange", "Grid", "HTLC", "Identity",
  "Agents", "Bridge", "Oracle", "Post-Quantum",
  "Faucet", "Governance", "Advanced", "EVM",
];
