// rpc-reference.ts — Static catalog of all OmniBus JSON-RPC 2.0 methods.
// Extracted from core/rpc_server.zig (dispatch table at ~line 3955).
// Used by DocsPage for search/filter without needing to parse JSX.

export interface RpcMethod {
  method: string;
  category: string;
  description: string;
  params: string;
  example: string;
}

export const RPC_METHODS: RpcMethod[] = [
  // ── Chain Info ──────────────────────────────────────────────────────────────
  {
    method: "getblockcount",
    category: "Chain Info",
    description: "Returns the current chain height (number of blocks mined).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblockcount","params":[]}\n// → {"result":12345}',
  },
  {
    method: "getblockchaininfo",
    category: "Chain Info",
    description: "Full chain info: chain name, height, best hash, difficulty, supply.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblockchaininfo","params":[]}',
  },
  {
    method: "getblock",
    category: "Chain Info",
    description: "Get a block by height.",
    params: "[height: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblock","params":[100]}',
  },
  {
    method: "getblocks",
    category: "Chain Info",
    description: "Get multiple blocks starting at height.",
    params: "[from: number, count: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblocks","params":[100,10]}',
  },
  {
    method: "getlatestblock",
    category: "Chain Info",
    description: "Returns the most recently mined block.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getlatestblock","params":[]}',
  },
  {
    method: "getblockhash",
    category: "Chain Info",
    description: "Get block hash at given height.",
    params: "[height: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getblockhash","params":[42]}',
  },
  {
    method: "getbestblockhash",
    category: "Chain Info",
    description: "Hash of the current chain tip.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getbestblockhash","params":[]}',
  },
  {
    method: "getdifficulty",
    category: "Chain Info",
    description: "Current PoW difficulty target.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getdifficulty","params":[]}',
  },
  {
    method: "getstatus",
    category: "Chain Info",
    description: "Combined chain status: height, mempool size, peers, sync.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getstatus","params":[]}',
  },
  {
    method: "getchainmetrics",
    category: "Chain Info",
    description: "Detailed chain metrics: TPS, block intervals, fee averages.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getchainmetrics","params":[]}',
  },
  {
    method: "getperformance",
    category: "Chain Info",
    description: "Runtime performance counters (CPU, memory, TX/s).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getperformance","params":[]}',
  },
  {
    method: "getheaders",
    category: "Chain Info",
    description: "Get block headers for light-client SPV verification.",
    params: "[from_height: number, count: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getheaders","params":[0,100]}',
  },
  {
    method: "getmerkleproof",
    category: "Chain Info",
    description: "Merkle proof for a transaction (SPV).",
    params: '["tx_hash_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getmerkleproof","params":["abc123..."]}',
  },
  // ── Wallet ──────────────────────────────────────────────────────────────────
  {
    method: "getbalance",
    category: "Wallet",
    description: "Node wallet balance in satoshis (1 OMNI = 1,000,000,000 sat).",
    params: "[] or [address]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getbalance","params":[]}',
  },
  {
    method: "getaddressbalance",
    category: "Wallet",
    description: "Balance of any on-chain address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getaddressbalance","params":["ob1qzhrauq0xe9hg033ccup7vlgsdmj6kcxyza9zp0"]}',
  },
  {
    method: "getwalletsummary",
    category: "Wallet",
    description: "Atomic snapshot: wallet, staked, in_orders, available. Also returns open orders and locks.",
    params: '["ob1q..."] or {"address":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"getwalletsummary","params":["ob1q..."]}\n// → {"wallet":100,"staked":20,"in_orders":5,"available":75}',
  },
  {
    method: "listunspent",
    category: "Wallet",
    description: "List unspent transaction outputs (UTXOs) for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"listunspent","params":["ob1q..."]}',
  },
  {
    method: "getaddresshistory",
    category: "Wallet",
    description: "Full TX history for an address (sent/received/mined/staked).",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getaddresshistory","params":["ob1q..."]}',
  },
  {
    method: "listtransactions",
    category: "Wallet",
    description: "List recent transactions from node wallet.",
    params: "[count: number]  (default 10)",
    example: '{"jsonrpc":"2.0","id":1,"method":"listtransactions","params":[20]}',
  },
  {
    method: "gettransaction",
    category: "Wallet",
    description: "Get transaction details by hash.",
    params: '["tx_hash_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"gettransaction","params":["deadbeef..."]}',
  },
  {
    method: "gettransactions",
    category: "Wallet",
    description: "Batch-fetch multiple transactions.",
    params: '["hash1","hash2",...]',
    example: '{"jsonrpc":"2.0","id":1,"method":"gettransactions","params":[["hash1","hash2"]]}',
  },
  {
    method: "sendtransaction",
    category: "Wallet",
    description: "Broadcast a signed transaction to the network.",
    params: '["to_address", amount_sat, fee_sat]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendtransaction","params":["ob1q...",1000000000,10000]}',
  },
  {
    method: "sendrawtransaction",
    category: "Wallet",
    description: "Broadcast a raw hex-encoded transaction.",
    params: '["raw_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendrawtransaction","params":["0200000001..."]}',
  },
  {
    method: "sendopreturn",
    category: "Wallet",
    description: "Send a transaction with OP_RETURN data (used for name registrations, memos).",
    params: '["data_string", fee_sat] or {"data":"...","fee":100}',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendopreturn","params":["ns:alice.omnibus:ob1q...",10000]}',
  },
  {
    method: "minersendtx",
    category: "Wallet",
    description: "Miner-signed transaction (used by mining pool).",
    params: '["from_addr","to_addr",amount_sat,fee_sat]',
    example: '{"jsonrpc":"2.0","id":1,"method":"minersendtx","params":["ob1q...","ob1q...",1000,100]}',
  },
  {
    method: "estimatefee",
    category: "Wallet",
    description: "Estimate fee for next block inclusion.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"estimatefee","params":[]}',
  },
  {
    method: "getnonce",
    category: "Wallet",
    description: "Get the next transaction nonce for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getnonce","params":["ob1q..."]}',
  },
  {
    method: "getrichlist",
    category: "Wallet",
    description: "Top N addresses by balance. Includes roles[] badges.",
    params: "[count: number]  (default 100)",
    example: '{"jsonrpc":"2.0","id":1,"method":"getrichlist","params":[50]}',
  },
  {
    method: "getdailyactivity",
    category: "Wallet",
    description: "Per-day TX breakdown for an address (useful for audit charts).",
    params: '["ob1q...", days?]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getdailyactivity","params":["ob1q...",30]}',
  },
  // ── Mempool / Network ────────────────────────────────────────────────────────
  {
    method: "getmempoolsize",
    category: "Network",
    description: "Number of pending transactions in the mempool.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmempoolsize","params":[]}',
  },
  {
    method: "getmempoolstats",
    category: "Network",
    description: "Mempool stats: size, bytes, fee histogram.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmempoolstats","params":[]}',
  },
  {
    method: "getmempoolinfo",
    category: "Network",
    description: "Alias for getmempoolstats. Also aliased as getrawmempool / getmempool.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmempoolinfo","params":[]}',
  },
  {
    method: "getpeers",
    category: "Network",
    description: "List connected P2P peers.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getpeers","params":[]}',
  },
  {
    method: "getpeerinfo",
    category: "Network",
    description: "Detailed peer info (latency, version, services).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getpeerinfo","params":[]}',
  },
  {
    method: "getnetworkinfo",
    category: "Network",
    description: "Network info: version, subversion, connections, local addresses.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getnetworkinfo","params":[]}',
  },
  {
    method: "getconnectioncount",
    category: "Network",
    description: "Number of active P2P connections.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getconnectioncount","params":[]}',
  },
  {
    method: "getsyncstatus",
    category: "Network",
    description: "IBD sync progress: headers/blocks synced vs chain tip.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getsyncstatus","params":[]}',
  },
  {
    method: "getnodelist",
    category: "Network",
    description: "Known nodes in the DHT routing table.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getnodelist","params":[]}',
  },
  // ── Mining ───────────────────────────────────────────────────────────────────
  {
    method: "getminerstats",
    category: "Mining",
    description: "Miner statistics: hashrate, blocks found, rewards.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getminerstats","params":[]}',
  },
  {
    method: "getminerinfo",
    category: "Mining",
    description: "Info about the node's own miner (address, hashrate, rewards).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getminerinfo","params":[]}',
  },
  {
    method: "getmininginfo",
    category: "Mining",
    description: "Mining info: difficulty, network hashrate, block reward.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getmininginfo","params":[]}',
  },
  {
    method: "getpoolstats",
    category: "Mining",
    description: "Mining pool stats: connected miners, total hashrate, last payout.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getpoolstats","params":[]}',
  },
  {
    method: "getslotleader",
    category: "Mining",
    description: "Current slot leader address for PoUW slot-based mining.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getslotleader","params":[]}',
  },
  {
    method: "getslotcalendar",
    category: "Mining",
    description: "Upcoming slot assignments for the next N blocks.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getslotcalendar","params":[]}',
  },
  {
    method: "getclockstatus",
    category: "Mining",
    description: "Node clock drift vs NTP and slot timing status.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getclockstatus","params":[]}',
  },
  {
    method: "getfuturepool",
    category: "Mining",
    description: "Transactions pre-committed for future blocks.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getfuturepool","params":[]}',
  },
  {
    method: "registerminer",
    category: "Mining",
    description: "Register a miner address with the network.",
    params: '["address","node_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"registerminer","params":["ob1q...","miner-1"]}',
  },
  {
    method: "omnibus_getminers",
    category: "Mining",
    description: "List all known miners registered on chain.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getminers","params":[]}',
  },
  {
    method: "omnibus_gettotalmined",
    category: "Mining",
    description: "Total OMNI mined across the entire network (explorer stat).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_gettotalmined","params":[]}',
  },
  // ── Staking & Validators ─────────────────────────────────────────────────────
  {
    method: "stake",
    category: "Staking",
    description: "Stake OMNI to become a validator candidate.",
    params: '["address", amount_sat, "privkey_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"stake","params":["ob1q...",10000000000,"aabbcc..."]}',
  },
  {
    method: "unstake",
    category: "Staking",
    description: "Unstake OMNI (subject to unbonding period).",
    params: '["address", amount_sat, "privkey_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"unstake","params":["ob1q...",10000000000,"aabbcc..."]}',
  },
  {
    method: "getstake",
    category: "Staking",
    description: "Current stake amount and status for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getstake","params":["ob1q..."]}',
  },
  {
    method: "getstakers",
    category: "Staking",
    description: "List of all stakers sorted by stake amount.",
    params: "[limit?]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getstakers","params":[20]}',
  },
  {
    method: "getvalidators",
    category: "Staking",
    description: "List of current active validators.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getvalidators","params":[]}',
  },
  {
    method: "getvalidatorsv2",
    category: "Staking",
    description: "Validators v2: includes soulbound tier, uptime, slash history.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getvalidatorsv2","params":[]}',
  },
  {
    method: "become_validator",
    category: "Staking",
    description: "Promote staker to active validator set.",
    params: '["address","pubkey_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"become_validator","params":["ob1q...","03..."]}',
  },
  {
    method: "validator_heartbeat",
    category: "Staking",
    description: "Keep-alive ping for active validators (prevents slashing).",
    params: '["validator_addr","sig_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"validator_heartbeat","params":["ob1q...","sig..."]}',
  },
  {
    method: "getstakinginfo",
    category: "Staking",
    description: "Staking parameters: min stake, unbonding days, epoch.",
    params: '["validator_addr"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getstakinginfo","params":["ob1q..."]}',
  },
  {
    method: "submitslashevidence",
    category: "Staking",
    description: "Submit double-sign evidence to slash a misbehaving validator.",
    params: '["validator_addr","double_sign","hash1","hash2",height,"reporter_addr"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"submitslashevidence","params":["ob1q...","double_sign","h1","h2",100,"ob1q..."]}',
  },
  {
    method: "getslashhistory",
    category: "Staking",
    description: "Slash events for a validator.",
    params: '["validator_addr"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getslashhistory","params":["ob1q..."]}',
  },
  {
    method: "getslashevents",
    category: "Staking",
    description: "All recent slash events on the network.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getslashevents","params":[]}',
  },
  // ── DNS / Names ──────────────────────────────────────────────────────────────
  {
    method: "registername",
    category: "Names",
    description: "Register a .omnibus / .arbitraje / .bank name on-chain.",
    params: '{"name":"alice.omnibus","address":"ob1q...","owner":"ob1q...","fee_sat":5000000000}',
    example: '{"jsonrpc":"2.0","id":1,"method":"registername","params":[{"name":"alice.omnibus","address":"ob1q...","owner":"ob1q...","fee_sat":5000000000}]}',
  },
  {
    method: "resolvename",
    category: "Names",
    description: "Resolve a name to an on-chain address.",
    params: '["alice.omnibus"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"resolvename","params":["alice.omnibus"]}',
  },
  {
    method: "ns_resolveforsend",
    category: "Names",
    description: "Resolve name and validate it can receive funds.",
    params: '["alice.omnibus"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_resolveforsend","params":["alice.omnibus"]}',
  },
  {
    method: "reverseresolvename",
    category: "Names",
    description: "Reverse lookup: address → name.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"reverseresolvename","params":["ob1q..."]}',
  },
  {
    method: "listnames",
    category: "Names",
    description: "List all registered names, optionally filtered by owner.",
    params: '[{"owner":"ob1q..."}]  (optional)',
    example: '{"jsonrpc":"2.0","id":1,"method":"listnames","params":[{"owner":"ob1q..."}]}',
  },
  {
    method: "renewname",
    category: "Names",
    description: "Renew a name registration before expiry.",
    params: '["alice.omnibus","owner_addr","sig"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"renewname","params":["alice.omnibus","ob1q...","sig"]}',
  },
  {
    method: "transfername",
    category: "Names",
    description: "Transfer a name to a new owner address.",
    params: '["alice.omnibus","new_owner","sig"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"transfername","params":["alice.omnibus","ob1q...","sig"]}',
  },
  {
    method: "updatename",
    category: "Names",
    description: "Update the resolved address for a name.",
    params: '["alice.omnibus","new_addr","sig"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"updatename","params":["alice.omnibus","ob1q...","sig"]}',
  },
  {
    method: "getensfee",
    category: "Names",
    description: "Get registration fee for a name (varies by TLD and length).",
    params: '["alice.omnibus"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getensfee","params":["alice.omnibus"]}',
  },
  {
    method: "ns_listTlds",
    category: "Names",
    description: "List all supported TLDs (.omnibus, .arbitraje, .bank, etc.).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_listTlds","params":[]}',
  },
  {
    method: "ns_stats",
    category: "Names",
    description: "Registry stats: total names, registrations today, by TLD.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_stats","params":[]}',
  },
  {
    method: "ns_expiringSoon",
    category: "Names",
    description: "Names expiring in the next N days.",
    params: "[days: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"ns_expiringSoon","params":[30]}',
  },
  {
    method: "getnamesbycategory",
    category: "Names",
    description: "Names filtered by category tag.",
    params: '["category_slug"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getnamesbycategory","params":["defi"]}',
  },
  // ── Exchange / DEX ────────────────────────────────────────────────────────────
  {
    method: "exchange_listPairs",
    category: "Exchange",
    description: "List all trading pairs with pair_id. IDs are fixed forever.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_listPairs","params":[]}',
  },
  {
    method: "exchange_pairInfo",
    category: "Exchange",
    description: "Info for a pair: maker_chains[], taker_chains[], 24h stats.",
    params: "[pair_id: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_pairInfo","params":[0]}',
  },
  {
    method: "exchange_getOrderbook",
    category: "Exchange",
    description: "Current orderbook (bids/asks) for a pair.",
    params: "[pair_id: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getOrderbook","params":[3]}',
  },
  {
    method: "exchange_placeOrder",
    category: "Exchange",
    description: "Place a limit order on the DEX orderbook.",
    params: '{"pair_id":0,"side":"buy","price":100,"amount":1000000000,"owner":"ob1q...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_placeOrder","params":[{"pair_id":0,"side":"buy","price":100,"amount":1000000000,"owner":"ob1q..."}]}',
  },
  {
    method: "exchange_cancelOrder",
    category: "Exchange",
    description: "Cancel an open order.",
    params: '{"order_id":"uuid","owner":"ob1q...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_cancelOrder","params":[{"order_id":"...","owner":"ob1q..."}]}',
  },
  {
    method: "exchange_getUserOrders",
    category: "Exchange",
    description: "All open orders for a given user address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getUserOrders","params":["ob1q..."]}',
  },
  {
    method: "exchange_getTrades",
    category: "Exchange",
    description: "Recent trades for a pair.",
    params: "[pair_id: number, limit?: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getTrades","params":[0,50]}',
  },
  {
    method: "exchange_getStats",
    category: "Exchange",
    description: "24h stats for a pair: volume, high, low, last price.",
    params: "[pair_id: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getStats","params":[0]}',
  },
  {
    method: "exchange_depositReal",
    category: "Exchange",
    description: "Initiate a real cross-chain deposit into DEX escrow via HTLC.",
    params: '{"pair_id":0,"amount":1000,"chain":"omni","address":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_depositReal","params":[{"pair_id":0,"amount":1000,"chain":"omni","address":"ob1q..."}]}',
  },
  {
    method: "exchange_getEscrowAddress",
    category: "Exchange",
    description: "Returns the DEX escrow address (never deposit manually; use depositReal).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getEscrowAddress","params":[]}',
  },
  {
    method: "exchange_getBalance",
    category: "Exchange",
    description: "Exchange balance for an address (in-DEX custody).",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_getBalance","params":["ob1q..."]}',
  },
  // ── Grid Trading ─────────────────────────────────────────────────────────────
  {
    method: "grid_create",
    category: "Grid",
    description: "Create an automated market-making grid. Chain generates N buy + N sell orders.",
    params: '{"pair_id":0,"price_low":95,"price_high":105,"levels":5,"total_base":10,"total_quote":1000,"owner":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_create","params":[{"pair_id":0,"price_low":95,"price_high":105,"levels":5,"total_base":10,"total_quote":1000,"owner":"ob1q..."}]}',
  },
  {
    method: "grid_list",
    category: "Grid",
    description: "List active grids, optionally filtered by owner.",
    params: '{"owner":"ob1q..."}  (optional)',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_list","params":[{"owner":"ob1q..."}]}',
  },
  {
    method: "grid_status",
    category: "Grid",
    description: "Grid details: fills, P&L, currently active orders.",
    params: '{"grid_id":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_status","params":[{"grid_id":"..."}]}',
  },
  {
    method: "grid_cancel",
    category: "Grid",
    description: "Stop a grid. Funds stay in user wallet (never locked until fill).",
    params: '{"grid_id":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"grid_cancel","params":[{"grid_id":"..."}]}',
  },
  // ── HTLC ────────────────────────────────────────────────────────────────────
  {
    method: "htlc_init",
    category: "HTLC",
    description: "Create a Hash Time-Locked Contract for atomic cross-chain swap. Preimage generated server-side.",
    params: '{"pair_id":0,"maker":"ob1q...","taker":"ob1q...","amount":1000,"timelock_blocks":144}',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_init","params":[{"pair_id":0,"maker":"ob1q...","taker":"0x...","amount":1000}]}',
  },
  {
    method: "htlc_claim",
    category: "HTLC",
    description: "Claim HTLC funds by revealing the preimage.",
    params: '{"htlc_id":"...","preimage_hex":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_claim","params":[{"htlc_id":"...","preimage_hex":"..."}]}',
  },
  {
    method: "htlc_refund",
    category: "HTLC",
    description: "Refund expired HTLC back to maker.",
    params: '{"htlc_id":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_refund","params":[{"htlc_id":"..."}]}',
  },
  {
    method: "htlc_get",
    category: "HTLC",
    description: "Get HTLC status by ID.",
    params: '["htlc_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_get","params":["htlc_id_here"]}',
  },
  {
    method: "htlc_listByAddress",
    category: "HTLC",
    description: "List HTLCs involving an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_listByAddress","params":["ob1q..."]}',
  },
  {
    method: "htlc_listPending",
    category: "HTLC",
    description: "All pending (unclaimed/unrefunded) HTLCs.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"htlc_listPending","params":[]}',
  },
  // ── Identity / Profile ────────────────────────────────────────────────────────
  {
    method: "getdid",
    category: "Identity",
    description: "Get the W3C-compatible DID document for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getdid","params":["ob1q..."]}',
  },
  {
    method: "getobm",
    category: "Identity",
    description: "Get OmniBus Binary Map (OBM) — 8-bit badge vector for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getobm","params":["ob1q..."]}',
  },
  {
    method: "getfacets",
    category: "Identity",
    description: "Get the 4 identity facets (Social/Professional/Cultural/Economic) with Merkle proofs.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getfacets","params":["ob1q..."]}',
  },
  {
    method: "profile_init",
    category: "Identity",
    description: "Initialize profile for an address (first-time setup).",
    params: '{"address":"ob1q...","display_name":"Alice"}',
    example: '{"jsonrpc":"2.0","id":1,"method":"profile_init","params":[{"address":"ob1q...","display_name":"Alice"}]}',
  },
  {
    method: "profile_get",
    category: "Identity",
    description: "Get full profile: name, facets, OBM, reputation cups.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"profile_get","params":["ob1q..."]}',
  },
  {
    method: "profile_update",
    category: "Identity",
    description: "Update profile fields.",
    params: '{"address":"ob1q...","display_name":"Bob","bio":"...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"profile_update","params":[{"address":"ob1q...","display_name":"Bob"}]}',
  },
  {
    method: "mica_attest",
    category: "Identity",
    description: "Attach MiCA (EU crypto regulation) attestation to an address.",
    params: '{"address":"ob1q...","mica_type":"EMT","issuer":"ob1q...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"mica_attest","params":[{"address":"ob1q...","mica_type":"EMT"}]}',
  },
  {
    method: "mica_disclose",
    category: "Identity",
    description: "Selective disclosure of MiCA compliance fields.",
    params: '{"address":"ob1q...","fields":["mica_type","issuer"]}',
    example: '{"jsonrpc":"2.0","id":1,"method":"mica_disclose","params":[{"address":"ob1q...","fields":["mica_type"]}]}',
  },
  {
    method: "getreputation",
    category: "Identity",
    description: "4-cup reputation (LOVE/FOOD/RENT/VACATION) and total score for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getreputation","params":["ob1q..."]}',
  },
  {
    method: "getreputationtop",
    category: "Identity",
    description: "Top N addresses by reputation score.",
    params: "[limit: number]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getreputationtop","params":[50]}',
  },
  // ── Agents ────────────────────────────────────────────────────────────────────
  {
    method: "agent_list",
    category: "Agents",
    description: "List all registered autonomous trading agents.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_list","params":[]}',
  },
  {
    method: "agent_register",
    category: "Agents",
    description: "Register a new AI agent on-chain.",
    params: '{"name":"MyBot","owner":"ob1q...","strategy":"grid","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_register","params":[{"name":"MyBot","owner":"ob1q..."}]}',
  },
  {
    method: "agent_unregister",
    category: "Agents",
    description: "Remove an agent from the registry.",
    params: '{"agent_id":"...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_unregister","params":[{"agent_id":"..."}]}',
  },
  {
    method: "agent_status",
    category: "Agents",
    description: "Current status and last decisions of an agent.",
    params: '["agent_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_status","params":["agent_id_here"]}',
  },
  {
    method: "agent_pending_decisions",
    category: "Agents",
    description: "Pending decisions queued for an agent.",
    params: '["agent_id"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_pending_decisions","params":["agent_id"]}',
  },
  // ── Bridge ────────────────────────────────────────────────────────────────────
  {
    method: "getbridgestatus",
    category: "Bridge",
    description: "Status of cross-chain bridge (locked amounts, pending transfers).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getbridgestatus","params":[]}',
  },
  {
    method: "bridge_lock",
    category: "Bridge",
    description: "Lock OMNI on OmniBus chain to bridge to EVM chain.",
    params: '{"amount":1000000000,"to_chain":"base","to_address":"0x...","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"bridge_lock","params":[{"amount":1000000000,"to_chain":"base","to_address":"0x..."}]}',
  },
  {
    method: "omnibus_getbridgestatus",
    category: "Bridge",
    description: "Extended bridge status including fee limits and supported chains.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getbridgestatus","params":[]}',
  },
  {
    method: "omnibus_bridge_limits",
    category: "Bridge",
    description: "Min/max bridge amounts and cooldown per chain.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_bridge_limits","params":[]}',
  },
  // ── Oracle / Prices ────────────────────────────────────────────────────────────
  {
    method: "omnibus_getoracleprices",
    category: "Oracle",
    description: "All price feeds from the distributed oracle (Chainlink/Pyth/CoinGecko).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getoracleprices","params":[]}',
  },
  {
    method: "omnibus_getallprices",
    category: "Oracle",
    description: "All prices in a single call including cross-rates.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getallprices","params":[]}',
  },
  {
    method: "omnibus_getarbitrage",
    category: "Oracle",
    description: "Current arbitrage opportunities across oracle feeds.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getarbitrage","params":[]}',
  },
  {
    method: "omnibus_getexchangefeed",
    category: "Oracle",
    description: "Real-time feed from connected external exchanges.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getexchangefeed","params":[]}',
  },
  // ── PQ / Post-Quantum ─────────────────────────────────────────────────────────
  {
    method: "pq_listSchemes",
    category: "Post-Quantum",
    description: "List supported PQ signature schemes (ML-DSA-87, Falcon-512, SLH-DSA, ML-KEM-768).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_listSchemes","params":[]}',
  },
  {
    method: "pq_balance",
    category: "Post-Quantum",
    description: "Balance on a PQ soulbound address.",
    params: '["obk1_..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_balance","params":["obk1_..."]}',
  },
  {
    method: "pq_attestation",
    category: "Post-Quantum",
    description: "Get pq_attest record (7 simultaneous signatures binding cross-chain identity).",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_attestation","params":["ob1q..."]}',
  },
  // ── Faucet ────────────────────────────────────────────────────────────────────
  {
    method: "claimfaucet",
    category: "Faucet",
    description: "Claim 0.1 OMNI from the testnet faucet. One claim per address per cooldown period.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"claimfaucet","params":["ob1q..."]}',
  },
  {
    method: "getfaucetstatus",
    category: "Faucet",
    description: "Faucet wallet balance, grant amount, and recent claims.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getfaucetstatus","params":[]}',
  },
  // ── Governance ───────────────────────────────────────────────────────────────
  {
    method: "gov_propose",
    category: "Governance",
    description: "Submit an on-chain governance proposal.",
    params: '{"title":"...","description":"...","type":"parameter_change","proposer":"ob1q..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"gov_propose","params":[{"title":"Increase block reward","type":"parameter_change","proposer":"ob1q..."}]}',
  },
  {
    method: "gov_vote",
    category: "Governance",
    description: "Vote on a governance proposal.",
    params: '{"proposal_id":1,"voter":"ob1q...","option":"yes","sig":"..."}',
    example: '{"jsonrpc":"2.0","id":1,"method":"gov_vote","params":[{"proposal_id":1,"voter":"ob1q...","option":"yes"}]}',
  },
  {
    method: "getproposals",
    category: "Governance",
    description: "List all governance proposals (active/passed/rejected).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getproposals","params":[]}',
  },
  // ── Multisig ──────────────────────────────────────────────────────────────────
  {
    method: "createmultisig",
    category: "Advanced",
    description: "Create M-of-N multisig address.",
    params: "[M, [\"pubkey1_hex\", \"pubkey2_hex\", ...]]",
    example: '{"jsonrpc":"2.0","id":1,"method":"createmultisig","params":[2,["03abc...","03def..."]]}',
  },
  {
    method: "sendmultisig",
    category: "Advanced",
    description: "Send from multisig address with M signatures.",
    params: '["multisig_addr","to_addr",amount,fee,"privkey1","privkey2",...]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendmultisig","params":["ob1q...","ob1q...",1000,100,"key1","key2"]}',
  },
  // ── EVM Compatibility ─────────────────────────────────────────────────────────
  {
    method: "eth_call",
    category: "EVM",
    description: "EVM eth_call (read-only contract call on OmniBus EVM layer).",
    params: '[{"to":"0x...","data":"0x..."},"latest"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"to":"0x...","data":"0x..."},"latest"]}',
  },
  {
    method: "eth_chainId",
    category: "EVM",
    description: "OmniBus EVM chain ID (for MetaMask-compatible tooling).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}',
  },
  {
    method: "net_version",
    category: "EVM",
    description: "Network version string (EVM compatibility).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"net_version","params":[]}',
  },
  // ── Social Graph ────────────────────────────────────────────────────────────
  {
    method: "follow",
    category: "Social",
    description: "Follow another address on-chain (signed by follower).",
    params: '[{"from":"ob1q...","to":"ob1q...","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"follow","params":[{"from":"ob1q...","to":"ob1q...","signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "unfollow",
    category: "Social",
    description: "Unfollow an address on-chain.",
    params: '[{"from":"ob1q...","to":"ob1q...","signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"unfollow","params":[{"from":"ob1q...","to":"ob1q...","signature":"hex","public_key":"hex","nonce":2}]}',
  },
  {
    method: "getfollowers",
    category: "Social",
    description: "List addresses that follow the given address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getfollowers","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "getfollowing",
    category: "Social",
    description: "List addresses that the given address follows.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getfollowing","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "applylabel",
    category: "Social",
    description: "Attach a text label to an address (e.g. 'Exchange hot wallet').",
    params: '["ob1q...","MyLabel"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"applylabel","params":["ob1q...","Treasury"]}',
  },
  {
    method: "getlabels",
    category: "Social",
    description: "Fetch all labels for an address.",
    params: '["ob1q..."]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getlabels","params":["ob1q..."]}',
  },
  {
    method: "removelabel",
    category: "Social",
    description: "Remove a label from an address.",
    params: '["ob1q...","MyLabel"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"removelabel","params":["ob1q...","Treasury"]}',
  },
  // ── Bridge ──────────────────────────────────────────────────────────────────
  {
    method: "bridge_lock",
    category: "Bridge",
    description: "Lock OMNI in the bridge vault for relay to an external chain address.",
    params: '[{"amount_sat":1000000000,"destination_chain":"ethereum","destination_addr":"0x..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"bridge_lock","params":[{"amount_sat":1000000000,"destination_chain":"ethereum","destination_addr":"0x..."}]}',
  },
  {
    method: "bridge_unlock_request",
    category: "Bridge",
    description: "Submit a multi-sig unlock request to release bridge-locked funds.",
    params: '[{"signer_addr":"ob1q...","recipient_addr":"ob1q...","amount_sat":1000000000,"nonce":"hex64"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"bridge_unlock_request","params":[{"signer_addr":"ob1q...","recipient_addr":"ob1q...","amount_sat":1000000000,"nonce":"hex64"}]}',
  },
  {
    method: "bridge_fraud_challenge",
    category: "Bridge",
    description: "Void a pending unlock by submitting fraud proof before the challenge window closes.",
    params: '[{"nonce":"hex64","fraud_proof":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"bridge_fraud_challenge","params":[{"nonce":"hex64"}]}',
  },
  {
    method: "bridge_settle",
    category: "Bridge",
    description: "Execute a pending unlock after the challenge window has passed.",
    params: '[{"nonce":"hex64"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"bridge_settle","params":[{"nonce":"hex64"}]}',
  },
  // ── Payment Channels ────────────────────────────────────────────────────────
  {
    method: "openchannel",
    category: "Channel",
    description: "Open a bidirectional payment channel between two parties.",
    params: '["party_a_hex","party_b_hex",amount_a,amount_b]',
    example: '{"jsonrpc":"2.0","id":1,"method":"openchannel","params":["03abc...","03def...",1000000000,1000000000]}',
  },
  {
    method: "channelpay",
    category: "Channel",
    description: "Make an off-chain payment within a channel.",
    params: '["channel_id_hex","a_to_b",amount_sat,"sig_a_hex","sig_b_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"channelpay","params":["hex64",true,500000000,"siga","sigb"]}',
  },
  {
    method: "closechannel",
    category: "Channel",
    description: "Cooperatively close a payment channel and settle on-chain.",
    params: '["channel_id_hex"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"closechannel","params":["hex64"]}',
  },
  {
    method: "getchannels",
    category: "Channel",
    description: "List all payment channels (optionally filtered by address).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getchannels","params":[]}',
  },
  // ── Vault / Timelock ────────────────────────────────────────────────────────
  {
    method: "timelock_create",
    category: "Vault",
    description: "Create a CLTV timelock vault — locks OMNI until a specific block height.",
    params: '[{"owner":"ob1q...","dest":"ob1q...","amount_sat":1000000000,"unlock_block":100000}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"timelock_create","params":[{"owner":"ob1q...","dest":"ob1q...","amount_sat":1000000000,"unlock_block":100000}]}',
  },
  {
    method: "timelock_list",
    category: "Vault",
    description: "List timelock vaults owned by an address.",
    params: '[{"owner":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"timelock_list","params":[{"owner":"ob1q..."}]}',
  },
  {
    method: "timelock_spend",
    category: "Vault",
    description: "Spend a timelock vault after the unlock block is reached.",
    params: '[{"vault_id":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"timelock_spend","params":[{"vault_id":"hex32"}]}',
  },
  {
    method: "timelock_status",
    category: "Vault",
    description: "Get live status of a timelock vault including blocks remaining.",
    params: '[{"vault_id":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"timelock_status","params":[{"vault_id":"hex32"}]}',
  },
  // ── Vault / Covenant ────────────────────────────────────────────────────────
  {
    method: "covenant_create",
    category: "Vault",
    description: "Create a covenant — restricts an address to only send to whitelisted destinations.",
    params: '[{"address":"ob1q...","whitelist":["ob1q..."],"label":"Treasury"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"covenant_create","params":[{"address":"ob1q...","whitelist":["ob1q..."],"label":"Cold"}]}',
  },
  {
    method: "covenant_list",
    category: "Vault",
    description: "List all active covenants.",
    params: "[{}]",
    example: '{"jsonrpc":"2.0","id":1,"method":"covenant_list","params":[{}]}',
  },
  {
    method: "covenant_get",
    category: "Vault",
    description: "Get live covenant data for an address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"covenant_get","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "covenant_remove",
    category: "Vault",
    description: "Remove a covenant restriction from an address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"covenant_remove","params":[{"address":"ob1q..."}]}',
  },
  // ── Vault / Treasury ────────────────────────────────────────────────────────
  {
    method: "treasury_create",
    category: "Vault",
    description: "Create a treasury that auto-distributes OMNI to destinations by percentage.",
    params: '[{"address":"ob1q...","destinations":[{"address":"ob1q...","percent":100,"label":"Dev"}],"trigger_sat":0,"label":"Protocol Fees"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"treasury_create","params":[{"address":"ob1q...","destinations":[{"address":"ob1q...","percent":100,"label":"Dev"}],"trigger_sat":0}]}',
  },
  {
    method: "treasury_list",
    category: "Vault",
    description: "List all treasuries.",
    params: "[{}]",
    example: '{"jsonrpc":"2.0","id":1,"method":"treasury_list","params":[{}]}',
  },
  {
    method: "treasury_distribute",
    category: "Vault",
    description: "Manually trigger treasury distribution.",
    params: '[{"treasury_id":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"treasury_distribute","params":[{"treasury_id":"hex32"}]}',
  },
  {
    method: "treasury_status",
    category: "Vault",
    description: "Get live treasury status: balance, pending distribute, total distributed.",
    params: '[{"treasury_id":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"treasury_status","params":[{"treasury_id":"hex32"}]}',
  },
  // ── Vault / Cold Wallet ─────────────────────────────────────────────────────
  {
    method: "coldwallet_add",
    category: "Vault",
    description: "Add a watch-only cold wallet address.",
    params: '[{"address":"ob1q...","label":"Cold Storage"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"coldwallet_add","params":[{"address":"ob1q...","label":"Cold"}]}',
  },
  {
    method: "coldwallet_list",
    category: "Vault",
    description: "List all tracked cold wallet addresses.",
    params: "[{}]",
    example: '{"jsonrpc":"2.0","id":1,"method":"coldwallet_list","params":[{}]}',
  },
  {
    method: "coldwallet_remove",
    category: "Vault",
    description: "Remove a cold wallet address from tracking.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"coldwallet_remove","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "coldwallet_history",
    category: "Vault",
    description: "Get transaction history for a cold wallet address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"coldwallet_history","params":[{"address":"ob1q..."}]}',
  },
  // ── POAP ────────────────────────────────────────────────────────────────────
  {
    method: "getpoaps",
    category: "POAP",
    description: "List all POAP badges claimed by an address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getpoaps","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "getpoapevent",
    category: "POAP",
    description: "Get details of a POAP event by event_id.",
    params: '[{"event_id":"my-event-2026"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getpoapevent","params":[{"event_id":"event123"}]}',
  },
  {
    method: "poap_createevent",
    category: "POAP",
    description: "Create a new POAP event (signed by organizer).",
    params: '[{"from":"ob1q...","event_id":"my-event","name":"OmniBus Hackathon","max_claims":500,"note":"","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"poap_createevent","params":[{"from":"ob1q...","event_id":"event123","name":"Test","max_claims":100,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "poap_claim",
    category: "POAP",
    description: "Claim a POAP badge for an event.",
    params: '[{"from":"ob1q...","event_id":"my-event","signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"poap_claim","params":[{"from":"ob1q...","event_id":"event123","signature":"hex","public_key":"hex","nonce":2}]}',
  },
  {
    method: "poap_close",
    category: "POAP",
    description: "Close a POAP event — no more claims accepted (signed by organizer).",
    params: '[{"from":"ob1q...","event_id":"my-event","signature":"hex","public_key":"hex","nonce":3}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"poap_close","params":[{"from":"ob1q...","event_id":"event123","signature":"hex","public_key":"hex","nonce":3}]}',
  },
  // ── Subscriptions ───────────────────────────────────────────────────────────
  {
    method: "sub_create",
    category: "Subscription",
    description: "Create a recurring on-chain payment subscription.",
    params: '[{"from":"ob1q...","to":"ob1q...","amount_sat":100000,"interval":86400,"max_payments":0,"note":"Monthly","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sub_create","params":[{"from":"ob1q...","to":"ob1q...","amount_sat":100000,"interval":86400,"max_payments":12,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "sub_cancel",
    category: "Subscription",
    description: "Cancel an active subscription.",
    params: '[{"from":"ob1q...","sub_id":42,"signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sub_cancel","params":[{"from":"ob1q...","sub_id":42,"signature":"hex","public_key":"hex","nonce":2}]}',
  },
  {
    method: "getsubscriptions",
    category: "Subscription",
    description: "List subscriptions emitted or received by an address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getsubscriptions","params":[{"address":"ob1q..."}]}',
  },
  // ── Atomic Swap ─────────────────────────────────────────────────────────────
  {
    method: "swap_open",
    category: "Swap",
    description: "Open an atomic cross-chain swap (HTLC-based).",
    params: '[{"maker":"ob1q...","asset_in":"OMNI","amount_in":1000000000,"asset_out":"ETH","timelock_blocks":144,"signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"swap_open","params":[{"maker":"ob1q...","asset_in":"OMNI","amount_in":1000000000,"asset_out":"ETH","timelock_blocks":144,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "swap_status",
    category: "Swap",
    description: "Get status of a swap by ID.",
    params: '[{"swap_id":"hex64"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"swap_status","params":[{"swap_id":"hex64"}]}',
  },
  {
    method: "swap_timeout",
    category: "Swap",
    description: "Refund a swap after the timelock has expired.",
    params: '[{"swap_id":"hex64"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"swap_timeout","params":[{"swap_id":"hex64"}]}',
  },
  // ── Notarize ────────────────────────────────────────────────────────────────
  {
    method: "notarizedoc",
    category: "Notarize",
    description: "Notarize a document hash on-chain via OP_RETURN.",
    params: '[{"from":"ob1q...","doc_hash":"sha256hex","label":"contract","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"notarizedoc","params":[{"from":"ob1q...","doc_hash":"sha256hex","label":"doc","signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "getnotarizations",
    category: "Notarize",
    description: "List all notarizations by an address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getnotarizations","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "verifynotarize",
    category: "Notarize",
    description: "Verify a document hash against on-chain notarization record.",
    params: '[{"doc_hash":"sha256hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"verifynotarize","params":[{"doc_hash":"sha256hex"}]}',
  },
  {
    method: "revokenotarize",
    category: "Notarize",
    description: "Revoke a notarization (signed by original notarizer).",
    params: '[{"from":"ob1q...","doc_hash":"sha256hex","signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"revokenotarize","params":[{"from":"ob1q...","doc_hash":"sha256hex","signature":"hex","public_key":"hex","nonce":2}]}',
  },
  // ── Escrow ──────────────────────────────────────────────────────────────────
  {
    method: "escrow_create",
    category: "Escrow",
    description: "Create a 2-of-3 escrow: buyer, seller, arbiter.",
    params: '[{"from":"ob1q...","seller":"ob1q...","arbiter":"ob1q...","amount_sat":1000000000,"signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"escrow_create","params":[{"from":"ob1q...","seller":"ob1q...","arbiter":"ob1q...","amount_sat":1000000000,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "escrow_release",
    category: "Escrow",
    description: "Release escrow funds to seller (signed by buyer or arbiter).",
    params: '[{"from":"ob1q...","escrow_id":"hex","signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"escrow_release","params":[{"from":"ob1q...","escrow_id":"hex","signature":"hex","public_key":"hex","nonce":2}]}',
  },
  {
    method: "escrow_refund",
    category: "Escrow",
    description: "Refund escrow to buyer (signed by seller or arbiter).",
    params: '[{"from":"ob1q...","escrow_id":"hex","signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"escrow_refund","params":[{"from":"ob1q...","escrow_id":"hex","signature":"hex","public_key":"hex","nonce":2}]}',
  },
  {
    method: "escrow_dispute",
    category: "Escrow",
    description: "Raise an escrow dispute (either party — invites arbiter decision).",
    params: '[{"from":"ob1q...","escrow_id":"hex","reason":"goods not received","signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"escrow_dispute","params":[{"from":"ob1q...","escrow_id":"hex","reason":"dispute","signature":"hex","public_key":"hex","nonce":2}]}',
  },
  {
    method: "getescrow",
    category: "Escrow",
    description: "Get escrow details by ID.",
    params: '[{"escrow_id":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getescrow","params":[{"escrow_id":"hex"}]}',
  },
  {
    method: "getescrows",
    category: "Escrow",
    description: "List escrows involving an address (buyer/seller/arbiter).",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getescrows","params":[{"address":"ob1q..."}]}',
  },
  // ── Identity extended ───────────────────────────────────────────────────────
  {
    method: "getidentity",
    category: "Identity",
    description: "Get full identity snapshot for an address (DID + OBM + all facets).",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getidentity","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "getpqidentity",
    category: "Identity",
    description: "Get PQ identity binding for an address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getpqidentity","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "identity_get",
    category: "Identity",
    description: "Get identity record by address.",
    params: '[{"address":"ob1q..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"identity_get","params":[{"address":"ob1q..."}]}',
  },
  {
    method: "identity_set",
    category: "Identity",
    description: "Set/update identity metadata (signed by owner).",
    params: '[{"address":"ob1q...","display_name":"Alex","bio":"OmniBus founder","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"identity_set","params":[{"address":"ob1q...","display_name":"Alex","signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "identity_search",
    category: "Identity",
    description: "Search identities by display name or keyword.",
    params: '[{"query":"Alex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"identity_search","params":[{"query":"Alex"}]}',
  },
  {
    method: "sendpqattest",
    category: "Identity",
    description: "Send a PQ attestation linking OMNI + 4 PQ + BTC + ETH keys to one identity.",
    params: '[{"address":"ob1q...","attestation_data":{...},"signatures":{...}}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"sendpqattest","params":[{"address":"ob1q..."}]}',
  },
  // ── Post-Quantum extended ───────────────────────────────────────────────────
  {
    method: "pq_send",
    category: "Post-Quantum",
    description: "Send a transaction signed with a post-quantum key (ML-DSA/Falcon/SLH-DSA).",
    params: '[{"from":"obk1_...","to":"ob1q...","amount_sat":100000,"fee_sat":1000,"pq_signature":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_send","params":[{"from":"obk1_...","to":"ob1q...","amount_sat":100000,"fee_sat":1000,"pq_signature":"hex","nonce":1}]}',
  },
  {
    method: "pq_verify_test",
    category: "Post-Quantum",
    description: "Test PQ signature verification (dev tool).",
    params: '[{"algorithm":"ml-dsa","public_key":"hex","message":"hex","signature":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"pq_verify_test","params":[{"algorithm":"ml-dsa","public_key":"hex","message":"68656c6c6f","signature":"hex"}]}',
  },
  {
    method: "setpqaddress",
    category: "Post-Quantum",
    description: "Register a PQ address as belonging to an OMNI address.",
    params: '[{"omni_address":"ob1q...","pq_address":"obk1_...","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"setpqaddress","params":[{"omni_address":"ob1q...","pq_address":"obk1_...","signature":"hex","public_key":"hex","nonce":1}]}',
  },
  // ── Names extended ──────────────────────────────────────────────────────────
  {
    method: "setcategory",
    category: "Names",
    description: "Set the category of a registered name (personal/bank/gov/trading/etc.).",
    params: '[{"name":"alice","tld":"omnibus","category":"personal","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"setcategory","params":[{"name":"alice","tld":"omnibus","category":"trading","signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "setpreferredslot",
    category: "Names",
    description: "Set preferred wallet slot for a name (0=OMNI, 1-4=PQ algorithms).",
    params: '[{"name":"alice","tld":"omnibus","slot":0,"signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"setpreferredslot","params":[{"name":"alice","tld":"omnibus","slot":0,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  // ── Oracle extended ─────────────────────────────────────────────────────────
  {
    method: "omnibus_getblockprices",
    category: "Oracle",
    description: "Get oracle price snapshots for a specific block height.",
    params: '[1234]',
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getblockprices","params":[1234]}',
  },
  {
    method: "omnibus_getpricerange",
    category: "Oracle",
    description: "Get oracle price history for a block range.",
    params: '[1000,1200,"BTC/USD"]',
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getpricerange","params":[1000,1200,"BTC/USD"]}',
  },
  {
    method: "omnibus_getfxrate",
    category: "Oracle",
    description: "Get current USD/EUR exchange rate from oracle.",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getfxrate","params":[]}',
  },
  {
    method: "omnibus_getoraclepolicy",
    category: "Oracle",
    description: "Get oracle update policy (sources, thresholds, update interval).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getoraclepolicy","params":[]}',
  },
  {
    method: "omnibus_setoraclepolicy",
    category: "Oracle",
    description: "Update oracle policy (admin only).",
    params: '[{"update_interval_blocks":6,"deviation_threshold_pct":5}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_setoraclepolicy","params":[{"update_interval_blocks":6}]}',
  },
  {
    method: "omnibus_getorderbook",
    category: "Oracle",
    description: "Get DEX orderbook snapshot for a pair from the oracle aggregator.",
    params: '[{"pair":"OMNI/USDC"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"omnibus_getorderbook","params":[{"pair":"OMNI/USDC"}]}',
  },
  // ── Exchange extended ───────────────────────────────────────────────────────
  {
    method: "exchange_login",
    category: "Exchange",
    description: "Authenticate with exchange API key and secret. Returns a session token.",
    params: '[{"exchange":"lcx","api_key":"...","api_secret":"..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_login","params":[{"exchange":"lcx","api_key":"...","api_secret":"..."}]}',
  },
  {
    method: "place_order",
    category: "Exchange",
    description: "Place a spot order on an external exchange via the node proxy.",
    params: '[{"exchange":"lcx","symbol":"LCX/USDC","side":"buy","type":"limit","price":0.02,"amount":100}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"place_order","params":[{"exchange":"lcx","symbol":"LCX/USDC","side":"buy","type":"limit","price":0.02,"amount":100}]}',
  },
  {
    method: "cancel_order",
    category: "Exchange",
    description: "Cancel an open order on an external exchange.",
    params: '[{"exchange":"lcx","order_id":"ABC123","symbol":"LCX/USDC"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"cancel_order","params":[{"exchange":"lcx","order_id":"ABC123","symbol":"LCX/USDC"}]}',
  },
  {
    method: "exchange_deposit",
    category: "Exchange",
    description: "Get deposit address for an exchange.",
    params: '[{"exchange":"lcx","currency":"USDC"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_deposit","params":[{"exchange":"lcx","currency":"USDC"}]}',
  },
  {
    method: "exchange_withdraw",
    category: "Exchange",
    description: "Initiate a withdrawal from an exchange.",
    params: '[{"exchange":"lcx","currency":"USDC","amount":100,"address":"0x..."}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_withdraw","params":[{"exchange":"lcx","currency":"USDC","amount":100,"address":"0x..."}]}',
  },
  {
    method: "exchange_orderbook",
    category: "Exchange",
    description: "Get live orderbook from an external exchange via node proxy.",
    params: '[{"exchange":"lcx","symbol":"LCX/USDC"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_orderbook","params":[{"exchange":"lcx","symbol":"LCX/USDC"}]}',
  },
  {
    method: "exchange_trades",
    category: "Exchange",
    description: "Get recent trades from an external exchange via node proxy.",
    params: '[{"exchange":"lcx","symbol":"LCX/USDC"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"exchange_trades","params":[{"exchange":"lcx","symbol":"LCX/USDC"}]}',
  },
  // ── Agents extended ─────────────────────────────────────────────────────────
  {
    method: "getagents",
    category: "Agents",
    description: "List all registered agents with pagination.",
    params: '[{"limit":20,"offset":0}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getagents","params":[{"limit":20,"offset":0}]}',
  },
  {
    method: "getagent",
    category: "Agents",
    description: "Get a single agent by numeric ID.",
    params: '[{"agent_id":42}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getagent","params":[{"agent_id":42}]}',
  },
  {
    method: "agent_edit",
    category: "Agents",
    description: "Edit agent metadata (name, strategy, fee_bps).",
    params: '[{"from":"ob1q...","agent_id":42,"name":"NewName","signature":"hex","public_key":"hex","nonce":2}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_edit","params":[{"from":"ob1q...","agent_id":42,"name":"NewName","signature":"hex","public_key":"hex","nonce":2}]}',
  },
  {
    method: "agent_follow",
    category: "Agents",
    description: "Follow an agent to track its decisions.",
    params: '[{"from":"ob1q...","agent_id":42,"signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_follow","params":[{"from":"ob1q...","agent_id":42,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "agent_report_execution",
    category: "Agents",
    description: "Report the result of an agent decision execution.",
    params: '[{"from":"ob1q...","decision_id":"hex","success":true,"result_summary":"...","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"agent_report_execution","params":[{"from":"ob1q...","decision_id":"hex","success":true}]}',
  },
  // ── Intent ──────────────────────────────────────────────────────────────────
  {
    method: "intent_post",
    category: "Intent",
    description: "Post a swap intent to the DEX intent pool.",
    params: '[{"from":"ob1q...","give_asset":"OMNI","give_amount":1000000000,"want_asset":"ETH","want_min":100000000,"deadline_block":200000,"signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"intent_post","params":[{"from":"ob1q...","give_asset":"OMNI","give_amount":1000000000,"want_asset":"ETH","want_min":100000000,"deadline_block":200000,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "intent_fill_commit",
    category: "Intent",
    description: "Commit to fill an intent (filler locks funds).",
    params: '[{"from":"ob1q...","intent_id":"hex","give_amount":100000000,"signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"intent_fill_commit","params":[{"from":"ob1q...","intent_id":"hex","give_amount":100000000,"signature":"hex","public_key":"hex","nonce":1}]}',
  },
  {
    method: "intent_settle",
    category: "Intent",
    description: "Settle a committed intent fill (both sides confirm).",
    params: '[{"intent_id":"hex","fill_id":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"intent_settle","params":[{"intent_id":"hex","fill_id":"hex"}]}',
  },
  {
    method: "intent_timeout",
    category: "Intent",
    description: "Expire an intent or fill after deadline.",
    params: '[{"intent_id":"hex"}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"intent_timeout","params":[{"intent_id":"hex"}]}',
  },
  // ── KYC ─────────────────────────────────────────────────────────────────────
  {
    method: "kyc_attest",
    category: "Identity",
    description: "Submit a KYC/MiCA attestation for an address.",
    params: '[{"address":"ob1q...","level":"basic","jurisdiction":"EU","hash":"hex","signature":"hex","public_key":"hex","nonce":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"kyc_attest","params":[{"address":"ob1q...","level":"basic","jurisdiction":"EU","hash":"hex","signature":"hex","public_key":"hex","nonce":1}]}',
  },
  // ── Disclosure ──────────────────────────────────────────────────────────────
  {
    method: "disclose_cert",
    category: "Identity",
    description: "Selectively disclose a certificate leaf from the identity Merkle tree.",
    params: '[{"address":"ob1q...","leaf_index":3,"proof":["hex",...]}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"disclose_cert","params":[{"address":"ob1q...","leaf_index":3,"proof":[]}]}',
  },
  {
    method: "disclose_post",
    category: "Identity",
    description: "Disclose a social post proof from identity.",
    params: '[{"address":"ob1q...","leaf_index":6,"proof":["hex",...]}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"disclose_post","params":[{"address":"ob1q...","leaf_index":6,"proof":[]}]}',
  },
  {
    method: "disclose_work",
    category: "Identity",
    description: "Disclose a work history proof from identity.",
    params: '[{"address":"ob1q...","leaf_index":7,"proof":["hex",...]}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"disclose_work","params":[{"address":"ob1q...","leaf_index":7,"proof":[]}]}',
  },
  // ── Governance extended ──────────────────────────────────────────────────────
  {
    method: "gov_execute",
    category: "Governance",
    description: "Execute a passed governance proposal.",
    params: '[{"proposal_id":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"gov_execute","params":[{"proposal_id":1}]}',
  },
  {
    method: "getproposal",
    category: "Governance",
    description: "Get full details of a single governance proposal.",
    params: '[{"proposal_id":1}]',
    example: '{"jsonrpc":"2.0","id":1,"method":"getproposal","params":[{"proposal_id":1}]}',
  },
  // ── Mempool extended ────────────────────────────────────────────────────────
  {
    method: "getrawmempool",
    category: "Chain Info",
    description: "Get raw mempool contents (same as getmempoolinfo).",
    params: "[]",
    example: '{"jsonrpc":"2.0","id":1,"method":"getrawmempool","params":[]}',
  },
];

export const RPC_CATEGORIES = [
  "Chain Info", "Wallet", "Network", "Mining", "Staking",
  "Names", "Exchange", "Grid", "HTLC", "Intent", "Identity",
  "Agents", "Bridge", "Channel", "Oracle", "Post-Quantum",
  "Vault", "Social", "POAP", "Subscription", "Swap",
  "Notarize", "Escrow", "Faucet", "Governance", "Advanced", "EVM",
];
