#!/usr/bin/env python3
"""
OmniBus BlockChainCore — Node Deployment Tool
==============================================
Automates the full deployment of an OmniBus blockchain node:

  1. Verifies Zig compiler is installed and accessible
  2. Runs ``zig build`` to compile the node binary
  3. Copies omnibus-node binary to target directory
  4. Generates a default omnibus.toml configuration file
  5. Creates a launcher script (systemd .service on Linux, .bat on Windows)

Usage:
    python deploy-node.py --target-dir /opt/omnibus --mode seed
    python deploy-node.py --target-dir C:\\omnibus --mode miner --seed-host 10.0.0.1
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

# ── ANSI colours ─────────────────────────────────────────────────────
RESET   = "\033[0m"
BOLD    = "\033[1m"
DIM     = "\033[2m"
RED     = "\033[91m"
GREEN   = "\033[92m"
YELLOW  = "\033[93m"
CYAN    = "\033[96m"
MAGENTA = "\033[95m"

CHECKMARK = f"{GREEN}[OK]{RESET}"
CROSS     = f"{RED}[FAIL]{RESET}"
ARROW     = f"{CYAN}>>>{RESET}"


def step(msg: str):
    print(f"\n  {ARROW} {BOLD}{msg}{RESET}")


def ok(msg: str):
    print(f"    {CHECKMARK} {msg}")


def fail(msg: str):
    print(f"    {CROSS} {msg}")


def warn(msg: str):
    print(f"    {YELLOW}[WARN]{RESET} {msg}")


def find_project_root() -> Path:
    """Walk up from script dir to find build.zig."""
    d = Path(__file__).resolve().parent
    for _ in range(6):
        if (d / "build.zig").exists():
            return d
        d = d.parent
    return Path(__file__).resolve().parent.parent.parent


def check_zig() -> str | None:
    """Return zig version string, or None if not found."""
    try:
        result = subprocess.run(["zig", "version"], capture_output=True, text=True, timeout=10)
        if result.returncode == 0:
            return result.stdout.strip()
    except FileNotFoundError:
        pass
    return None


def build_node(project_root: Path) -> bool:
    step("Building node binary with zig build")
    try:
        result = subprocess.run(
            ["zig", "build"],
            cwd=str(project_root),
            capture_output=True, text=True, timeout=300,
        )
        if result.returncode == 0:
            ok("Build succeeded")
            return True
        else:
            fail("Build failed")
            print(f"    {DIM}{result.stderr[:500]}{RESET}")
            return False
    except subprocess.TimeoutExpired:
        fail("Build timed out (300s)")
        return False


def find_binary(project_root: Path) -> Path | None:
    candidates = [
        project_root / "zig-out" / "bin" / "omnibus-node.exe",
        project_root / "zig-out" / "bin" / "omnibus-node",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def generate_toml(target_dir: Path, mode: str, node_id: str,
                  port: int, rpc_port: int, seed_host: str, seed_port: int) -> Path:
    """Generate omnibus.toml config."""
    toml_content = textwrap.dedent(f"""\
        # OmniBus Node Configuration
        # Generated by deploy-node.py

        [node]
        id = "{node_id}"
        mode = "{mode}"
        data_dir = "."

        [network]
        p2p_port = {port}
        rpc_port = {rpc_port}
        ws_port = {rpc_port + 2}
        max_peers = 50

        [seed]
        host = "{seed_host}"
        port = {seed_port}

        [mining]
        enabled = {"true" if mode == "miner" else "false"}
        threads = 2

        [logging]
        level = "info"
        file = "omnibus.log"
    """)
    toml_path = target_dir / "omnibus.toml"
    toml_path.write_text(toml_content)
    return toml_path


def generate_systemd_service(target_dir: Path, binary_name: str, mode: str, node_id: str) -> Path:
    """Generate a systemd .service file."""
    binary_path = target_dir / binary_name
    service = textwrap.dedent(f"""\
        [Unit]
        Description=OmniBus Blockchain Node ({mode})
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=simple
        ExecStart={binary_path} --mode {mode} --node-id {node_id} --config {target_dir / "omnibus.toml"}
        WorkingDirectory={target_dir}
        Restart=on-failure
        RestartSec=10
        User=omnibus
        LimitNOFILE=65535

        [Install]
        WantedBy=multi-user.target
    """)
    svc_path = target_dir / f"omnibus-{mode}.service"
    svc_path.write_text(service)
    return svc_path


def generate_bat_launcher(target_dir: Path, binary_name: str, mode: str, node_id: str) -> Path:
    """Generate a Windows .bat launcher."""
    bat_content = textwrap.dedent(f"""\
        @echo off
        title OmniBus Node [{mode}] {node_id}
        echo ================================================
        echo   OmniBus Blockchain Node
        echo   Mode: {mode}    ID: {node_id}
        echo ================================================
        echo.
        cd /d "{target_dir}"
        "{target_dir / binary_name}" --mode {mode} --node-id {node_id} --config omnibus.toml
        pause
    """)
    bat_path = target_dir / f"start-omnibus-{mode}.bat"
    bat_path.write_text(bat_content)
    return bat_path


def main():
    parser = argparse.ArgumentParser(
        description="OmniBus Node Deployment Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python deploy-node.py --target-dir ./deploy --mode seed\n"
            "  python deploy-node.py --target-dir /opt/omnibus --mode miner --seed-host 10.0.0.1"
        ),
    )
    parser.add_argument("--target-dir", required=True, help="Directory to deploy the node into")
    parser.add_argument("--mode", choices=["seed", "miner"], default="seed",
                        help="Node mode: seed or miner (default: seed)")
    parser.add_argument("--node-id", default=None, help="Node identifier (default: auto-generated)")
    parser.add_argument("--port", type=int, default=9000, help="P2P port (default: 9000)")
    parser.add_argument("--rpc-port", type=int, default=8332, help="RPC port (default: 8332)")
    parser.add_argument("--seed-host", default="127.0.0.1", help="Seed node host (for miner mode)")
    parser.add_argument("--seed-port", type=int, default=9000, help="Seed node port (default: 9000)")
    parser.add_argument("--skip-build", action="store_true", help="Skip zig build step")
    args = parser.parse_args()

    node_id = args.node_id or f"{args.mode}-{os.getpid()}"
    target_dir = Path(args.target_dir).resolve()
    project_root = find_project_root()
    is_windows = platform.system() == "Windows"

    print(f"\n{CYAN}{BOLD}  OmniBus Node Deployment{RESET}")
    print(f"  {DIM}{'─' * 50}{RESET}")
    print(f"  {CYAN}Project root:{RESET}  {project_root}")
    print(f"  {CYAN}Target dir:{RESET}    {target_dir}")
    print(f"  {CYAN}Mode:{RESET}          {args.mode}")
    print(f"  {CYAN}Node ID:{RESET}       {node_id}")
    print(f"  {CYAN}Platform:{RESET}      {platform.system()}")

    # Step 1: Check Zig
    step("Checking Zig compiler")
    zig_ver = check_zig()
    if zig_ver:
        ok(f"Zig {zig_ver}")
    else:
        fail("Zig compiler not found in PATH")
        print(f"    {DIM}Install from https://ziglang.org/download/{RESET}")
        sys.exit(1)

    # Step 2: Build
    if not args.skip_build:
        if not build_node(project_root):
            fail("Cannot proceed without successful build")
            sys.exit(1)
    else:
        warn("Build step skipped (--skip-build)")

    # Step 3: Find and copy binary
    step("Locating compiled binary")
    binary = find_binary(project_root)
    if not binary:
        fail("Binary not found in zig-out/bin/")
        sys.exit(1)
    ok(f"Found {binary.name} ({binary.stat().st_size / 1024:.0f} KB)")

    step(f"Copying to {target_dir}")
    target_dir.mkdir(parents=True, exist_ok=True)
    dest_binary = target_dir / binary.name
    shutil.copy2(str(binary), str(dest_binary))
    ok(f"Copied to {dest_binary}")

    # Step 4: Generate config
    step("Generating omnibus.toml config")
    toml_path = generate_toml(target_dir, args.mode, node_id,
                               args.port, args.rpc_port, args.seed_host, args.seed_port)
    ok(f"Config written to {toml_path}")

    # Step 5: Generate launcher
    step("Generating launcher script")
    if is_windows:
        launcher = generate_bat_launcher(target_dir, binary.name, args.mode, node_id)
        ok(f"Windows launcher: {launcher}")
    else:
        launcher = generate_systemd_service(target_dir, binary.name, args.mode, node_id)
        ok(f"Systemd service: {launcher}")
        print(f"    {DIM}Install: sudo cp {launcher} /etc/systemd/system/{RESET}")
        print(f"    {DIM}Enable:  sudo systemctl enable omnibus-{args.mode}{RESET}")

    # Done
    print(f"\n  {DIM}{'─' * 50}{RESET}")
    print(f"  {GREEN}{BOLD}Deployment complete!{RESET}")
    print(f"  {DIM}To start: {'double-click ' + launcher.name if is_windows else f'systemctl start omnibus-{args.mode}'}{RESET}\n")


if __name__ == "__main__":
    main()
