var searchData=
[
  ['safety_20contract_20target_0',['Crash-safety contract (target)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md6',1,'']]],
  ['safety_20trail_1',['DB safety trail',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md31',1,'']]],
  ['same_2',['What stays the same',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md7',1,'']]],
  ['same_20day_3',['[v0.3.2] - 2026-04-25 (later same day)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md26',1,'']]],
  ['sample_5frecipients_4',['SAMPLE_RECIPIENTS',['../namespacetx-stress-sim.html#a45242ec75d7bd20fd8d1d449f5199fbf',1,'tx-stress-sim']]],
  ['seed_5fports_5',['SEED_PORTS',['../namespace_we-_are-_here-_hod_lum-_w_o_r_k_e_r.html#a6119dedbd63c08799b1f8ec039713999',1,'We-Are-Here-HodLum-WORKER']]],
  ['selection_20mainnet_20testnet_20regtest_6',['Added — Multi-chain Selection (Mainnet / Testnet / Regtest)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md33',1,'']]],
  ['selection_20was_20incomplete_20in_20v0_203_200_7',['Fixed — DB path wiring + chain selection (was incomplete in v0.3.0)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md27',1,'']]],
  ['self_20contained_8',['Each core/*.zig file is self-contained',['../md__c_l_a_u_d_e.html#autotoc_md51',1,'']]],
  ['send_5fone_9',['send_one',['../namespacetx-stress-sim.html#aba8cfc01767686cb28f1f3141af0f46c',1,'tx-stress-sim.send_one()'],['../namespacetx-stress-sim2.html#ad5ea2cc9c284531c81457a91078df94f',1,'tx-stress-sim2.send_one()']]],
  ['sent_10',['sent',['../classtx-stress-sim_1_1_stats.html#ab2be719ea269b628caf9a34eada8cdcd',1,'tx-stress-sim.Stats.sent'],['../classtx-stress-sim2_1_1_stats.html#ad623c040edefe507135f3af4b3d274be',1,'tx-stress-sim2.Stats.sent']]],
  ['separate_20dedicated_20session_11',['Migration plan (separate dedicated session)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md17',1,'']]],
  ['server_12',['Terminal 2: Start RPC Server',['../md__s_e_t_u_p.html#autotoc_md133',1,'']]],
  ['server_20won_20t_20start_13',['&quot;RPC server won&apos;t start&quot;',['../md__s_e_t_u_p.html#autotoc_md162',1,'']]],
  ['sesiunea_20următoare_14',['sesiunea următoare',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md92',1,'Order of operations recomandat pentru sesiunea următoare'],['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md86',1,'Pentru sesiunea următoare']]],
  ['session_15',['Migration plan (separate dedicated session)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md17',1,'']]],
  ['session_20plan_20—_20slot_20calendar_20spark_20sub_20block_20consensus_16',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['settlement_205–8_20h_17',['Phase 4 — Exchange match settlement (~5–8 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md21',1,'']]],
  ['setup_18',['Git Setup',['../md__s_e_t_u_p.html#autotoc_md155',1,'']]],
  ['setup_20getting_20started_19',['OmniBus BlockChain Core - Setup &amp;amp; Getting Started',['../md__s_e_t_u_p.html',1,'']]],
  ['setup_2emd_20',['SETUP.md',['../_s_e_t_u_p_8md.html',1,'']]],
  ['single_20run_21',['Best vs worst observed in a single run',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md63',1,'']]],
  ['sizes_20estimated_22',['Component sizes (estimated)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md4',1,'']]],
  ['slot_20calendar_20solana_20poh_20style_23',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['slot_20calendar_20spark_20sub_20block_20consensus_24',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['snippets_25',['EXISTING CODE (relevant snippets)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md69',1,'']]],
  ['solana_20poh_20style_26',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['source_27',['B.2 — Switch &lt;span class=&quot;tt&quot;&gt;getAddressBalance&lt;/span&gt; to UTXO source',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md77',1,'']]],
  ['source_20of_20truth_28',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['spark_20sub_20block_20consensus_29',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['spark_20sub_20block_20consensus_20viziunea_20ta_30',['2. SPARK Sub-Block Consensus (viziunea ta)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md88',1,'']]],
  ['spec_31',['Bitcoin-style Storage Refactor — Architecture Spec',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html',1,'']]],
  ['specific_20constraints_32',['OMNIBUS-SPECIFIC CONSTRAINTS',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md74',1,'']]],
  ['spectrum_20visualizer_33',['4. UI spectrum visualizer',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md90',1,'']]],
  ['spend_20the_20inputs_34',['B.1 — Make &lt;span class=&quot;tt&quot;&gt;applyBlock&lt;/span&gt; spend the inputs',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md76',1,'']]],
  ['stack_35',['Cryptographic stack',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md59',1,'']]],
  ['standard_20bitcoin_20rpc_20methods_36',['Added — 7 missing standard Bitcoin RPC methods',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md29',1,'']]],
  ['start_37',['&quot;RPC server won&apos;t start&quot;',['../md__s_e_t_u_p.html#autotoc_md162',1,'']]],
  ['start_205_20minutes_38',['Quick Start (5 Minutes)',['../md__s_e_t_u_p.html#autotoc_md125',1,'']]],
  ['start_20blockchain_20mining_39',['Terminal 1: Start Blockchain (Mining)',['../md__s_e_t_u_p.html#autotoc_md132',1,'']]],
  ['start_20frontend_40',['Terminal 3: Start Frontend',['../md__s_e_t_u_p.html#autotoc_md134',1,'']]],
  ['start_20rpc_20server_41',['Terminal 2: Start RPC Server',['../md__s_e_t_u_p.html#autotoc_md133',1,'']]],
  ['started_42',['OmniBus BlockChain Core - Setup &amp;amp; Getting Started',['../md__s_e_t_u_p.html',1,'']]],
  ['started_5fat_43',['started_at',['../classtx-stress-sim_1_1_stats.html#a8fcf7e304216e65d1b92f2a24a73d8e7',1,'tx-stress-sim.Stats.started_at'],['../classtx-stress-sim2_1_1_stats.html#ab1a37818e606e9a59eecd5fc301ee45c',1,'tx-stress-sim2.Stats.started_at']]],
  ['startup_20core_20main_20zig_44',['Node Startup (core/main.zig)',['../md__c_l_a_u_d_e.html#autotoc_md48',1,'']]],
  ['state_20change_20must_20be_20a_20chain_20tx_45',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['stats_46',['Stats',['../classtx-stress-sim2_1_1_stats.html',1,'tx-stress-sim2.Stats'],['../classtx-stress-sim_1_1_stats.html',1,'tx-stress-sim.Stats']]],
  ['status_20implementare_47',['Status implementare',['../md__r_e_a_d_m_e.html#autotoc_md114',1,'']]],
  ['stays_20in_20memory_20legitimately_48',['What stays in memory (legitimately)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md16',1,'']]],
  ['stays_20the_20same_49',['What stays the same',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md7',1,'']]],
  ['storage_20refactor_20—_20architecture_20spec_50',['Bitcoin-style Storage Refactor — Architecture Spec',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html',1,'']]],
  ['strategy_51',['Migration strategy',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md5',1,'']]],
  ['stretch_20goals_20post_20mvp_52',['Stretch goals (post-MVP)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md8',1,'']]],
  ['structura_20proiectului_53',['Structura proiectului',['../md__r_e_a_d_m_e.html#autotoc_md100',1,'']]],
  ['structure_54',['Project Structure',['../md__s_e_t_u_p.html#autotoc_md140',1,'']]],
  ['style_55',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['style_20omnibus_20tuned_56',['What we move to (Bitcoin-style, OmniBus-tuned)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md3',1,'']]],
  ['style_20storage_20refactor_20—_20architecture_20spec_57',['Bitcoin-style Storage Refactor — Architecture Spec',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html',1,'']]],
  ['sub_20block_20consensus_58',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['sub_20block_20consensus_20viziunea_20ta_59',['2. SPARK Sub-Block Consensus (viziunea ta)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md88',1,'']]],
  ['supervault_60',['Integrare SuperVault',['../md__r_e_a_d_m_e.html#autotoc_md112',1,'']]],
  ['switch_20getaddressbalance_20to_20utxo_20source_61',['B.2 — Switch &lt;span class=&quot;tt&quot;&gt;getAddressBalance&lt;/span&gt; to UTXO source',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md77',1,'']]],
  ['switch_20omnibus_20l1_20from_20ram_20cached_20balances_20to_20utxo_20source_20of_20truth_62',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['system_63',['System',['../md__s_e_t_u_p.html#autotoc_md131',1,'Run the System'],['../md__s_e_t_u_p.html#autotoc_md136',1,'Test the System']]]
];
