var searchData=
[
  ['a_20chain_20tx_0',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['a_20single_20run_1',['Best vs worst observed in a single run',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md63',1,'']]],
  ['acceptance_20criteria_2',['Acceptance criteria',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md23',1,'']]],
  ['accepted_3',['accepted',['../classtx-stress-sim_1_1_stats.html#a746c7a8554a1e75d73c2096470d63d30',1,'tx-stress-sim.Stats.accepted'],['../classtx-stress-sim2_1_1_stats.html#aca7a40c1429c4fcaa6e8966401f0fe7a',1,'tx-stress-sim2.Stats.accepted']]],
  ['actually_20does_4',['What Bitcoin actually does',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md1',1,'']]],
  ['added_5',['Added',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md43',1,'']]],
  ['added_20—_207_20missing_20standard_20bitcoin_20rpc_20methods_6',['Added — 7 missing standard Bitcoin RPC methods',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md29',1,'']]],
  ['added_20—_20bech32_20addresses_20full_20btc_20parity_20115_7',['Added — Bech32 Addresses + Full BTC Parity (115%)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md39',1,'']]],
  ['added_20—_20multi_20chain_20selection_20mainnet_20testnet_20regtest_8',['Added — Multi-chain Selection (Mainnet / Testnet / Regtest)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md33',1,'']]],
  ['addr_5fstats_9',['addr_stats',['../classtx-stress-sim2_1_1_stats.html#af6b2b51716b52895c2815011d17fc91e',1,'tx-stress-sim2::Stats']]],
  ['addresses_20full_20btc_20parity_20115_10',['Added — Bech32 Addresses + Full BTC Parity (115%)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md39',1,'']]],
  ['agent_20tx_20ification_203_20h_11',['Phase 3 — Agent TX-ification (~3 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md20',1,'']]],
  ['already_20implemented_20currently_12',['&lt;span class=&quot;tt&quot;&gt;core/utxo.zig&lt;/span&gt; (excerpts — already implemented, currently',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md71',1,'']]],
  ['alternative_20architectures_20for_20omnibus_20block_20rate_20problem_13',['Prompt for Kimi — alternative architectures for OmniBus block-rate problem',['../md__k_i_m_i___p_r_o_m_p_t.html',1,'']]],
  ['and_20lost_14',['Best ever observed (and lost)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md62',1,'']]],
  ['api_20—_20port_208332_15',['RPC API — port 8332',['../md__r_e_a_d_m_e.html#autotoc_md102',1,'']]],
  ['api_5fkey_5fid_16',['API_KEY_ID',['../namespacetest__rest__hmac.html#a900bb4c80653b779858000a412a13435',1,'test_rest_hmac']]],
  ['api_5fsecret_5fb64_17',['API_SECRET_B64',['../namespacetest__rest__hmac.html#a27a33f19d28b5df91ff0e238c0be9742',1,'test_rest_hmac']]],
  ['applyblock_20spend_20the_20inputs_18',['B.1 — Make &lt;span class=&quot;tt&quot;&gt;applyBlock&lt;/span&gt; spend the inputs',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md76',1,'']]],
  ['approximate_19',['Where UTXO is currently populated (line numbers approximate)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md72',1,'']]],
  ['arch_5fbitcoin_5fstorage_2emd_20',['ARCH_BITCOIN_STORAGE.md',['../_a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e_8md.html',1,'']]],
  ['arch_5ffix_5ftx_5fonly_2emd_21',['ARCH_FIX_TX_ONLY.md',['../_a_r_c_h___f_i_x___t_x___o_n_l_y_8md.html',1,'']]],
  ['architectural_20fix_3a_20every_20state_20change_20must_20be_20a_20chain_20tx_22',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['architecture_23',['Architecture',['../md__c_l_a_u_d_e.html#autotoc_md47',1,'']]],
  ['architecture_20current_20working_24',['Architecture (current, working)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md58',1,'']]],
  ['architecture_20spec_25',['Bitcoin-style Storage Refactor — Architecture Spec',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html',1,'']]],
  ['architectures_20for_20omnibus_20block_20rate_20problem_26',['Prompt for Kimi — alternative architectures for OmniBus block-rate problem',['../md__k_i_m_i___p_r_o_m_p_t.html',1,'']]],
  ['assertion_27',['B.3 — Audit assertion',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md78',1,'']]],
  ['audit_20assertion_28',['B.3 — Audit assertion',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md78',1,'']]],
  ['audit_20tooling_202_20h_29',['Phase 5 — Audit + tooling (~2 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md22',1,'']]],
  ['authors_30',['Co-Authors',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md37',1,'']]]
];
