var searchData=
[
  ['t_20load_0',['&quot;Frontend won&apos;t load&quot;',['../md__s_e_t_u_p.html#autotoc_md163',1,'']]],
  ['t_20start_1',['&quot;RPC server won&apos;t start&quot;',['../md__s_e_t_u_p.html#autotoc_md162',1,'']]],
  ['ta_2',['2. SPARK Sub-Block Consensus (viziunea ta)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md88',1,'']]],
  ['target_3',['Crash-safety contract (target)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md6',1,'']]],
  ['tasks_20current_20week_4',['Phase 1 Tasks (Current Week)',['../md__s_e_t_u_p.html#autotoc_md143',1,'']]],
  ['tasks_20week_202_5',['Phase 2 Tasks (Week 2)',['../md__s_e_t_u_p.html#autotoc_md144',1,'']]],
  ['tasks_20week_203_6',['Phase 3 Tasks (Week 3)',['../md__s_e_t_u_p.html#autotoc_md145',1,'']]],
  ['tasks_20week_204_7',['Phase 4 Tasks (Week 4)',['../md__s_e_t_u_p.html#autotoc_md146',1,'']]],
  ['tasks_20week_205_8',['Phase 5 Tasks (Week 5)',['../md__s_e_t_u_p.html#autotoc_md147',1,'']]],
  ['tehnice_20per_20platform_20pentru_20clock_9',['3. Detalii tehnice per platform pentru clock',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md89',1,'']]],
  ['terminal_201_3a_20start_20blockchain_20mining_10',['Terminal 1: Start Blockchain (Mining)',['../md__s_e_t_u_p.html#autotoc_md132',1,'']]],
  ['terminal_202_3a_20start_20rpc_20server_11',['Terminal 2: Start RPC Server',['../md__s_e_t_u_p.html#autotoc_md133',1,'']]],
  ['terminal_203_3a_20start_20frontend_12',['Terminal 3: Start Frontend',['../md__s_e_t_u_p.html#autotoc_md134',1,'']]],
  ['test_13',['✅ Build &amp;amp; Test',['../md__s_e_t_u_p.html#autotoc_md122',1,'']]],
  ['test_20infrastructure_14',['Test infrastructure',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md30',1,'']]],
  ['test_20rpc_20endpoints_20via_20curl_15',['Test RPC Endpoints (via curl)',['../md__s_e_t_u_p.html#autotoc_md138',1,'']]],
  ['test_20the_20system_16',['Test the System',['../md__s_e_t_u_p.html#autotoc_md136',1,'']]],
  ['test_5fopenapi_17',['test_openapi',['../namespacetest__rest__hmac.html#a8e30d2b4bad2fada0efdddf83eb93b1e',1,'test_rest_hmac']]],
  ['test_5fprivate_5fadd_5forder_18',['test_private_add_order',['../namespacetest__rest__hmac.html#a06259ef206eb13425de0486074e078e1',1,'test_rest_hmac']]],
  ['test_5fprivate_5fbalance_19',['test_private_balance',['../namespacetest__rest__hmac.html#aff138f9ec0001f4ff02a94a80dcc4d4a',1,'test_rest_hmac']]],
  ['test_5fpublic_20',['test_public',['../namespacetest__rest__hmac.html#a03385f61a5d473360c981fc69d866a55',1,'test_rest_hmac']]],
  ['test_5frest_5fhmac_21',['test_rest_hmac',['../namespacetest__rest__hmac.html',1,'']]],
  ['test_5frest_5fhmac_2epy_22',['test_rest_hmac.py',['../test__rest__hmac_8py.html',1,'']]],
  ['testing_23',['Testing',['../md__c_l_a_u_d_e.html#autotoc_md46',1,'']]],
  ['testnet_20regtest_24',['Added — Multi-chain Selection (Mainnet / Testnet / Regtest)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md33',1,'']]],
  ['tests_25',['Tests',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md79',1,'B.4 — Tests'],['../md__s_e_t_u_p.html#autotoc_md137',1,'Run Unit Tests'],['../md__r_e_a_d_m_e.html#autotoc_md110',1,'Tests']]],
  ['the_20broken_20design_26',['What we have today (the broken design)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md2',1,'']]],
  ['the_20bug_20we_20just_20hit_202026_2004_2028_27',['The bug we just hit (2026-04-28)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md13',1,'']]],
  ['the_20bug_20we_20re_20fixing_28',['THE BUG WE&apos;RE FIXING',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md73',1,'']]],
  ['the_20inputs_29',['B.1 — Make &lt;span class=&quot;tt&quot;&gt;applyBlock&lt;/span&gt; spend the inputs',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md76',1,'']]],
  ['the_20rule_30',['The rule',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md14',1,'']]],
  ['the_20same_31',['What stays the same',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md7',1,'']]],
  ['the_20system_32',['the System',['../md__s_e_t_u_p.html#autotoc_md131',1,'Run the System'],['../md__s_e_t_u_p.html#autotoc_md136',1,'Test the System']]],
  ['this_20matters_33',['Why this matters',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md11',1,'']]],
  ['to_20become_20tx_20on_20chain_34',['What needs to become TX-on-chain',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md15',1,'']]],
  ['to_20bitcoin_20style_20omnibus_20tuned_35',['What we move to (Bitcoin-style, OmniBus-tuned)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md3',1,'']]],
  ['to_20do_20next_36',['What to Do Next',['../md__s_e_t_u_p.html#autotoc_md142',1,'']]],
  ['to_20focus_20on_37',['Files to Focus On',['../md__s_e_t_u_p.html#autotoc_md149',1,'']]],
  ['to_20github_38',['Push to GitHub',['../md__s_e_t_u_p.html#autotoc_md157',1,'']]],
  ['to_20project_39',['2. Navigate to Project',['../md__s_e_t_u_p.html#autotoc_md127',1,'']]],
  ['to_20resolve_20before_20coding_40',['Open questions to resolve before coding',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md9',1,'']]],
  ['to_20utxo_20source_41',['B.2 — Switch &lt;span class=&quot;tt&quot;&gt;getAddressBalance&lt;/span&gt; to UTXO source',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md77',1,'']]],
  ['to_20utxo_20source_20of_20truth_42',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['today_20interim_43',['What we do today (interim)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md24',1,'']]],
  ['today_20the_20broken_20design_44',['What we have today (the broken design)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md2',1,'']]],
  ['tooling_202_20h_45',['Phase 5 — Audit + tooling (~2 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md22',1,'']]],
  ['trail_46',['DB safety trail',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md31',1,'']]],
  ['troubleshooting_47',['Troubleshooting',['../md__s_e_t_u_p.html#autotoc_md159',1,'']]],
  ['truth_48',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['tuned_49',['What we move to (Bitcoin-style, OmniBus-tuned)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md3',1,'']]],
  ['tx_50',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['tx_51',['tx',['../namespacetx.html',1,'']]],
  ['tx_20ification_203–4_20h_52',['Phase 1 — Faucet TX-ification (~3–4 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md18',1,'']]],
  ['tx_20ification_203_20h_53',['Phase 3 — Agent TX-ification (~3 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md20',1,'']]],
  ['tx_20ification_204–6_20h_54',['Phase 2 — Reputation TX-ification (~4–6 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md19',1,'']]],
  ['tx_20on_20chain_55',['What needs to become TX-on-chain',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md15',1,'']]],
  ['tx_2dstress_2dsim_56',['tx-stress-sim',['../namespacetx-stress-sim.html',1,'']]],
  ['tx_2dstress_2dsim_2epy_57',['tx-stress-sim.py',['../tx-stress-sim_8py.html',1,'']]],
  ['tx_2dstress_2dsim2_58',['tx-stress-sim2',['../namespacetx-stress-sim2.html',1,'']]],
  ['tx_2dstress_2dsim2_2epy_59',['tx-stress-sim2.py',['../tx-stress-sim2_8py.html',1,'']]],
  ['typescript_20react_60',['✅ Frontend (TypeScript/React)',['../md__s_e_t_u_p.html#autotoc_md121',1,'']]]
];
