var searchData=
[
  ['parameters_0',['Key Parameters',['../md__c_l_a_u_d_e.html#autotoc_md52',1,'']]],
  ['parameters_20reference_1',['Blockchain Parameters (Reference)',['../md__s_e_t_u_p.html#autotoc_md151',1,'']]],
  ['parametri_20blockchain_2',['Parametri Blockchain',['../md__r_e_a_d_m_e.html#autotoc_md106',1,'']]],
  ['parity_20115_3',['Added — Bech32 Addresses + Full BTC Parity (115%)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md39',1,'']]],
  ['parse_5fduration_4',['parse_duration',['../namespacetx-stress-sim.html#ac9ab6d0c4e90563cfd586f010baa2f74',1,'tx-stress-sim.parse_duration()'],['../namespacetx-stress-sim2.html#ac9ab6d0c4e90563cfd586f010baa2f74',1,'tx-stress-sim2.parse_duration()']]],
  ['path_20wiring_20chain_20selection_20was_20incomplete_20in_20v0_203_200_5',['Fixed — DB path wiring + chain selection (was incomplete in v0.3.0)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md27',1,'']]],
  ['pentru_20clock_6',['3. Detalii tehnice per platform pentru clock',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md89',1,'']]],
  ['pentru_20sesiunea_20următoare_7',['Pentru sesiunea următoare',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md86',1,'']]],
  ['pentru_20sesiunea_20următoare_8',['Order of operations recomandat pentru sesiunea următoare',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md92',1,'']]],
  ['per_20platform_20pentru_20clock_9',['3. Detalii tehnice per platform pentru clock',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md89',1,'']]],
  ['performance_20measured_10',['Performance, measured',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md60',1,'']]],
  ['persistent_20problem_11',['Persistent problem',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md64',1,'']]],
  ['phase_201_12',['RPC Methods (Phase 1)',['../md__s_e_t_u_p.html#autotoc_md153',1,'']]],
  ['phase_201_20—_20faucet_20tx_20ification_203–4_20h_13',['Phase 1 — Faucet TX-ification (~3–4 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md18',1,'']]],
  ['phase_201_20tasks_20current_20week_14',['Phase 1 Tasks (Current Week)',['../md__s_e_t_u_p.html#autotoc_md143',1,'']]],
  ['phase_202_20—_20reputation_20tx_20ification_204–6_20h_15',['Phase 2 — Reputation TX-ification (~4–6 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md19',1,'']]],
  ['phase_202_20tasks_20week_202_16',['Phase 2 Tasks (Week 2)',['../md__s_e_t_u_p.html#autotoc_md144',1,'']]],
  ['phase_203_20—_20agent_20tx_20ification_203_20h_17',['Phase 3 — Agent TX-ification (~3 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md20',1,'']]],
  ['phase_203_20tasks_20week_203_18',['Phase 3 Tasks (Week 3)',['../md__s_e_t_u_p.html#autotoc_md145',1,'']]],
  ['phase_204_20—_20exchange_20match_20settlement_205–8_20h_19',['Phase 4 — Exchange match settlement (~5–8 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md21',1,'']]],
  ['phase_204_20tasks_20week_204_20',['Phase 4 Tasks (Week 4)',['../md__s_e_t_u_p.html#autotoc_md146',1,'']]],
  ['phase_205_20—_20audit_20tooling_202_20h_21',['Phase 5 — Audit + tooling (~2 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md22',1,'']]],
  ['phase_205_20tasks_20week_205_22',['Phase 5 Tasks (Week 5)',['../md__s_e_t_u_p.html#autotoc_md147',1,'']]],
  ['phase_20b_20—_20deliverable_23',['PHASE B — DELIVERABLE',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md75',1,'']]],
  ['phase_20c_20—_20design_20only_24',['PHASE C — DESIGN ONLY',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md81',1,'']]],
  ['plan_20—_20slot_20calendar_20spark_20sub_20block_20consensus_25',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['plan_20separate_20dedicated_20session_26',['Migration plan (separate dedicated session)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md17',1,'']]],
  ['platform_20pentru_20clock_27',['3. Detalii tehnice per platform pentru clock',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md89',1,'']]],
  ['poh_20style_28',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['pool_20node_20js_29',['Mining Pool (Node.js)',['../md__r_e_a_d_m_e.html#autotoc_md108',1,'']]],
  ['populated_20line_20numbers_20approximate_30',['Where UTXO is currently populated (line numbers approximate)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md72',1,'']]],
  ['port_208332_31',['RPC API — port 8332',['../md__r_e_a_d_m_e.html#autotoc_md102',1,'']]],
  ['post_20mvp_32',['Stretch goals (post-MVP)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md8',1,'']]],
  ['post_20quantum_33',['Wallet — 5 Domenii Post-Quantum',['../md__r_e_a_d_m_e.html#autotoc_md104',1,'']]],
  ['pre_20computed_20slot_20calendar_20solana_20poh_20style_34',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['prerequisites_35',['1. Verify Prerequisites',['../md__s_e_t_u_p.html#autotoc_md126',1,'']]],
  ['problem_36',['problem',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md64',1,'Persistent problem'],['../md__k_i_m_i___p_r_o_m_p_t.html',1,'Prompt for Kimi — alternative architectures for OmniBus block-rate problem']]],
  ['proiectului_37',['Structura proiectului',['../md__r_e_a_d_m_e.html#autotoc_md100',1,'']]],
  ['project_38',['2. Navigate to Project',['../md__s_e_t_u_p.html#autotoc_md127',1,'']]],
  ['project_20structure_39',['Project Structure',['../md__s_e_t_u_p.html#autotoc_md140',1,'']]],
  ['prompt_20for_20kimi_20—_20alternative_20architectures_20for_20omnibus_20block_20rate_20problem_40',['Prompt for Kimi — alternative architectures for OmniBus block-rate problem',['../md__k_i_m_i___p_r_o_m_p_t.html',1,'']]],
  ['prompt_20for_20kimi_20—_20switch_20omnibus_20l1_20from_20ram_20cached_20balances_20to_20utxo_20source_20of_20truth_41',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['propagation_42',['B.5 — RPC propagation',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md80',1,'']]],
  ['push_20to_20github_43',['Push to GitHub',['../md__s_e_t_u_p.html#autotoc_md157',1,'']]]
];
