var searchData=
[
  ['c_0',['C',['../class_we-_are-_here-_hod_lum-_w_o_r_k_e_r_1_1_c.html',1,'We-Are-Here-HodLum-WORKER']]],
  ['c_20—_20design_20only_1',['PHASE C — DESIGN ONLY',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md81',1,'']]],
  ['cached_20balances_20to_20utxo_20source_20of_20truth_2',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['calendar_20solana_20poh_20style_3',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['calendar_20spark_20sub_20block_20consensus_4',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['ce_20este_5',['Ce este',['../md__r_e_a_d_m_e.html#autotoc_md96',1,'']]],
  ['chain_6',['What needs to become TX-on-chain',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md15',1,'']]],
  ['chain_20selection_20mainnet_20testnet_20regtest_7',['Added — Multi-chain Selection (Mainnet / Testnet / Regtest)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md33',1,'']]],
  ['chain_20selection_20was_20incomplete_20in_20v0_203_200_8',['Fixed — DB path wiring + chain selection (was incomplete in v0.3.0)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md27',1,'']]],
  ['chain_20tx_9',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['chain_5fsnapshot_10',['chain_snapshot',['../namespacetx-stress-sim.html#a719aaefb29d6ae0104e76b63b1fe3c80',1,'tx-stress-sim.chain_snapshot()'],['../namespacetx-stress-sim2.html#a42abc4ec911393d78ca225b85f3de28f',1,'tx-stress-sim2.chain_snapshot()']]],
  ['change_20must_20be_20a_20chain_20tx_11',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['changed_12',['Changed',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md40',1,'']]],
  ['changelog_13',['Changelog',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['changelog_2emd_14',['CHANGELOG.md',['../_c_h_a_n_g_e_l_o_g_8md.html',1,'']]],
  ['claude_20md_15',['CLAUDE.md',['../md__c_l_a_u_d_e.html',1,'']]],
  ['claude_2emd_16',['CLAUDE.md',['../_c_l_a_u_d_e_8md.html',1,'']]],
  ['clock_17',['3. Detalii tehnice per platform pentru clock',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md89',1,'']]],
  ['co_20authors_18',['Co-Authors',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md37',1,'']]],
  ['code_20relevant_20snippets_19',['EXISTING CODE (relevant snippets)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md69',1,'']]],
  ['coding_20',['Open questions to resolve before coding',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md9',1,'']]],
  ['colorize_5flog_5fline_21',['colorize_log_line',['../namespace_we-_are-_here-_hod_lum-_w_o_r_k_e_r.html#a5ec78d4d15f3bfc669b4bd09efcba0d5',1,'We-Are-Here-HodLum-WORKER']]],
  ['command_20not_20found_3a_20zig_22',['&quot;Command not found: zig&quot;',['../md__s_e_t_u_p.html#autotoc_md160',1,'']]],
  ['commit_20history_20newest_20first_23',['Recent commit history (newest first)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md61',1,'']]],
  ['compatibility_24',['Compatibility',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md34',1,'']]],
  ['component_20sizes_20estimated_25',['Component sizes (estimated)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md4',1,'']]],
  ['components_20zig_20backend_26',['✅ Core Components (Zig Backend)',['../md__s_e_t_u_p.html#autotoc_md120',1,'']]],
  ['computed_20slot_20calendar_20solana_20poh_20style_27',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['configuration_28',['✅ Configuration',['../md__s_e_t_u_p.html#autotoc_md123',1,'']]],
  ['consensus_29',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['consensus_20viziunea_20ta_30',['2. SPARK Sub-Block Consensus (viziunea ta)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md88',1,'']]],
  ['constraints_31',['OMNIBUS-SPECIFIC CONSTRAINTS',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md74',1,'']]],
  ['contained_32',['Each core/*.zig file is self-contained',['../md__c_l_a_u_d_e.html#autotoc_md51',1,'']]],
  ['context_33',['CONTEXT',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md57',1,'']]],
  ['context_34',['Ecosystem Context',['../md__c_l_a_u_d_e.html#autotoc_md54',1,'']]],
  ['contract_20target_35',['Crash-safety contract (target)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md6',1,'']]],
  ['core_20blockchain_20zig_20excerpts_36',['&lt;span class=&quot;tt&quot;&gt;core/blockchain.zig&lt;/span&gt; (excerpts)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md70',1,'']]],
  ['core_20components_20zig_20backend_37',['✅ Core Components (Zig Backend)',['../md__s_e_t_u_p.html#autotoc_md120',1,'']]],
  ['core_20layers_38',['Core Layers',['../md__c_l_a_u_d_e.html#autotoc_md49',1,'']]],
  ['core_20main_20zig_39',['Node Startup (core/main.zig)',['../md__c_l_a_u_d_e.html#autotoc_md48',1,'']]],
  ['core_20setup_20getting_20started_40',['OmniBus BlockChain Core - Setup &amp;amp; Getting Started',['../md__s_e_t_u_p.html',1,'']]],
  ['core_20utxo_20zig_20excerpts_20—_20already_20implemented_20currently_41',['&lt;span class=&quot;tt&quot;&gt;core/utxo.zig&lt;/span&gt; (excerpts — already implemented, currently',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md71',1,'']]],
  ['core_20zig_20file_20is_20self_20contained_42',['Each core/*.zig file is self-contained',['../md__c_l_a_u_d_e.html#autotoc_md51',1,'']]],
  ['crash_20safety_20contract_20target_43',['Crash-safety contract (target)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md6',1,'']]],
  ['created_44',['What Was Created',['../md__s_e_t_u_p.html#autotoc_md119',1,'']]],
  ['criteria_45',['Acceptance criteria',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md23',1,'']]],
  ['cryptographic_20stack_46',['Cryptographic stack',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md59',1,'']]],
  ['cu_20omnibussidebar_47',['Legătură cu OmnibusSidebar',['../md__r_e_a_d_m_e.html#autotoc_md116',1,'']]],
  ['curl_48',['Test RPC Endpoints (via curl)',['../md__s_e_t_u_p.html#autotoc_md138',1,'']]],
  ['current_20week_49',['Phase 1 Tasks (Current Week)',['../md__s_e_t_u_p.html#autotoc_md143',1,'']]],
  ['current_20working_50',['Architecture (current, working)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md58',1,'']]],
  ['currently_51',['&lt;span class=&quot;tt&quot;&gt;core/utxo.zig&lt;/span&gt; (excerpts — already implemented, currently',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md71',1,'']]],
  ['currently_20populated_20line_20numbers_20approximate_52',['Where UTXO is currently populated (line numbers approximate)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md72',1,'']]],
  ['cyan_53',['CYAN',['../class_we-_are-_here-_hod_lum-_w_o_r_k_e_r_1_1_c.html#a8277021fefb9756fe1a093b68ae4d7fe',1,'We-Are-Here-HodLum-WORKER::C']]]
];
