var searchData=
[
  ['ram_20cached_20balances_20to_20utxo_20source_20of_20truth_0',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['rapid_1',['Build rapid',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['rate_20problem_2',['Prompt for Kimi — alternative architectures for OmniBus block-rate problem',['../md__k_i_m_i___p_r_o_m_p_t.html',1,'']]],
  ['re_20fixing_3',['THE BUG WE&apos;RE FIXING',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md73',1,'']]],
  ['react_4',['✅ Frontend (TypeScript/React)',['../md__s_e_t_u_p.html#autotoc_md121',1,'']]],
  ['recent_20commit_20history_20newest_20first_5',['Recent commit history (newest first)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md61',1,'']]],
  ['recomandat_20pentru_20sesiunea_20următoare_6',['Order of operations recomandat pentru sesiunea următoare',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md92',1,'']]],
  ['refactor_20—_20architecture_20spec_7',['Bitcoin-style Storage Refactor — Architecture Spec',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html',1,'']]],
  ['reference_8',['Blockchain Parameters (Reference)',['../md__s_e_t_u_p.html#autotoc_md151',1,'']]],
  ['regtest_9',['Added — Multi-chain Selection (Mainnet / Testnet / Regtest)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md33',1,'']]],
  ['relevant_20snippets_10',['EXISTING CODE (relevant snippets)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md69',1,'']]],
  ['repository_11',['Initialize Repository',['../md__s_e_t_u_p.html#autotoc_md156',1,'']]],
  ['reputation_20tx_20ification_204–6_20h_12',['Phase 2 — Reputation TX-ification (~4–6 h)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md19',1,'']]],
  ['resolve_20before_20coding_13',['Open questions to resolve before coding',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md9',1,'']]],
  ['resources_14',['Resources',['../md__s_e_t_u_p.html#autotoc_md165',1,'']]],
  ['role_15',['ROLE',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md68',1,'']]],
  ['rpc_20api_20—_20port_208332_16',['RPC API — port 8332',['../md__r_e_a_d_m_e.html#autotoc_md102',1,'']]],
  ['rpc_20endpoints_20via_20curl_17',['Test RPC Endpoints (via curl)',['../md__s_e_t_u_p.html#autotoc_md138',1,'']]],
  ['rpc_20methods_18',['Added — 7 missing standard Bitcoin RPC methods',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md29',1,'']]],
  ['rpc_20methods_20phase_201_19',['RPC Methods (Phase 1)',['../md__s_e_t_u_p.html#autotoc_md153',1,'']]],
  ['rpc_20propagation_20',['B.5 — RPC propagation',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md80',1,'']]],
  ['rpc_20server_21',['Terminal 2: Start RPC Server',['../md__s_e_t_u_p.html#autotoc_md133',1,'']]],
  ['rpc_20server_20won_20t_20start_22',['&quot;RPC server won&apos;t start&quot;',['../md__s_e_t_u_p.html#autotoc_md162',1,'']]],
  ['rule_23',['The rule',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md14',1,'']]],
  ['rules_24',['GROUND RULES',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md83',1,'']]],
  ['run_25',['Build &amp;amp; Run',['../md__c_l_a_u_d_e.html#autotoc_md45',1,'']]],
  ['run_26',['Best vs worst observed in a single run',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md63',1,'']]],
  ['run_20the_20system_27',['Run the System',['../md__s_e_t_u_p.html#autotoc_md131',1,'']]],
  ['run_20unit_20tests_28',['Run Unit Tests',['../md__s_e_t_u_p.html#autotoc_md137',1,'']]]
];
