var searchData=
[
  ['b_20—_20deliverable_0',['PHASE B — DELIVERABLE',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md75',1,'']]],
  ['b_201_20—_20make_20applyblock_20spend_20the_20inputs_1',['B.1 — Make &lt;span class=&quot;tt&quot;&gt;applyBlock&lt;/span&gt; spend the inputs',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md76',1,'']]],
  ['b_202_20—_20switch_20getaddressbalance_20to_20utxo_20source_2',['B.2 — Switch &lt;span class=&quot;tt&quot;&gt;getAddressBalance&lt;/span&gt; to UTXO source',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md77',1,'']]],
  ['b_203_20—_20audit_20assertion_3',['B.3 — Audit assertion',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md78',1,'']]],
  ['b_204_20—_20tests_4',['B.4 — Tests',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md79',1,'']]],
  ['b_205_20—_20rpc_20propagation_5',['B.5 — RPC propagation',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md80',1,'']]],
  ['back_6',['DELIVERABLES (what you give back)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md82',1,'']]],
  ['backend_7',['✅ Core Components (Zig Backend)',['../md__s_e_t_u_p.html#autotoc_md120',1,'']]],
  ['balances_20to_20utxo_20source_20of_20truth_8',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['be_20a_20chain_20tx_9',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['bech32_20addresses_20full_20btc_20parity_20115_10',['Added — Bech32 Addresses + Full BTC Parity (115%)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md39',1,'']]],
  ['become_20tx_20on_20chain_11',['What needs to become TX-on-chain',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md15',1,'']]],
  ['before_20coding_12',['Open questions to resolve before coding',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md9',1,'']]],
  ['best_20ever_20observed_20and_20lost_13',['Best ever observed (and lost)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md62',1,'']]],
  ['best_20vs_20worst_20observed_20in_20a_20single_20run_14',['Best vs worst observed in a single run',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md63',1,'']]],
  ['bitcoin_20actually_20does_15',['What Bitcoin actually does',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md1',1,'']]],
  ['bitcoin_20rpc_20methods_16',['Added — 7 missing standard Bitcoin RPC methods',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md29',1,'']]],
  ['bitcoin_20style_20omnibus_20tuned_17',['What we move to (Bitcoin-style, OmniBus-tuned)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md3',1,'']]],
  ['bitcoin_20style_20storage_20refactor_20—_20architecture_20spec_18',['Bitcoin-style Storage Refactor — Architecture Spec',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html',1,'']]],
  ['block_20consensus_19',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['block_20consensus_20viziunea_20ta_20',['2. SPARK Sub-Block Consensus (viziunea ta)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md88',1,'']]],
  ['block_20rate_20problem_21',['Prompt for Kimi — alternative architectures for OmniBus block-rate problem',['../md__k_i_m_i___p_r_o_m_p_t.html',1,'']]],
  ['blockchain_22',['Parametri Blockchain',['../md__r_e_a_d_m_e.html#autotoc_md106',1,'']]],
  ['blockchain_20core_20setup_20getting_20started_23',['OmniBus BlockChain Core - Setup &amp;amp; Getting Started',['../md__s_e_t_u_p.html',1,'']]],
  ['blockchain_20mining_24',['Terminal 1: Start Blockchain (Mining)',['../md__s_e_t_u_p.html#autotoc_md132',1,'']]],
  ['blockchain_20parameters_20reference_25',['Blockchain Parameters (Reference)',['../md__s_e_t_u_p.html#autotoc_md151',1,'']]],
  ['blockchain_20zig_20excerpts_26',['&lt;span class=&quot;tt&quot;&gt;core/blockchain.zig&lt;/span&gt; (excerpts)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md70',1,'']]],
  ['blockchaincore_27',['OmniBus-BlockChainCore',['../md__r_e_a_d_m_e.html',1,'']]],
  ['branch_20layout_28',['Branch layout',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md10',1,'']]],
  ['broken_20design_29',['What we have today (the broken design)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md2',1,'']]],
  ['btc_20parity_20115_30',['Added — Bech32 Addresses + Full BTC Parity (115%)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md39',1,'']]],
  ['bug_20we_20just_20hit_202026_2004_2028_31',['The bug we just hit (2026-04-28)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md13',1,'']]],
  ['bug_20we_20re_20fixing_32',['THE BUG WE&apos;RE FIXING',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md73',1,'']]],
  ['build_20everything_33',['4. Build Everything',['../md__s_e_t_u_p.html#autotoc_md129',1,'']]],
  ['build_20fails_20with_20linking_20error_34',['&quot;Build fails with linking error&quot;',['../md__s_e_t_u_p.html#autotoc_md161',1,'']]],
  ['build_20rapid_35',['Build rapid',['../md__r_e_a_d_m_e.html#autotoc_md98',1,'']]],
  ['build_20run_36',['Build &amp;amp; Run',['../md__c_l_a_u_d_e.html#autotoc_md45',1,'']]],
  ['build_20test_37',['✅ Build &amp;amp; Test',['../md__s_e_t_u_p.html#autotoc_md122',1,'']]]
];
