var searchData=
[
  ['⚠️_0',['⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot;&gt;GitHub Releases&lt;/a&gt; page ⚠️',['../md_frontend_2node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['⚠️_20next_20versions_20change_20notes_20are_20available_20only_20on_20the_20github_20releases_20page_20⚠️_1',['⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot;&gt;GitHub Releases&lt;/a&gt; page ⚠️',['../md_frontend_2node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['⚠️_20notă_2',['⚠️ NOTĂ',['../md_archived-4-eterniti_2ai-opcode-research_21.html#autotoc_md27',1,'⚠️ NOTĂ'],['../md_archived-4-eterniti_2ai-opcode-research_2_o_p_c_o_d_e_s.html#autotoc_md132',1,'⚠️ NOTĂ'],['../md_archived-4-eterniti_2ai-opcode-research_2_o_p_c_o_d_e_s1.html#autotoc_md237',1,'⚠️ NOTĂ']]],
  ['⚠️_20observații_20importante_3a_3',['⚠️ Observații importante:',['../md_archived-4-eterniti_2docs-extra_2_t_o_o_l_s___s_t_a_t_u_s.html#autotoc_md616',1,'']]],
  ['⚠️_20troubleshooting_4',['⚠️ Troubleshooting',['../md_archived-4-eterniti_2docs-extra_2_g_e_n_e_s_i_s___l_a_u_n_c_h___g_u_i_d_e.html#autotoc_md486',1,'']]],
  ['⚠_20breaking_20changes_5',['⚠ BREAKING CHANGES',['../md_frontend_2node__modules_2chokidar_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html#autotoc_md5727',1,'⚠ BREAKING CHANGES'],['../md_frontend_2node__modules_2chokidar_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html#autotoc_md5730',1,'⚠ BREAKING CHANGES'],['../md_frontend_2node__modules_2chokidar_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html#autotoc_md5739',1,'⚠ BREAKING CHANGES'],['../md_frontend_2node__modules_2fast-glob_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html#autotoc_md6610',1,'⚠ BREAKING CHANGES'],['../md_frontend_2node__modules_2fast-glob_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html#autotoc_md6613',1,'⚠ BREAKING CHANGES'],['../md_frontend_2node__modules_2fast-glob_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html#autotoc_md6622',1,'⚠ BREAKING CHANGES']]]
];
