var searchData=
[
  ['c_20—_20design_20only_0',['PHASE C — DESIGN ONLY',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md81',1,'']]],
  ['cached_20balances_20to_20utxo_20source_20of_20truth_1',['Prompt for Kimi — Switch OmniBus L1 from RAM-cached balances to UTXO source-of-truth',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html',1,'']]],
  ['calendar_20solana_20poh_20style_2',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['calendar_20spark_20sub_20block_20consensus_3',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['ce_20este_4',['Ce este',['../md__r_e_a_d_m_e.html#autotoc_md96',1,'']]],
  ['chain_5',['What needs to become TX-on-chain',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md15',1,'']]],
  ['chain_20selection_20mainnet_20testnet_20regtest_6',['Added — Multi-chain Selection (Mainnet / Testnet / Regtest)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md33',1,'']]],
  ['chain_20selection_20was_20incomplete_20in_20v0_203_200_7',['Fixed — DB path wiring + chain selection (was incomplete in v0.3.0)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md27',1,'']]],
  ['chain_20tx_8',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['change_20must_20be_20a_20chain_20tx_9',['Architectural fix: every state change MUST be a chain TX',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html',1,'']]],
  ['changed_10',['Changed',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md40',1,'']]],
  ['changelog_11',['Changelog',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['claude_20md_12',['CLAUDE.md',['../md__c_l_a_u_d_e.html',1,'']]],
  ['clock_13',['3. Detalii tehnice per platform pentru clock',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md89',1,'']]],
  ['co_20authors_14',['Co-Authors',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md37',1,'']]],
  ['code_20relevant_20snippets_15',['EXISTING CODE (relevant snippets)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md69',1,'']]],
  ['coding_16',['Open questions to resolve before coding',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md9',1,'']]],
  ['command_20not_20found_3a_20zig_17',['&quot;Command not found: zig&quot;',['../md__s_e_t_u_p.html#autotoc_md160',1,'']]],
  ['commit_20history_20newest_20first_18',['Recent commit history (newest first)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md61',1,'']]],
  ['compatibility_19',['Compatibility',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md34',1,'']]],
  ['component_20sizes_20estimated_20',['Component sizes (estimated)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md4',1,'']]],
  ['components_20zig_20backend_21',['✅ Core Components (Zig Backend)',['../md__s_e_t_u_p.html#autotoc_md120',1,'']]],
  ['computed_20slot_20calendar_20solana_20poh_20style_22',['1. Pre-Computed Slot Calendar (Solana PoH-style)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md87',1,'']]],
  ['configuration_23',['✅ Configuration',['../md__s_e_t_u_p.html#autotoc_md123',1,'']]],
  ['consensus_24',['Next Session Plan — Slot Calendar + SPARK Sub-Block Consensus',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html',1,'']]],
  ['consensus_20viziunea_20ta_25',['2. SPARK Sub-Block Consensus (viziunea ta)',['../md__n_e_x_t___s_e_s_s_i_o_n___p_l_a_n.html#autotoc_md88',1,'']]],
  ['constraints_26',['OMNIBUS-SPECIFIC CONSTRAINTS',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md74',1,'']]],
  ['contained_27',['Each core/*.zig file is self-contained',['../md__c_l_a_u_d_e.html#autotoc_md51',1,'']]],
  ['context_28',['CONTEXT',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md57',1,'']]],
  ['context_29',['Ecosystem Context',['../md__c_l_a_u_d_e.html#autotoc_md54',1,'']]],
  ['contract_20target_30',['Crash-safety contract (target)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md6',1,'']]],
  ['core_20blockchain_20zig_20excerpts_31',['&lt;span class=&quot;tt&quot;&gt;core/blockchain.zig&lt;/span&gt; (excerpts)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md70',1,'']]],
  ['core_20components_20zig_20backend_32',['✅ Core Components (Zig Backend)',['../md__s_e_t_u_p.html#autotoc_md120',1,'']]],
  ['core_20layers_33',['Core Layers',['../md__c_l_a_u_d_e.html#autotoc_md49',1,'']]],
  ['core_20main_20zig_34',['Node Startup (core/main.zig)',['../md__c_l_a_u_d_e.html#autotoc_md48',1,'']]],
  ['core_20setup_20getting_20started_35',['OmniBus BlockChain Core - Setup &amp;amp; Getting Started',['../md__s_e_t_u_p.html',1,'']]],
  ['core_20utxo_20zig_20excerpts_20—_20already_20implemented_20currently_36',['&lt;span class=&quot;tt&quot;&gt;core/utxo.zig&lt;/span&gt; (excerpts — already implemented, currently',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md71',1,'']]],
  ['core_20zig_20file_20is_20self_20contained_37',['Each core/*.zig file is self-contained',['../md__c_l_a_u_d_e.html#autotoc_md51',1,'']]],
  ['crash_20safety_20contract_20target_38',['Crash-safety contract (target)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md6',1,'']]],
  ['created_39',['What Was Created',['../md__s_e_t_u_p.html#autotoc_md119',1,'']]],
  ['criteria_40',['Acceptance criteria',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md23',1,'']]],
  ['cryptographic_20stack_41',['Cryptographic stack',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md59',1,'']]],
  ['cu_20omnibussidebar_42',['Legătură cu OmnibusSidebar',['../md__r_e_a_d_m_e.html#autotoc_md116',1,'']]],
  ['curl_43',['Test RPC Endpoints (via curl)',['../md__s_e_t_u_p.html#autotoc_md138',1,'']]],
  ['current_20week_44',['Phase 1 Tasks (Current Week)',['../md__s_e_t_u_p.html#autotoc_md143',1,'']]],
  ['current_20working_45',['Architecture (current, working)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md58',1,'']]],
  ['currently_46',['&lt;span class=&quot;tt&quot;&gt;core/utxo.zig&lt;/span&gt; (excerpts — already implemented, currently',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md71',1,'']]],
  ['currently_20populated_20line_20numbers_20approximate_47',['Where UTXO is currently populated (line numbers approximate)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md72',1,'']]]
];
