var searchData=
[
  ['wallet_20—_205_20domenii_20post_20quantum_0',['Wallet — 5 Domenii Post-Quantum',['../md__r_e_a_d_m_e.html#autotoc_md104',1,'']]],
  ['want_20from_20you_1',['What I want from you',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md65',1,'']]],
  ['was_20created_2',['What Was Created',['../md__s_e_t_u_p.html#autotoc_md119',1,'']]],
  ['was_20incomplete_20in_20v0_203_200_3',['Fixed — DB path wiring + chain selection (was incomplete in v0.3.0)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md27',1,'']]],
  ['we_20do_20today_20interim_4',['What we do today (interim)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md24',1,'']]],
  ['we_20have_20today_20the_20broken_20design_5',['What we have today (the broken design)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md2',1,'']]],
  ['we_20just_20hit_202026_2004_2028_6',['The bug we just hit (2026-04-28)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md13',1,'']]],
  ['we_20move_20to_20bitcoin_20style_20omnibus_20tuned_7',['What we move to (Bitcoin-style, OmniBus-tuned)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md3',1,'']]],
  ['we_20re_20fixing_8',['THE BUG WE&apos;RE FIXING',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md73',1,'']]],
  ['week_9',['Phase 1 Tasks (Current Week)',['../md__s_e_t_u_p.html#autotoc_md143',1,'']]],
  ['week_202_10',['Phase 2 Tasks (Week 2)',['../md__s_e_t_u_p.html#autotoc_md144',1,'']]],
  ['week_203_11',['Phase 3 Tasks (Week 3)',['../md__s_e_t_u_p.html#autotoc_md145',1,'']]],
  ['week_204_12',['Phase 4 Tasks (Week 4)',['../md__s_e_t_u_p.html#autotoc_md146',1,'']]],
  ['week_205_13',['Phase 5 Tasks (Week 5)',['../md__s_e_t_u_p.html#autotoc_md147',1,'']]],
  ['what_20bitcoin_20actually_20does_14',['What Bitcoin actually does',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md1',1,'']]],
  ['what_20i_20want_20from_20you_15',['What I want from you',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md65',1,'']]],
  ['what_20needs_20to_20become_20tx_20on_20chain_16',['What needs to become TX-on-chain',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md15',1,'']]],
  ['what_20stays_20in_20memory_20legitimately_17',['What stays in memory (legitimately)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md16',1,'']]],
  ['what_20stays_20the_20same_18',['What stays the same',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md7',1,'']]],
  ['what_20to_20do_20next_19',['What to Do Next',['../md__s_e_t_u_p.html#autotoc_md142',1,'']]],
  ['what_20was_20created_20',['What Was Created',['../md__s_e_t_u_p.html#autotoc_md119',1,'']]],
  ['what_20we_20do_20today_20interim_21',['What we do today (interim)',['../md__a_r_c_h___f_i_x___t_x___o_n_l_y.html#autotoc_md24',1,'']]],
  ['what_20we_20have_20today_20the_20broken_20design_22',['What we have today (the broken design)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md2',1,'']]],
  ['what_20we_20move_20to_20bitcoin_20style_20omnibus_20tuned_23',['What we move to (Bitcoin-style, OmniBus-tuned)',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md3',1,'']]],
  ['what_20you_20give_20back_24',['DELIVERABLES (what you give back)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md82',1,'']]],
  ['where_20utxo_20is_20currently_20populated_20line_20numbers_20approximate_25',['Where UTXO is currently populated (line numbers approximate)',['../md__k_i_m_i___p_r_o_m_p_t___u_t_x_o.html#autotoc_md72',1,'']]],
  ['why_20this_20matters_26',['Why this matters',['../md__a_r_c_h___b_i_t_c_o_i_n___s_t_o_r_a_g_e.html#autotoc_md11',1,'']]],
  ['wiring_20chain_20selection_20was_20incomplete_20in_20v0_203_200_27',['Fixed — DB path wiring + chain selection (was incomplete in v0.3.0)',['../md__c_h_a_n_g_e_l_o_g.html#autotoc_md27',1,'']]],
  ['with_20linking_20error_28',['&quot;Build fails with linking error&quot;',['../md__s_e_t_u_p.html#autotoc_md161',1,'']]],
  ['won_20t_20load_29',['&quot;Frontend won&apos;t load&quot;',['../md__s_e_t_u_p.html#autotoc_md163',1,'']]],
  ['won_20t_20start_30',['&quot;RPC server won&apos;t start&quot;',['../md__s_e_t_u_p.html#autotoc_md162',1,'']]],
  ['workflow_31',['Git Workflow',['../md__c_l_a_u_d_e.html#autotoc_md53',1,'']]],
  ['working_32',['Architecture (current, working)',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md58',1,'']]],
  ['worst_20observed_20in_20a_20single_20run_33',['Best vs worst observed in a single run',['../md__k_i_m_i___p_r_o_m_p_t.html#autotoc_md63',1,'']]]
];
