var dir_5b91aa2fbd8a37e6cdf62b25d429303a =
[
    [ "AddressLabel.cpp", "_address_label_8cpp.html", null ],
    [ "AddressLabel.h", "_address_label_8h.html", "_address_label_8h" ],
    [ "BlockExplorerTab.cpp", "_block_explorer_tab_8cpp.html", null ],
    [ "BlockExplorerTab.h", "_block_explorer_tab_8h.html", "_block_explorer_tab_8h" ],
    [ "ConsoleTab.cpp", "_console_tab_8cpp.html", null ],
    [ "ConsoleTab.h", "_console_tab_8h.html", "_console_tab_8h" ],
    [ "ExchangeKeysTab.cpp", "_exchange_keys_tab_8cpp.html", null ],
    [ "ExchangeKeysTab.h", "_exchange_keys_tab_8h.html", "_exchange_keys_tab_8h" ],
    [ "MiningTab.cpp", "_mining_tab_8cpp.html", null ],
    [ "MiningTab.h", "_mining_tab_8h.html", "_mining_tab_8h" ],
    [ "MultiWalletTab.cpp", "_multi_wallet_tab_8cpp.html", null ],
    [ "MultiWalletTab.h", "_multi_wallet_tab_8h.html", "_multi_wallet_tab_8h" ],
    [ "NetworkTab.cpp", "_network_tab_8cpp.html", null ],
    [ "NetworkTab.h", "_network_tab_8h.html", "_network_tab_8h" ],
    [ "OverviewTab.cpp", "_overview_tab_8cpp.html", null ],
    [ "OverviewTab.h", "_overview_tab_8h.html", "_overview_tab_8h" ],
    [ "QRCodeWidget.cpp", "_q_r_code_widget_8cpp.html", "_q_r_code_widget_8cpp" ],
    [ "QRCodeWidget.h", "_q_r_code_widget_8h.html", "_q_r_code_widget_8h" ],
    [ "ReceiveTab.cpp", "_receive_tab_8cpp.html", null ],
    [ "ReceiveTab.h", "_receive_tab_8h.html", "_receive_tab_8h" ],
    [ "SendTab.cpp", "_send_tab_8cpp.html", null ],
    [ "SendTab.h", "_send_tab_8h.html", "_send_tab_8h" ],
    [ "StatusBar.cpp", "_status_bar_8cpp.html", null ],
    [ "StatusBar.h", "_status_bar_8h.html", "_status_bar_8h" ],
    [ "TransactionsTab.cpp", "_transactions_tab_8cpp.html", null ],
    [ "TransactionsTab.h", "_transactions_tab_8h.html", "_transactions_tab_8h" ]
];