var hierarchy =
[
    [ "omni::AdaVaultBridge", "classomni_1_1_ada_vault_bridge.html", null ],
    [ "http.server.BaseHTTPRequestHandler", null, [
      [ "metrics_exporter.MetricsHandler", "classmetrics__exporter_1_1_metrics_handler.html", null ]
    ] ],
    [ "metrics_exporter.BlockchainMetrics", "classmetrics__exporter_1_1_blockchain_metrics.html", null ],
    [ "omni::BlockData", "structomni_1_1_block_data.html", null ],
    [ "bridge_validator.BridgeTransaction", "classbridge__validator_1_1_bridge_transaction.html", null ],
    [ "bridge_validator.BridgeValidator", "classbridge__validator_1_1_bridge_validator.html", null ],
    [ "We-Are-Here-HodLum-WORKER.C", "class_we-_are-_here-_hod_lum-_w_o_r_k_e_r_1_1_c.html", null ],
    [ "omni::ChainAddress", "structomni_1_1_chain_address.html", null ],
    [ "omni::ChainDef", "structomni_1_1_chain_def.html", null ],
    [ "changelog_manager.Change", "classchangelog__manager_1_1_change.html", null ],
    [ "changelog_manager.ChangelogManager", "classchangelog__manager_1_1_changelog_manager.html", null ],
    [ "dependency_check.CheckResult", "classdependency__check_1_1_check_result.html", null ],
    [ "quick_check.CheckResult", "classquick__check_1_1_check_result.html", null ],
    [ "code_metrics.CodeAnalyzer", "classcode__metrics_1_1_code_analyzer.html", null ],
    [ "project_health.Colors", "classproject__health_1_1_colors.html", null ],
    [ "blockchain_vs_comparison.ComparisonFeature", "classblockchain__vs__comparison_1_1_comparison_feature.html", null ],
    [ "p2p-connection-flood.ConnectionTracker", "classp2p-connection-flood_1_1_connection_tracker.html", null ],
    [ "benchmark-consensus.ConsensusBenchmark", "classbenchmark-consensus_1_1_consensus_benchmark.html", null ],
    [ "scan_opcodes.Constant", "classscan__opcodes_1_1_constant.html", null ],
    [ "omni::WalletManager::CreateResult", "structomni_1_1_wallet_manager_1_1_create_result.html", null ],
    [ "crypto-audit.CryptoAuditor", "classcrypto-audit_1_1_crypto_auditor.html", null ],
    [ "blockchain_dependency_graph.CycleInfo", "classblockchain__dependency__graph_1_1_cycle_info.html", null ],
    [ "dependency_check.Dependency", "classdependency__check_1_1_dependency.html", null ],
    [ "dependency_check.DependencyChecker", "classdependency__check_1_1_dependency_checker.html", null ],
    [ "blockchain_deep_audit.DuplicateBlock", "classblockchain__deep__audit_1_1_duplicate_block.html", null ],
    [ "Enum", null, [
      [ "blockchain_analyzer.ModuleCategory", "classblockchain__analyzer_1_1_module_category.html", null ],
      [ "blockchain_analyzer.ModuleStatus", "classblockchain__analyzer_1_1_module_status.html", null ],
      [ "blockchain_analyzer.Severity", "classblockchain__analyzer_1_1_severity.html", null ],
      [ "blockchain_deep_audit.CWE", "classblockchain__deep__audit_1_1_c_w_e.html", null ],
      [ "blockchain_deep_audit.RiskLevel", "classblockchain__deep__audit_1_1_risk_level.html", null ],
      [ "blockchain_vs_comparison.FeatureStatus", "classblockchain__vs__comparison_1_1_feature_status.html", null ],
      [ "bridge_validator.ChainType", "classbridge__validator_1_1_chain_type.html", null ],
      [ "bridge_validator.TxStatus", "classbridge__validator_1_1_tx_status.html", null ],
      [ "oracle_verifier.DataStatus", "classoracle__verifier_1_1_data_status.html", null ],
      [ "oracle_verifier.OracleSource", "classoracle__verifier_1_1_oracle_source.html", null ],
      [ "vulnerability_scanner.Severity", "classvulnerability__scanner_1_1_severity.html", null ]
    ] ],
    [ "scan_opcodes.EnumDef", "classscan__opcodes_1_1_enum_def.html", null ],
    [ "scan_opcodes.EnumVariant", "classscan__opcodes_1_1_enum_variant.html", null ],
    [ "omni::crypto::ExtendedKey", "structomni_1_1crypto_1_1_extended_key.html", null ],
    [ "omni::FeeEstimate", "structomni_1_1_fee_estimate.html", null ],
    [ "code_metrics.FileMetrics", "classcode__metrics_1_1_file_metrics.html", null ],
    [ "blockchain_analyzer.Finding", "classblockchain__analyzer_1_1_finding.html", null ],
    [ "symbolic-exec-helper.Finding", "classsymbolic-exec-helper_1_1_finding.html", null ],
    [ "doc_generator.FunctionDoc", "classdoc__generator_1_1_function_doc.html", null ],
    [ "blockchain_deep_audit.FunctionInfo", "classblockchain__deep__audit_1_1_function_info.html", null ],
    [ "rop-gadget-scanner.GadgetScanner", "classrop-gadget-scanner_1_1_gadget_scanner.html", null ],
    [ "node-health-monitor.HealthMonitor", "classnode-health-monitor_1_1_health_monitor.html", null ],
    [ "project_health.HealthStatus", "classproject__health_1_1_health_status.html", null ],
    [ "tx-stress-sim2.LevelConfig", "classtx-stress-sim2_1_1_level_config.html", null ],
    [ "tx-stress-sim.LevelConfig", "classtx-stress-sim_1_1_level_config.html", null ],
    [ "log-aggregator.LogEntry", "classlog-aggregator_1_1_log_entry.html", null ],
    [ "scan_opcodes.MarkdownGenerator", "classscan__opcodes_1_1_markdown_generator.html", null ],
    [ "omni::MempoolStats", "structomni_1_1_mempool_stats.html", null ],
    [ "omni::MinerInfo", "structomni_1_1_miner_info.html", null ],
    [ "blockchain_deep_audit.ModuleDeepResult", "classblockchain__deep__audit_1_1_module_deep_result.html", null ],
    [ "doc_generator.ModuleDoc", "classdoc__generator_1_1_module_doc.html", null ],
    [ "blockchain_dependency_graph.ModuleNode", "classblockchain__dependency__graph_1_1_module_node.html", null ],
    [ "blockchain_analyzer.ModuleResult", "classblockchain__analyzer_1_1_module_result.html", null ],
    [ "omni::MultiChainWallet", "classomni_1_1_multi_chain_wallet.html", null ],
    [ "omni::NetworkInfo", "structomni_1_1_network_info.html", null ],
    [ "historical-attack-replayer.NodeRPC", "classhistorical-attack-replayer_1_1_node_r_p_c.html", null ],
    [ "franchise_client.OmniBusClient", "classfranchise__client_1_1_omni_bus_client.html", null ],
    [ "replay-protection-tester.OmnibusRPC", "classreplay-protection-tester_1_1_omnibus_r_p_c.html", null ],
    [ "scan_opcodes.OpcodeScanner", "classscan__opcodes_1_1_opcode_scanner.html", null ],
    [ "scan_opcodes.OpcodeScanResult", "classscan__opcodes_1_1_opcode_scan_result.html", null ],
    [ "oracle_verifier.OracleVerifier", "classoracle__verifier_1_1_oracle_verifier.html", null ],
    [ "p2p-attack-simulator.P2PAttackSimulator", "classp2p-attack-simulator_1_1_p2_p_attack_simulator.html", null ],
    [ "p2p-test-harness.P2PTestHarness", "classp2p-test-harness_1_1_p2_p_test_harness.html", null ],
    [ "omni::PeerInfo", "structomni_1_1_peer_info.html", null ],
    [ "oracle_verifier.PriceData", "classoracle__verifier_1_1_price_data.html", null ],
    [ "prompt_generator.ProjectContext", "classprompt__generator_1_1_project_context.html", null ],
    [ "code_metrics.ProjectMetrics", "classcode__metrics_1_1_project_metrics.html", null ],
    [ "prompt_generator.PromptGenerator", "classprompt__generator_1_1_prompt_generator.html", null ],
    [ "QAbstractTableModel", null, [
      [ "omni::BlockTableModel", "classomni_1_1_block_table_model.html", null ],
      [ "omni::MempoolTableModel", "classomni_1_1_mempool_table_model.html", null ],
      [ "omni::MinerTableModel", "classomni_1_1_miner_table_model.html", null ],
      [ "omni::PeerTableModel", "classomni_1_1_peer_table_model.html", null ],
      [ "omni::TransactionTableModel", "classomni_1_1_transaction_table_model.html", null ]
    ] ],
    [ "QDialog", null, [
      [ "omni::AboutDialog", "classomni_1_1_about_dialog.html", null ],
      [ "omni::ConfirmSendDialog", "classomni_1_1_confirm_send_dialog.html", null ],
      [ "omni::CreateWalletDialog", "classomni_1_1_create_wallet_dialog.html", null ],
      [ "omni::ImportWalletDialog", "classomni_1_1_import_wallet_dialog.html", null ],
      [ "omni::SettingsDialog", "classomni_1_1_settings_dialog.html", null ],
      [ "omni::UnlockDialog", "classomni_1_1_unlock_dialog.html", null ],
      [ "omni::WelcomeDialog", "classomni_1_1_welcome_dialog.html", null ]
    ] ],
    [ "QLabel", null, [
      [ "omni::AddressLabel", "classomni_1_1_address_label.html", null ]
    ] ],
    [ "QMainWindow", null, [
      [ "omni::MainWindow", "classomni_1_1_main_window.html", null ]
    ] ],
    [ "QObject", null, [
      [ "omni::NodeService", "classomni_1_1_node_service.html", null ],
      [ "omni::RpcClient", "classomni_1_1_rpc_client.html", null ],
      [ "omni::WalletManager", "classomni_1_1_wallet_manager.html", null ],
      [ "omni::WebSocketClient", "classomni_1_1_web_socket_client.html", null ]
    ] ],
    [ "omni::qr::QRMatrix", "structomni_1_1qr_1_1_q_r_matrix.html", null ],
    [ "QStatusBar", null, [
      [ "omni::StatusBar", "classomni_1_1_status_bar.html", null ]
    ] ],
    [ "QSystemTrayIcon", null, [
      [ "omni::TrayIcon", "classomni_1_1_tray_icon.html", null ]
    ] ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni10ConsoleTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni10_console_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni10MainWindowE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni10_main_window_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni10NetworkTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni10_network_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni10ReceiveTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni10_receive_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni11AboutDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni11_about_dialog_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni11NodeServiceE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni11_node_service_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni11OverviewTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni11_overview_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni12AddressLabelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni12_address_label_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni12QRCodeWidgetE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni12_q_r_code_widget_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni12UnlockDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni12_unlock_dialog_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni13ExchangePanelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni13_exchange_panel_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni13WalletManagerE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni13_wallet_manager_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni13WelcomeDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni13_welcome_dialog_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni14MultiWalletTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni14_multi_wallet_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni14PeerTableModelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni14_peer_table_model_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni14SettingsDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni14_settings_dialog_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni15BlockTableModelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni15_block_table_model_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni15MinerTableModelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni15_miner_table_model_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni15TransactionsTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni15_transactions_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni15WebSocketClientE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni15_web_socket_client_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni16BlockExplorerTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni16_block_explorer_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni17ConfirmSendDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni17_confirm_send_dialog_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni17MempoolTableModelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni17_mempool_table_model_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni18CreateWalletDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni18_create_wallet_dialog_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni18ImportWalletDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni18_import_wallet_dialog_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni21TransactionTableModelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni21_transaction_table_model_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni7SendTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni7_send_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni8TrayIconE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni8_tray_icon_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni9MiningTabE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni9_mining_tab_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni9RpcClientE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni9_rpc_client_e__t.html", null ],
    [ "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN4omni9StatusBarE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n4omni9_status_bar_e__t.html", null ],
    [ "quick_check.QuickChecker", "classquick__check_1_1_quick_checker.html", null ],
    [ "QWidget", null, [
      [ "omni::BlockExplorerTab", "classomni_1_1_block_explorer_tab.html", null ],
      [ "omni::ConsoleTab", "classomni_1_1_console_tab.html", null ],
      [ "omni::ExchangeKeysTab", "classomni_1_1_exchange_keys_tab.html", null ],
      [ "omni::ExchangePanel", "classomni_1_1_exchange_panel.html", null ],
      [ "omni::MiningTab", "classomni_1_1_mining_tab.html", null ],
      [ "omni::MultiWalletTab", "classomni_1_1_multi_wallet_tab.html", null ],
      [ "omni::NetworkTab", "classomni_1_1_network_tab.html", null ],
      [ "omni::OverviewTab", "classomni_1_1_overview_tab.html", null ],
      [ "omni::QRCodeWidget", "classomni_1_1_q_r_code_widget.html", null ],
      [ "omni::ReceiveTab", "classomni_1_1_receive_tab.html", null ],
      [ "omni::SendTab", "classomni_1_1_send_tab.html", null ],
      [ "omni::TransactionsTab", "classomni_1_1_transactions_tab.html", null ]
    ] ],
    [ "changelog_manager.Release", "classchangelog__manager_1_1_release.html", null ],
    [ "buffer-overflow-tester.RPCClient", "classbuffer-overflow-tester_1_1_r_p_c_client.html", null ],
    [ "rpc-tester.RPCTester", "classrpc-tester_1_1_r_p_c_tester.html", null ],
    [ "blockchain_deep_audit.SecurityFinding", "classblockchain__deep__audit_1_1_security_finding.html", null ],
    [ "security_scan.SecurityIssue", "classsecurity__scan_1_1_security_issue.html", null ],
    [ "security_scan.SecurityScanner", "classsecurity__scan_1_1_security_scanner.html", null ],
    [ "omni::Settings", "classomni_1_1_settings.html", null ],
    [ "network-partition-sim.SimNode", "classnetwork-partition-sim_1_1_sim_node.html", null ],
    [ "property-based-crypto.Stats", "classproperty-based-crypto_1_1_stats.html", null ],
    [ "tx-stress-sim2.Stats", "classtx-stress-sim2_1_1_stats.html", null ],
    [ "tx-stress-sim.Stats", "classtx-stress-sim_1_1_stats.html", null ],
    [ "tx-flood-stress.StressResults", "classtx-flood-stress_1_1_stress_results.html", null ],
    [ "doc_generator.StructDoc", "classdoc__generator_1_1_struct_doc.html", null ],
    [ "test_runner.TestGroup", "classtest__runner_1_1_test_group.html", null ],
    [ "memory-pressure-test.TestResult", "classmemory-pressure-test_1_1_test_result.html", null ],
    [ "test_runner.TestResult", "classtest__runner_1_1_test_result.html", null ],
    [ "test_runner.TestRunner", "classtest__runner_1_1_test_runner.html", null ],
    [ "test_runner.TestSuiteResult", "classtest__runner_1_1_test_suite_result.html", null ],
    [ "todo_extractor.TodoExtractor", "classtodo__extractor_1_1_todo_extractor.html", null ],
    [ "todo_extractor.TodoItem", "classtodo__extractor_1_1_todo_item.html", null ],
    [ "config_validator.TomlValidator", "classconfig__validator_1_1_toml_validator.html", null ],
    [ "omni::TransactionData", "structomni_1_1_transaction_data.html", null ],
    [ "config_validator.ValidationError", "classconfig__validator_1_1_validation_error.html", null ],
    [ "omni::VaultKeyEntry", "structomni_1_1_vault_key_entry.html", null ],
    [ "omni::VaultStorage", "classomni_1_1_vault_storage.html", null ],
    [ "oracle_verifier.VerificationResult", "classoracle__verifier_1_1_verification_result.html", null ],
    [ "vulnerability_scanner.Vulnerability", "classvulnerability__scanner_1_1_vulnerability.html", null ],
    [ "omni::WalletAddress", "structomni_1_1_wallet_address.html", null ],
    [ "omni::WalletInfo", "structomni_1_1_wallet_info.html", null ],
    [ "omni::WalletMeta", "structomni_1_1_wallet_meta.html", null ],
    [ "ws-monitor.WSMonitor", "classws-monitor_1_1_w_s_monitor.html", null ],
    [ "scan_opcodes.ZigParser", "classscan__opcodes_1_1_zig_parser.html", null ]
];