#!/usr/bin/env python3
"""circuit_10h_v2.py — improved 10h circuit with full 200-address pool.

Loads addresses_pool.json (100 ECDSA + 100 Quantum) generated by
`generate_addresses_pool.py`. Distributes traffic uniformly across all 200
addresses so Rich List shows real distribution, not just 10 ECDSA hot spots.

Differences vs v1:
  - Full pool of 100 ECDSA + 100 Quantum (uniform random pick)
  - Larger amounts: 0.001 - 0.5 OMNI (1M - 500M SAT) instead of dust
  - NS register uses fully random target from the pool
  - Reports show coverage: how many distinct addresses funded so far
"""
import json, os, sys, time, random, urllib.request, urllib.error
from datetime import datetime, timedelta

RPC_URL = os.environ.get("OMNIBUS_RPC_URL", "https://omnibusblockchain.cc:8443/api-testnet")
TOKEN = os.environ.get("OMNIBUS_RPC_TOKEN", "")

DURATION_H = float(sys.argv[1]) if len(sys.argv) > 1 else 10.0
BURST_SIZE = int(sys.argv[2]) if len(sys.argv) > 2 else 5
DELAY_S = float(sys.argv[3]) if len(sys.argv) > 3 else 1.8

NS_WORDS = [
    "alpha","beta","gamma","delta","echo","foxtrot","golf","hotel",
    "india","juliet","kilo","lima","mike","november","oscar","papa",
    "quebec","romeo","sierra","tango","uniform","victor","whiskey","xray",
    "yankee","zulu","neon","vortex","zenith","quasar","nexus","aegis",
    "blaze","comet","drift","ember","flux","gleam","halo","ivory",
    "jade","krypton","lunar","mirage","nova","onyx","prism","quartz",
    "raven","spark","tide","umbra","vapor","wave","xenon","yarn","zest",
]


def gen_ns_name():
    w1 = random.choice(NS_WORDS)
    w2 = random.choice(NS_WORDS)
    n = random.randint(10, 99999)
    return f"{w1}{w2}{n}"


def rpc(method, params, retries=3, timeout=10):
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params}).encode()
    headers = {"Content-Type": "application/json"}
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    last_err = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(RPC_URL, method="POST", headers=headers, data=body)
            return json.loads(urllib.request.urlopen(req, timeout=timeout).read().decode())
        except (urllib.error.URLError, ConnectionRefusedError, TimeoutError) as e:
            last_err = e
            if attempt < retries - 1:
                time.sleep(3)
    raise last_err


def main():
    pool_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "addresses_pool.json")
    if not os.path.exists(pool_path):
        print(f"FATAL: {pool_path} missing. Run generate_addresses_pool.py first.")
        return
    with open(pool_path, "r", encoding="utf-8") as f:
        pool = json.load(f)

    ECDSA = [a["address"] for a in pool["ecdsa"]]
    QUANTUM = [a["address"] for a in pool["quantum"]]
    ALL = ECDSA + QUANTUM
    print(f"[POOL] {len(ECDSA)} ECDSA + {len(QUANTUM)} Quantum = {len(ALL)} addresses loaded")

    # Quantum breakdown by prefix
    qbp = {}
    for q in pool["quantum"]:
        qbp[q["prefix"]] = qbp.get(q["prefix"], 0) + 1
    print(f"[POOL] Quantum breakdown: {qbp}")

    start = datetime.now()
    end = start + timedelta(hours=DURATION_H)
    target_total = int(DURATION_H * 3600 / DELAY_S * BURST_SIZE)

    try:
        s = rpc("getstatus", [])["result"]
    except Exception as e:
        print(f"FATAL: cannot reach VPS RPC: {e}")
        return

    print()
    print("=" * 70)
    print(f"  CIRCUIT 10h v2 - OmniBus testnet (full 200-address pool)")
    print(f"  Started:   {start:%Y-%m-%d %H:%M:%S}")
    print(f"  Will end:  {end:%Y-%m-%d %H:%M:%S}  (in {DURATION_H}h)")
    print(f"  Pacing:    {BURST_SIZE} TX/burst every {DELAY_S}s ~= {BURST_SIZE/DELAY_S:.2f} TX/s")
    print(f"  Target:    ~{target_total:,} TXs total")
    print(f"  Mix:       70% ECDSA  /  25% Quantum (4 prefixes)  /  5% NS register")
    print(f"  Amounts:   1M - 500M SAT (0.001 - 0.5 OMNI)")
    print(f"  Start:     block={s['blockCount']:,}  bal={s['balance']/1e9:.4f} OMNI")
    print(f"  RPC:       {RPC_URL}")
    print("=" * 70)
    print()

    counts = {"ecdsa_ok":0,"ecdsa_fail":0,"quantum_ok":0,"quantum_fail":0,"ns_ok":0,"ns_fail":0}
    quantum_by_prefix = {p: 0 for p in qbp.keys()}
    funded_addrs = set()
    ns_registered_recent = []
    last_report = time.time()

    try:
        while datetime.now() < end:
            for _ in range(BURST_SIZE):
                r_action = random.random()
                try:
                    if r_action < 0.05:
                        # NS register — pick random address from the pool
                        target = random.choice(ALL)
                        name = gen_ns_name()
                        r = rpc("registername", [name, target])
                        if r.get("error"):
                            raise Exception(r["error"]["message"])
                        counts["ns_ok"] += 1
                        kind = "ECDSA" if target.startswith("ob1q") else "Quantum"
                        if len(ns_registered_recent) >= 30:
                            ns_registered_recent.pop(0)
                        ns_registered_recent.append((name, kind, target[-12:]))
                    elif r_action < 0.30:
                        # Quantum send
                        dst = random.choice(QUANTUM)
                        amount = random.randint(1_000_000, 500_000_000)  # 0.001 - 0.5 OMNI
                        r = rpc("sendtransaction", [dst, amount])
                        if r.get("error"):
                            raise Exception(r["error"]["message"])
                        counts["quantum_ok"] += 1
                        funded_addrs.add(dst)
                        prefix = dst[:5]
                        quantum_by_prefix[prefix] = quantum_by_prefix.get(prefix, 0) + 1
                    else:
                        # ECDSA send
                        dst = random.choice(ECDSA)
                        amount = random.randint(1_000_000, 500_000_000)
                        r = rpc("sendtransaction", [dst, amount])
                        if r.get("error"):
                            raise Exception(r["error"]["message"])
                        counts["ecdsa_ok"] += 1
                        funded_addrs.add(dst)
                except Exception as e:
                    if r_action < 0.05: counts["ns_fail"] += 1
                    elif r_action < 0.30: counts["quantum_fail"] += 1
                    else: counts["ecdsa_fail"] += 1

            now = time.time()
            if now - last_report >= 300:  # every 5 min
                last_report = now
                elapsed = datetime.now() - start
                total_ok = counts["ecdsa_ok"] + counts["quantum_ok"] + counts["ns_ok"]
                total_fail = counts["ecdsa_fail"] + counts["quantum_fail"] + counts["ns_fail"]
                try:
                    s = rpc("getstatus", [])["result"]
                    block, mempool, bal = s["blockCount"], s["mempoolSize"], s["balance"]/1e9
                except Exception:
                    block = mempool = bal = -1
                print(f"[{datetime.now():%H:%M:%S} | +{elapsed}] "
                      f"OK={total_ok:,} FAIL={total_fail} | "
                      f"ECDSA={counts['ecdsa_ok']:,} Quantum={counts['quantum_ok']:,} NS={counts['ns_ok']:,} | "
                      f"funded={len(funded_addrs)}/{len(ALL)} | "
                      f"block={block:,} mempool={mempool}")
                qb = " ".join(f"{p[:-1]}={c}" for p, c in quantum_by_prefix.items())
                print(f"    Quantum: {qb}")
                if ns_registered_recent:
                    n = ns_registered_recent[-1]
                    print(f"    Last NS: {n[0]}.omnibus -> {n[1]} ...{n[2]}")
                sys.stdout.flush()

            time.sleep(DELAY_S)
    except KeyboardInterrupt:
        print("\n[INTERRUPT] Stopping...")

    # Final report
    elapsed = datetime.now() - start
    total_ok = counts["ecdsa_ok"] + counts["quantum_ok"] + counts["ns_ok"]
    total_fail = counts["ecdsa_fail"] + counts["quantum_fail"] + counts["ns_fail"]

    print()
    print("=" * 70)
    print(f"  FINAL REPORT")
    print(f"  Ran for:        {elapsed} (target {DURATION_H}h)")
    print(f"  Total accepted: {total_ok:,}")
    print(f"  Total failed:   {total_fail:,}")
    rate = total_ok / max(total_ok+total_fail, 1) * 100
    print(f"  Success rate:   {rate:.1f}%")
    print(f"  Coverage:       {len(funded_addrs)}/{len(ALL)} addresses funded")
    print()
    print(f"  ECDSA sends:    {counts['ecdsa_ok']:,} ok  /  {counts['ecdsa_fail']} fail")
    print(f"  Quantum sends:  {counts['quantum_ok']:,} ok  /  {counts['quantum_fail']} fail")
    for p, c in quantum_by_prefix.items():
        print(f"     {p:<8} {c:,}")
    print(f"  NS registers:   {counts['ns_ok']:,} ok  /  {counts['ns_fail']} fail")
    if ns_registered_recent:
        print(f"\n  Last 10 NS registrations:")
        for name, kind, addr in ns_registered_recent[-10:]:
            print(f"    {name:<24}.omnibus  ({kind:<7}) -> ...{addr}")
    try:
        s = rpc("getstatus", [])["result"]
        print(f"\n  Final chain: block={s['blockCount']:,} bal={s['balance']/1e9:.4f}")
    except Exception:
        pass
    print("=" * 70)


if __name__ == "__main__":
    main()
