#!/usr/bin/env python3
"""
run.py — top-level CLI for the PQC quality scanner.

Phases:
  --generate   — invoke node generator to produce <algo>_signatures.bin files
  --scan       — run all statistical tests on cached files, write metrics.json
  --report PATH — render a human-readable Markdown report from the metrics
  --full       — generate + scan + report (one shot)

Sample:
  python run.py --full --report ../../STATUS/PQC_QUALITY_$(date +%F).md
"""
from __future__ import annotations
import argparse
import json
import os
import subprocess
import sys
from datetime import date
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPORTS    = SCRIPT_DIR / "reports"
GENERATOR  = SCRIPT_DIR / "algorithms" / "generate_signatures.mjs"
FRONTEND   = SCRIPT_DIR.parent.parent / "frontend"

# Ensure local modules import
sys.path.insert(0, str(SCRIPT_DIR))

from tests import entropy, avalanche, periodicity, nist_sp800_22  # noqa: E402

ALGOS = ["ml_dsa_87", "falcon_512", "dilithium_5", "slh_dsa_256s",
         "aes256ctr", "xor_weak"]


# ── Phases ────────────────────────────────────────────────────────────────

def phase_generate(count: int) -> int:
    """Invoke the JS generator from frontend/ so node_modules resolve.
    Node only resolves @noble/post-quantum when the script LIVES inside
    a folder that has node_modules in its tree, so we copy the generator
    into frontend/ temporarily and run from there."""
    import shutil
    REPORTS.mkdir(parents=True, exist_ok=True)
    if not FRONTEND.exists():
        print(f"ERROR: frontend dir not found at {FRONTEND}", file=sys.stderr)
        return 1
    tmp_script = FRONTEND / "_pqc_scanner_tmp.mjs"
    shutil.copy(str(GENERATOR), str(tmp_script))
    try:
        cmd = ["node", str(tmp_script.name), "--out", str(REPORTS), "--count", str(count)]
        print(f"$ (cd frontend && {' '.join(cmd)})")
        proc = subprocess.run(cmd, cwd=str(FRONTEND))
        return proc.returncode
    finally:
        try:
            tmp_script.unlink()
        except OSError:
            pass


def phase_scan() -> dict:
    """Read each <algo>_signatures.bin + <algo>_avalanche.bin, run all tests."""
    results: dict = {}
    for algo in ALGOS:
        sig_path = REPORTS / f"{algo}_signatures.bin"
        if not sig_path.exists():
            print(f"  [skip] {algo}: {sig_path.name} not found")
            continue
        sigs = sig_path.read_bytes()
        meta_path = REPORTS / f"{algo}_meta.json"
        meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}

        print(f"  [scan] {algo:<14} {len(sigs):>8} bytes")

        ent_score = entropy.shannon_entropy(sigs)
        chi2      = entropy.chi_square_uniformity(sigs)
        per_4     = periodicity.find_repeats(sigs, window=4)
        per_8     = periodicity.find_repeats(sigs, window=8)
        nist      = nist_sp800_22.run_all(sigs)

        # Avalanche needs the pair file
        ava_path = REPORTS / f"{algo}_avalanche.bin"
        ava_metrics = None
        if ava_path.exists() and meta.get("sig_len"):
            ava_bytes = ava_path.read_bytes()
            sig_len   = meta["sig_len"]
            pairs_n   = len(ava_bytes) // (2 * sig_len)
            pairs = []
            for i in range(pairs_n):
                a = ava_bytes[2 * i * sig_len:(2 * i + 1) * sig_len]
                b = ava_bytes[(2 * i + 1) * sig_len:(2 * i + 2) * sig_len]
                pairs.append((a, b))
            ava_metrics = avalanche.avalanche_score(pairs)

        results[algo] = {
            "meta": meta,
            "entropy_bits_per_byte": ent_score,
            "entropy_verdict": entropy.verdict(ent_score, chi2),
            "chi2": chi2,
            "periodicity_w4": per_4,
            "periodicity_w8": per_8,
            "periodicity_verdict": periodicity.verdict(per_4),
            "nist_sp800_22": nist,
            "nist_verdict": nist_sp800_22.verdict(nist),
            "avalanche": ava_metrics,
            "avalanche_verdict": avalanche.verdict(
                ava_metrics["mean_pct"], ava_metrics["std_pct"]
            ) if ava_metrics else ("[N/A]", "no_pairs"),
        }

    metrics_path = REPORTS / "metrics.json"
    metrics_path.write_text(json.dumps(results, indent=2))
    print(f"\n✓ Wrote: {metrics_path}")
    return results


# ── Report rendering ──────────────────────────────────────────────────────

def render_report(results: dict, out_path: Path) -> None:
    today = date.today().isoformat()
    lines: list[str] = []
    lines.append(f"# PQC Quality Scanner Report — {today}")
    lines.append("")
    lines.append("Auto-generated by `tools/pqc-quality-scanner/run.py`. ")
    lines.append("Source signatures produced by `@noble/post-quantum` (FIPS 204/205/206).")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Algorithm | Entropy | NIST SP800-22 | Avalanche | Periodicity | Overall |")
    lines.append("|---|---|---|---|---|---|")

    canon_set = {"ml_dsa_87", "falcon_512", "dilithium_5", "slh_dsa_256s"}
    for algo in ALGOS:
        r = results.get(algo)
        if not r:
            continue
        ent_s, ent_l = r["entropy_verdict"]
        nis_s, nis_l = r["nist_verdict"]
        ava_s, ava_l = r["avalanche_verdict"]
        per_s, per_l = r["periodicity_verdict"]
        ent_val = f"{r['entropy_bits_per_byte']:.4f}"
        ava_val = f"{r['avalanche']['mean_pct']:.2f}%" if r.get("avalanche") else "n/a"
        # Overall: pass if all 4 are PASS or OK
        ok = all(s in ("[PASS]", "[OK]") for s in (ent_s, nis_s, ava_s, per_s))
        marker = " ← **canon**" if algo in canon_set else " (reference)"
        lines.append(f"| `{algo}`{marker} | {ent_s} {ent_val} | {nis_s} {nis_l} | "
                     f"{ava_s} {ava_val} | {per_s} | {'PASS' if ok else 'CHECK'} |")
    lines.append("")

    lines.append("## Pass thresholds")
    lines.append("")
    lines.append("- **Entropy:** ≥ 7.99 bits/byte for PASS, ≥ 7.90 for OK.")
    lines.append("- **NIST SP800-22:** all 6 implemented tests p ≥ 0.01.")
    lines.append("- **Avalanche:** mean ∈ [49,51]% strict, ∈ [47,53]% acceptable.")
    lines.append("- **Periodicity (window=4 bytes):** ratio < 2 vs birthday expectation.")
    lines.append("")

    # Per-algorithm detail
    for algo in ALGOS:
        r = results.get(algo)
        if not r:
            continue
        lines.append(f"## {algo}")
        lines.append("")
        meta = r.get("meta", {})
        if meta:
            lines.append(f"- Samples: {meta.get('count', '?')} signatures × "
                         f"{meta.get('sig_len', '?')} bytes = "
                         f"**{meta.get('count', 0) * meta.get('sig_len', 0)}** bytes scanned")
        lines.append(f"- Entropy: **{r['entropy_bits_per_byte']:.4f}** bits/byte "
                     f"(chi² = {r['chi2']:.1f}) → {r['entropy_verdict'][0]} {r['entropy_verdict'][1]}")
        nist = r["nist_sp800_22"]
        lines.append(f"- NIST SP800-22: **{nist['passed']}/{nist['total']}** passed")
        for tname, p in nist["p_values"].items():
            check = "✅" if p >= 0.01 else "❌"
            lines.append(f"   - {check} `{tname}` — p = {p:.4f}")
        if r.get("avalanche"):
            a = r["avalanche"]
            lines.append(f"- Avalanche: mean = **{a['mean_pct']:.2f}%** "
                         f"(σ = {a['std_pct']:.2f}, range {a['min_pct']:.1f}–{a['max_pct']:.1f}, "
                         f"{a['samples']} pairs) → {r['avalanche_verdict'][0]} {r['avalanche_verdict'][1]}")
        per = r["periodicity_w4"]
        lines.append(f"- Periodicity (w=4): {per['duplicates']} duplicates / "
                     f"{per['expected']:.1f} expected → ratio {per['ratio']:.2f} → "
                     f"{r['periodicity_verdict'][0]} {r['periodicity_verdict'][1]}")
        lines.append("")

    lines.append("## What this proves")
    lines.append("")
    lines.append("- Signatures from the canonical OmniBus set produce output **statistically "
                 "indistinguishable from random** — high entropy, no detectable periodicity, "
                 "uniform bit-flip propagation.")
    lines.append("- The `xor_weak` reference is intentionally bad; if it does NOT fail, the "
                 "scanner itself has a bug.")
    lines.append("- The `aes256ctr` reference is a known good cryptographic stream — every "
                 "PQ algorithm should match or exceed its scores.")
    lines.append("")
    lines.append("## Caveats")
    lines.append("")
    lines.append("- Statistical tests verify *output looks random*, not that the math is "
                 "uncrackable. NIST FIPS provides the security argument; this scanner provides "
                 "the empirical witness.")
    lines.append("- 6 of 15 NIST SP800-22 tests implemented. Adding the remaining 9 (universal "
                 "statistical, linear complexity, random excursions, etc.) is on the roadmap.")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--generate", action="store_true",
                    help="Run JS generator to produce signature files")
    ap.add_argument("--scan", action="store_true",
                    help="Run statistical tests on cached files")
    ap.add_argument("--full", action="store_true",
                    help="--generate + --scan + --report (default path)")
    ap.add_argument("--count", type=int, default=200,
                    help="Number of signatures per algorithm (default: 200)")
    ap.add_argument("--report", type=str, default=None,
                    help="Write Markdown report to this path")
    args = ap.parse_args()

    if args.full:
        args.generate = True
        args.scan = True
        if args.report is None:
            default = SCRIPT_DIR.parent.parent / "STATUS" / f"PQC_QUALITY_{date.today().isoformat()}.md"
            args.report = str(default)

    if args.generate:
        rc = phase_generate(args.count)
        if rc != 0:
            print(f"\nGeneration failed (exit {rc})", file=sys.stderr)
            return rc

    results = {}
    if args.scan:
        print("\n=== Scan ===")
        results = phase_scan()

    if args.report:
        if not results:
            metrics = REPORTS / "metrics.json"
            if metrics.exists():
                results = json.loads(metrics.read_text())
            else:
                print("No metrics yet — run --scan first or use --full.", file=sys.stderr)
                return 1
        out = Path(args.report)
        render_report(results, out)
        print(f"\n✓ Report: {out}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
