#!/usr/bin/env python3
"""
consolidate-status.py — Walk all .md files, extract TODO/DONE/BLOCKED items
and section headings, and consolidate into a single STATUS.md.

WHY
---
After many sessions, status of the project is fragmented across N markdown
files. This script reads them all, pulls out the actionable items (open
checkboxes, completed checkboxes, BLOCKED markers, NEXT steps), tags each
with source file + line, and writes one normalized status doc.

EXTRACTED ITEMS
---------------
- `- [ ] TODO_ITEM`   → TODO
- `- [x] DONE_ITEM`   → DONE
- `BLOCKED:`/`STUCK:` → BLOCKED
- `NEXT:`/`TODO:` headings → upcoming work
- Lines containing `❌`, `🔴`, `WIP`, `IN PROGRESS` → in progress

USAGE
-----
    python tools/consolidate-status.py
    python tools/consolidate-status.py --output STATUS/STATUS.md
    python tools/consolidate-status.py --include-archive   # also scan archiveREADME/
"""

from __future__ import annotations
import argparse
import os
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import date
from pathlib import Path
import sys

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

SKIP_DIRS_DEFAULT = {
    "node_modules", "zig-out", ".zig-cache", "zig-cache", ".cache",
    "archived-4-eterniti", "8_JUNK", "html", "latex", "dist",
    ".git", "data", "backups",
}

TODO_RE     = re.compile(r"^\s*[-*]\s*\[\s\]\s*(.+)$")
DONE_RE     = re.compile(r"^\s*[-*]\s*\[[xX]\]\s*(.+)$")
BLOCKED_RE  = re.compile(r"\b(BLOCKED|STUCK|FIXME|FAIL(?:ED)?|❌)\b", re.I)
WIP_RE      = re.compile(r"\b(WIP|IN[- ]PROGRESS|🔴|🟡)\b", re.I)
NEXT_HDR_RE = re.compile(r"^#{1,3}\s*(NEXT|TODO|REMAINING|UPCOMING)\b", re.I)

@dataclass
class Item:
    kind: str      # TODO / DONE / BLOCKED / WIP
    text: str
    source: str    # relative path
    line: int


def scan(repo_root: Path, include_archive: bool) -> list[Item]:
    skip = set(SKIP_DIRS_DEFAULT)
    if not include_archive:
        skip.add("archiveREADME")
    items: list[Item] = []
    for dirpath, dirnames, filenames in os.walk(repo_root):
        dirnames[:] = [d for d in dirnames if d not in skip and not d.startswith(".")]
        for name in filenames:
            if not name.lower().endswith(".md"):
                continue
            p = Path(dirpath) / name
            rel = str(p.relative_to(repo_root)).replace("\\", "/")
            try:
                lines = p.read_text(encoding="utf-8", errors="replace").splitlines()
            except OSError:
                continue
            in_next_section = False
            for i, line in enumerate(lines, start=1):
                if NEXT_HDR_RE.match(line):
                    in_next_section = True
                    continue
                if line.startswith("#"):
                    in_next_section = False

                m = TODO_RE.match(line)
                if m:
                    items.append(Item("TODO", m.group(1).strip(), rel, i))
                    continue
                m = DONE_RE.match(line)
                if m:
                    items.append(Item("DONE", m.group(1).strip(), rel, i))
                    continue

                if BLOCKED_RE.search(line) and not line.startswith("#"):
                    items.append(Item("BLOCKED", line.strip()[:200], rel, i))
                    continue
                if WIP_RE.search(line) and not line.startswith("#"):
                    items.append(Item("WIP", line.strip()[:200], rel, i))
                    continue
                if in_next_section and line.strip() and not line.startswith("#"):
                    # Treat any non-empty line in NEXT section as TODO
                    items.append(Item("TODO", line.strip()[:200], rel, i))
    return items


def render(items: list[Item], repo_root: Path) -> str:
    by_kind: dict[str, list[Item]] = defaultdict(list)
    for it in items:
        by_kind[it.kind].append(it)
    by_source: dict[str, list[Item]] = defaultdict(list)
    for it in items:
        by_source[it.source].append(it)

    out: list[str] = []
    out.append(f"# Consolidated status — {date.today().isoformat()}")
    out.append("")
    out.append("Auto-generated by `tools/consolidate-status.py`. **Do not hand-edit** — re-run instead.")
    out.append("")
    out.append(f"Scanned repo: `{repo_root}`")
    out.append("")
    out.append("## Counts")
    out.append("")
    out.append("| Kind | Count |")
    out.append("|---|---|")
    for k in ("TODO", "BLOCKED", "WIP", "DONE"):
        out.append(f"| {k} | {len(by_kind.get(k, []))} |")
    out.append("")
    out.append(f"Across **{len(by_source)}** source files.")
    out.append("")

    # Top noisy sources
    top = sorted(by_source.items(), key=lambda x: -len(x[1]))[:10]
    out.append("## Top sources (most items)")
    out.append("")
    out.append("| File | Items |")
    out.append("|---|---|")
    for src, group in top:
        out.append(f"| `{src}` | {len(group)} |")
    out.append("")

    # Sections
    for kind, header in [("BLOCKED", "🔴 BLOCKED"), ("WIP", "🟡 In progress"),
                         ("TODO", "🔵 TODO"), ("DONE", "✅ DONE (recent)")]:
        group = by_kind.get(kind, [])
        if not group:
            continue
        # Cap DONE list
        if kind == "DONE":
            group = group[-200:]  # last 200
        out.append(f"## {header}  ({len(group)})")
        out.append("")
        for it in group:
            out.append(f"- {it.text}  — `{it.source}:{it.line}`")
        out.append("")

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--output", default=None)
    ap.add_argument("--include-archive", action="store_true",
                    help="Also scan STATUS/archiveREADME/ (off by default)")
    args = ap.parse_args()

    repo = Path(args.root).resolve() if args.root else REPO_ROOT
    items = scan(repo, args.include_archive)
    text = render(items, repo)
    out_path = Path(args.output) if args.output else repo / "STATUS" / "STATUS.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    counts = {k: sum(1 for it in items if it.kind == k) for k in ("TODO", "DONE", "BLOCKED", "WIP")}
    print(f"Extracted {len(items)} items: {counts}")
    print(f"Report: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
