#!/usr/bin/env python3
"""
parity_check.py — Live diff between BlockChainCore Zig (`core/`) and
Rust port (`core-rust/src/`).

Walks both module trees, normalizes filenames (`X.zig` ↔ `X.rs`), and
reports what's in one side but not the other. Output: Markdown table at
`STATUS/PARITY_LIVE_<date>.md` (overwrite per day).

Companion to the manual `MODULE_ORCHESTRATOR_2026-06-02.md` which has
hand-curated status. This script is the no-effort dynamic check.

Usage:
    python tools/parity_check.py
    python tools/parity_check.py --out custom_path.md
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]   # 1_CORE/BlockChainCore/
ZIG_DIR = ROOT / "core"
RUST_DIR = ROOT / "core-rust" / "src"

# Files we don't care about for parity (build artifacts, tests, façades).
SKIP_PREFIXES = (".", "_")
SKIP_SUFFIXES = ("_test.zig", "_tests.zig", "_test.rs", "_tests.rs", "lib.rs", "main.rs")


def collect(stem_dir: Path, ext: str) -> set[str]:
    """Return set of {module_stem} (without extension) under stem_dir."""
    if not stem_dir.exists():
        return set()
    result = set()
    for p in stem_dir.rglob(f"*{ext}"):
        if any(p.name.startswith(pref) for pref in SKIP_PREFIXES):
            continue
        if any(p.name.endswith(suf) for suf in SKIP_SUFFIXES):
            continue
        # Use the path relative to its root so nested dirs are kept distinct.
        rel = p.relative_to(stem_dir).with_suffix("")
        result.add(str(rel).replace("\\", "/"))
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    today = datetime.now().strftime("%Y-%m-%d")
    default_out = ROOT / "STATUS" / f"PARITY_LIVE_{today}.md"
    ap.add_argument("--out", type=Path, default=default_out,
                    help=f"output Markdown path (default: {default_out})")
    args = ap.parse_args()

    zig_mods = collect(ZIG_DIR, ".zig")
    rust_mods = collect(RUST_DIR, ".rs")

    only_zig = sorted(zig_mods - rust_mods)
    only_rust = sorted(rust_mods - zig_mods)
    in_both = sorted(zig_mods & rust_mods)

    args.out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"# BlockChainCore Zig ↔ Rust Parity — {today}",
        "",
        f"Generated by `tools/parity_check.py` at "
        f"{datetime.now().isoformat(timespec='seconds')}",
        "",
        "## Summary",
        "",
        f"- **Zig modules** (`core/*.zig`): **{len(zig_mods)}**",
        f"- **Rust modules** (`core-rust/src/*.rs`): **{len(rust_mods)}**",
        f"- **In both**: **{len(in_both)}**",
        f"- **Only in Zig** (Rust port pending): **{len(only_zig)}**",
        f"- **Only in Rust** (no Zig counterpart): **{len(only_rust)}**",
        "",
        "Companion to the curated `MODULE_ORCHESTRATOR_*.md`. This script "
        "uses filename matching only — semantic parity (does the Rust port "
        "do what the Zig file does?) lives in the orchestrator doc.",
        "",
        "## Modules only in Zig (Rust port pending)",
        "",
    ]
    if only_zig:
        lines.append("| # | Module |")
        lines.append("|---|---|")
        for i, m in enumerate(only_zig, 1):
            lines.append(f"| {i} | `core/{m}.zig` |")
    else:
        lines.append("_(none — every Zig file has a Rust counterpart by filename)_")
    lines.append("")

    lines.append("## Modules only in Rust (no Zig counterpart)")
    lines.append("")
    if only_rust:
        lines.append("| # | Module |")
        lines.append("|---|---|")
        for i, m in enumerate(only_rust, 1):
            lines.append(f"| {i} | `core-rust/src/{m}.rs` |")
    else:
        lines.append("_(none — Rust is a strict subset of Zig by filename)_")
    lines.append("")

    lines.append("## Modules present in both")
    lines.append("")
    lines.append("<details><summary>Click to expand the full list</summary>")
    lines.append("")
    lines.append("| # | Module |")
    lines.append("|---|---|")
    for i, m in enumerate(in_both, 1):
        lines.append(f"| {i} | `{m}` |")
    lines.append("")
    lines.append("</details>")

    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Parity report -> {args.out}")
    print(f"  zig only:  {len(only_zig)}")
    print(f"  rust only: {len(only_rust)}")
    print(f"  in both:   {len(in_both)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
